### ISSUE TITLE
Suggestion: Disable Android's Captive Portal Detection by Default?

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [LSPosed/MagiskOnWSA#103]
![图片](https://user-images.githubusercontent.com/32929636/143028780-5c14f69b-ebcf-474e-aae8-a7e41f48103a.png)

...We all know that Google's captive portal detection service (aka generate_204) is unstable in mainland China. And Windows already has its very own detection, making the detection inside WSA completely unnecessary.

The problem is that, WSA couldn't keep those settings after shutting down... Do you guys have any ideas?

**Comment by Sonic853** [comment]
Use adb to enter these:
```cmd
// It works in China.
adb shell "settings put global captive_portal_http_url http://connect.rom.miui.com/generate_204";
adb shell "settings put global captive_portal_https_url https://connect.rom.miui.com/generate_204";
```
Then restart WSA.

**Comment by yujincheng08** [comment]
@Sonic853 Thanks
