### ISSUE TITLE
Add busybox?

### ISSUE THREAD

**Issue by Sonic853** [LSPosed/MagiskOnWSA#104]
I tried to install using stericson's busybox and meefik's busybox, but none of them worked.

meefik's busybox outputs the error:
```
### BEGIN INSTALL
Remounting /system to rw ... fail
Copying busybox to /system/xbin ... fail
Changing permissions for busybox ... fail
Copying ssl_helper to /system/xbin ... fail
Changing permissions for ssl_helper ... fail
Removing old applets ... done
Installing new applets ... fail
### END
```

![Snipaste_2021-11-26_13-45-06](https://user-images.githubusercontent.com/8389962/143533006-5be6a1a6-93c9-4a58-9683-99d0bba29958.png)
stericson's busybox exits unexpectedly during installation.

**Comment by yujincheng08** [comment]
Could you try this? https://github.com/Magisk-Modules-Repo/busybox-ndk
