### ISSUE TITLE
An error occured while running install.ps1

### ISSUE THREAD

**Issue by FirstMelody** [LSPosed/MagiskOnWSA#107]
deployment failed with hresult 0x80073CF9

**Comment by yujincheng08** [comment]
#38

**Comment by yujincheng08** [comment]
@okibcn Maybe we could add detection to check if there's a WSA already installed?

**Comment by timbellomo** [comment]
Slightly different error (0x80073CFB), but same root cause (already installed).  My issue is that I'm trying to install for more than one Windows user.  Is there a way to achieve this?

**Comment by yujincheng08** [comment]
The `install.ps1` can now handle the scenario where there's already one WSA installation. It will preserve user data when possible.
