### ISSUE TITLE
[Bug] WSA Apps are unable to exit cleanly when Zygisk+LSPosed is used

### ISSUE THREAD

**Issue by wfjsw** [LSPosed/MagiskOnWSA#110]
### Steps to reproduce/复现步骤

1. Launch an application
2. Exit it with top-right 'X'

### Expected behaviour/预期行为

App exits cleanly.

### Actual behaviour/实际行为

App hangs with the screen turned gray. In some cases a WSA reboot occurred after this.
![image](https://user-images.githubusercontent.com/2220320/143726565-301475c6-375d-4d47-ae37-77e027096f13.png)

### Xposed Module List/Xposed 模块列表

```shell
No LSPosed module was installed.
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed v1.6.3(6253)
```

### LSPosed version/LSPosed 版本

6253

### Android version/安卓版本

Android 11

### Magisk version/Magisk 版本

5d6d2417 (23015)

### Riru version/Riru 版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2021-11-28T10_32_03.459.zip](https://github.com/LSPosed/LSPosed/files/7612705/LSPosed_2021-11-28T10_32_03.459.zip)

**Comment by wfjsw** [comment]
LGTM

**Comment by yujincheng08** [comment]
Merged. Thanks for your info.
