### ISSUE TITLE
Files of module placed incorrectly

### ISSUE THREAD

**Issue by Auncaughbove17** [LSPosed/MagiskOnWSA#113]
When installing [AvinashReddy3108/rclone-mount-magisk](https://github.com/AvinashReddy3108/rclone-mount-magisk/) some files are placed in a wrong directory causing the package to break. 
More detail: https://github.com/AvinashReddy3108/rclone-mount-magisk/issues/4

**Comment by yujincheng08** [comment]
This is definitely not our problem.

The issue is from the module. They didn't test on x64 machines.
