### ISSUE TITLE
magisk is installed but it says "please install magisk"

### ISSUE THREAD

**Issue by qazwsdc** [LSPosed/MagiskOnWSA#114]
![image](https://user-images.githubusercontent.com/37575412/144204083-2e1afa6f-0c4f-461b-9000-f9d987f39704.png)

magisk is installed but it says "please install magisk" when I want to install any module

**Comment by qazwsdc** [comment]
![image](https://user-images.githubusercontent.com/37575412/144210359-f550f65f-f2ca-4ea7-b5ba-f9800df7366e.png)
这是日志

**Comment by yujincheng08** [comment]
是不是没有提示修复环境？好像是 magisk 的 bug

**Comment by yujincheng08** [comment]
应该是模块问题，这个模块没有更新 `META-INF/com/google/android/update-binary`

**Comment by qazwsdc** [comment]
没提示修复环境，你说的那个模块需要怎么更新？
