### ISSUE TITLE
An erro occurred during  run github action workflow

### ISSUE THREAD

**Issue by xlmc** [LSPosed/MagiskOnWSA#115]
I do not know why it happens according to the standard operation , click acions option and slect left part and then run workflow,THX replies
![QEG`91)){GLR(7%S{9CUAK3](https://user-images.githubusercontent.com/23629616/144238235-306c1f20-2131-4461-aa5f-b7ae2e5027b4.png)
w 
![image](https://user-images.githubusercontent.com/23629616/144238416-12b58585-5595-40c1-bc91-52b5c16e0d1c.png)

**Comment by yujincheng08** [comment]
magisk download link is wrong

**Comment by yujincheng08** [comment]
Because you didn't use the latest script...
