### ISSUE TITLE
magisk安装后没提示修复环境，怎么手动修复呢？

### ISSUE THREAD

**Issue by qazwsdc** [LSPosed/MagiskOnWSA#116]
应该是模块问题，这个模块没有更新 `META-INF/com/google/android/update-binary`

_Originally posted by @yujincheng08 in https://github.com/LSPosed/MagiskOnWSA/issues/114#issuecomment-983504144_

**Comment by yujincheng08** [comment]
手动修复治标不治本，先看看 /data/adb/magisk 下面都有什么文件？

**Comment by qazwsdc** [comment]
> 

这里面是空的

**Comment by qazwsdc** [comment]
> 手动修复治标不治本，先看看 /data/adb/magisk 下面都有什么文件？

这里面是空的

**Comment by yujincheng08** [comment]
用这个 magisk 抓个 magisk 日志。如果提示修复环境记得不要修复。
[app-debug.zip](https://github.com/LSPosed/MagiskOnWSA/files/7640893/app-debug.zip)

**Comment by qazwsdc** [comment]
[INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.topjohnwu.magisk signatures do not match previously installed version; ignoring!]

提示这个

**Comment by yujincheng08** [comment]
先卸载已安装的 magisk app，再装我这个

**Comment by yujincheng08** [comment]
知道了，你 wsa 没网了，没网就不提示修补环境了。是 Magisk 的问题

**Comment by yujincheng08** [comment]
topjohnwu/Magisk#5007
