### ISSUE TITLE
不能执行adb disable-verity或adb root，访问/system/etc/security/cacerts/ (cannot execute adb disable-verity or adb root successfully ...)

### ISSUE THREAD

**Issue by AwakeYou** [LSPosed/MagiskOnWSA#119]
想让/system/etc/security/cacerts/可写，但是卡在adb disable-verity，求解。。。
(TO make /system/etc/security/cacerts/ writtable ... any ways?)

**Comment by yujincheng08** [comment]
2021年了，写个 magisk 模块放东西进去，而不是直接改。
