### ISSUE TITLE
WSA缺少系统组件导致无法启动VPN

### ISSUE THREAD

**Issue by CDPumpkin** [LSPosed/MagiskOnWSA#120]
![缺少系统组件](https://user-images.githubusercontent.com/64207250/144753146-e38f08f5-4fd4-4d05-bc99-14fb43d2b358.png)

是否可以让WSA支持VPN呢？

**Comment by vvb2060** [comment]
无法修复，请向微软报告

**Comment by CDPumpkin** [comment]
@huangyixu 感谢你提供的方法。
