### ISSUE TITLE
Artifacts not downloading properly.

### ISSUE THREAD

**Issue by thijsi123** [LSPosed/MagiskOnWSA#122]
Whenever I try to download the x64.exe 
I end up with an 800MB zip file, not the 1.86GB zip file.
![image](https://user-images.githubusercontent.com/64159148/144766751-d21ca5b7-f9ec-4a96-9263-bc0f1c77f3bb.png)
![image](https://user-images.githubusercontent.com/64159148/144766852-475a2e17-0504-4694-9cfe-eb61c2b1b40c.png)

**Comment by yujincheng08** [comment]
expected. the zip you downloaded is compressed.
