### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by CiprianDinca9** [LSPosed/MagiskOnWSA#123]
Hi,

How do I make sure I'm running the latest WSA build? I mean, Microsoft Sotre doesn't detect it so therefore can't update or check from there, any way I can check? And, after checking, how do I update to the latest version without losing GApps, Magisk, and installed apps?

Thanks.

**Comment by yujincheng08** [comment]
To check update, use https://store.rg-adguard.net with category id `858014f3-3934-4abe-8078-4aa193e74ca8`.
To update, rerun the workflow and replace everything from your previous version, and rerun the install script.
