### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by sram910** [LSPosed/MagiskOnWSA#125]
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
(Exception from HRESULT: 0x80073CF9)
Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.
NOTE: For additional information, look for [ActivityId] 53f3e0db-edef-0004-ae8e-f553efedd701 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 53f3e0db-edef-0004-ae8e-f553efedd701
At C:\Users\sram9\Desktop\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly\Install.ps1:20 char:1
+ Add-AppxPackage -Register .\AppxManifest.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\sram9\...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by yujincheng08** [comment]
Duplicate of #107
