### ISSUE TITLE
WSA Settings Language Changed

### ISSUE THREAD

**Issue by itsyourap** [LSPosed/MagiskOnWSA#126]
I had MagiskOnWSA installed previously. Installing the latest version again over the previous version succeeded but the WSA Settings UWP App's Language has changed to any other language which I don't know. The WSA Apps (Google Play, etc) are in English but the WSA Settings isn't.

![Screenshot](https://user-images.githubusercontent.com/90060131/145700254-37e74dd7-ddb1-4956-8a55-43e58e8b0e38.png)

**Comment by itsyourap** [comment]
Steps to Fix This Issue :-

1. Open AppxManifest.xml with any Text Editor
2. Under `<Resources>` Tag, Remove all Tags containing `<Resource Language="XX-XX"/>`
3. Add `<Resource Language="en-us" />` for English (United States) under the same Tag `<Resources>`
4. Save the File
5. Run `install.ps1` with PowerShell

Best Of Luck ❤️

**Comment by itsyourap** [comment]
Developer should fix this issue caused during Workflow build

**Comment by yujincheng08** [comment]
It's Fixed. A typo causes it.
