### ISSUE TITLE
Language is set to German?

### ISSUE THREAD

**Issue by MichaelPriebe** [LSPosed/MagiskOnWSA#129]
I have done all the steps and have been using it perfectly. But for some reason the windows strings are in German. Like the application name, and starting up text, and the back button.

![image](https://user-images.githubusercontent.com/5238952/145716601-670d4bc7-d50d-486b-a0fc-1785b5aa062f.png)

**Comment by yujincheng08** [comment]
Already fixed here https://github.com/LSPosed/MagiskOnWSA/commit/e9cb3831535234d04895d1df926dc9c4dbb8d6ce

**Comment by canyie** [comment]
duplicated of #128
