### ISSUE TITLE
Shortcuts removed on reinstall

### ISSUE THREAD

**Issue by mkelly72** [LSPosed/MagiskOnWSA#130]
When you install over an existing installation, the start menu shortcuts and the ability to uninstall via Windows Settings is removed. That did not happen before the language issue was corrected. The userdata.vhdx is retained and the apps do still exist inside the Android image, but the only way to open the apps is if you made a backup of the start menu shortcuts, go through the arduous process of manually recreating them, or to open via Google Play or adb. Uninstallation also is only possible through Google Play or adb, not through Windows Settings.

**Comment by yujincheng08** [comment]
This is because WSA will be temporarily removed and installed because of error 0x80073CF6 (#92). But now I managed to fix this issue by `Stop-Process -Name "wsaclient"`. Please try the latest version. Sorry but I don't know how to recover the shortcuts.

**Comment by mkelly72** [comment]
This worked perfectly. Thank you for your efforts.

I was able to restore the shortcuts before trying the latest version. Basically I did what I used to do before the script had the ability to install over an existing installation, which is:

1. Kill WSA.
2. Backup the existing userdata.vhdx file.
3. Uninstall WSA.
4. Reinstall WSA with the new version.
5. Log into Google Play.
6. Reinstall all apps from Google Play (which is where all my apps were installed from).
7. Reinstall anything else from all other sources (none for me).
8. Kill WSA again.
9. Replace the new userdata.vhdx file with the one backed up in step 2.
10. Restart WSA (i.e. open an app).

Reinstalling the apps on a fresh install gets the Windows side of things right again, and restoring the userdata.vhdx file restores Android to where it was. But I'm glad I did not have to do that again installing the latest version.
