### ISSUE TITLE
NoGApps版本的SAF无法读取存储目录

### ISSUE THREAD

**Issue by IamChocolate** [LSPosed/MagiskOnWSA#131]
第一次用NoGApps版本，不知道是一直这样还是最近几个版本导致的。
包含OpenGApps的版本就没有这个问题
![屏幕截图1.png](https://user-images.githubusercontent.com/94111173/145793507-54fdf91b-d558-4566-89fc-5ca1b872a5d9.png)
![屏幕截图2.png](https://user-images.githubusercontent.com/94111173/145793605-117a3129-0bb0-4b02-b2af-59acba10980e.png)

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/145795490-0a733917-3ca8-48c1-84d3-4575b5bd5f55.png)
我这里没问题呀

**Comment by IamChocolate** [comment]
> ![image](https://user-images.githubusercontent.com/5022927/145795490-0a733917-3ca8-48c1-84d3-4575b5bd5f55.png) 我这里没问题呀

试试SAF的文件夹访问授权界面？一片空白

**Comment by IamChocolate** [comment]
Shizuku在包含OpenGApps版本正常的导出
![屏幕截图3.png](https://user-images.githubusercontent.com/94111173/145804910-c4f4a5b5-ebcd-4e63-9755-5bb803017663.png)

**Comment by IamChocolate** [comment]
> Shizuku在包含OpenGApps版本正常的导出 

不只是SAF，Termux在NoGApps似乎也有问题 切换GApps-Pico版本后解决 https://github.com/2moe/tmoe-linux/issues/103
![屏幕截图3.png](https://user-images.githubusercontent.com/94111173/145804910-c4f4a5b5-ebcd-4e63-9755-5bb803017663.png)

**Comment by yujincheng08** [comment]
修复只测试了 SAF 能用，termux 没测。如果还有问题另开 issue 吧。

**Comment by Ccyuyzs** [comment]
> 修复只测试了 SAF 能用，termux 没测。如果还有问题另开 issue 吧。

看到了，感谢及时回复/修复

**Comment by IamChocolate** [comment]
> 修复只测试了 SAF 能用，termux 没测。如果还有问题另开 issue 吧。

Termux在NoGApps版本依然存在问题
`/system/bin/sh: syntax error: unexpected '('`
而GApps-Pico版就无法复现
但测试不够充分...所以不开新Issue了

**Comment by yujincheng08** [comment]
也有可能是机型问题。GApps 版本会把机型改成 pixel5 的，WSA 默认机型很奇怪可能有奇怪字符没转译然后导致命令拼接之后语法错误。建议定位到具体命令行后检查。

**Comment by yujincheng08** [comment]
请先尝试 `su -c resetprop ro.product.model WSA`

**Comment by yujincheng08** [comment]
亲测 `su -c resetprop ro.product.model WSA` 之后重装容器就能启动容器了。雀食是那个括号的问题。

**Comment by IamChocolate** [comment]
> 亲测 `su -c resetprop ro.product.model WSA` 之后重装容器就能启动容器了。雀食是那个括号的问题。

明白了 感谢解答
