### ISSUE TITLE
WSA不能正常连接网络

### ISSUE THREAD

**Issue by CDPumpkin** [LSPosed/MagiskOnWSA#132]
之前构建的版本都一切正常，昨晚拉取了新的代码后构建的WSA更新后就无法连接网络。
目前找到的唯一解决方法是开着代理才能恢复，一旦关闭又会无网络。

开着代理一切正常
![图1](https://user-images.githubusercontent.com/64207250/145874688-5a1f5515-a851-4908-a6ad-3155e4847125.jpg)

关闭代理后，一切APP无网络
![图2](https://user-images.githubusercontent.com/64207250/145874895-56f50168-cc8b-42ab-84ae-ed10b5fc6672.jpg)

**Comment by yujincheng08** [comment]
亲测 https://github.com/CDPumpkin/MagiskOnWSA/actions/runs/1574164335 没问题能联网

**Comment by yujincheng08** [comment]
你可以在 `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat` 查看日志定位问题。
