### ISSUE TITLE
(not issue) shall i delete the unzipped folder?

### ISSUE THREAD

**Issue by Ratulhasan14789** [LSPosed/MagiskOnWSA#133]
I'm running low on ssd storage. so just asking, shall i delete the installer folder (the unzipped one) after running the installation or it is neccesary for future use (was told to keep by the Google patchers repo)?
ps: also kindly add a FAQ in the readme.md file so that silly questions like this will not appear. thank you

**Comment by yujincheng08** [comment]
No
