### ISSUE TITLE
(Not an issue) How to update WSA

### ISSUE THREAD

**Issue by Wizards-god** [LSPosed/MagiskOnWSA#134]
I just found out that WSA got updated to 1.8.32828, and I have 1.7.32815. I just wanted to know how to update WSA Without Losing my data. I have used your method to get GApps and Magisk on WSA, so thought this would be the best place to ask for a solution.
<img width="919" alt="image" src="https://user-images.githubusercontent.com/70703332/146122574-c8abc5a9-ea09-47e8-809f-41c349b2e820.png">

**Comment by yujincheng08** [comment]
read FAQ

**Comment by Wizards-god** [comment]
Could you please link to it.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/MagiskOnWSA#faq

**Comment by Wizards-god** [comment]
Thank you!

**Comment by Wizards-god** [comment]
And while I'm at it, Can you suggest to me if I should use the Canary Version of Magisk or The Stable one

**Comment by yujincheng08** [comment]
read faq

**Comment by Wizards-god** [comment]
Ok, Thank you for the assistance.
