### ISSUE TITLE
install Powershell script not working.

### ISSUE THREAD

**Issue by Hehehehehehehehe1200** [LSPosed/MagiskOnWSA#137]
if i open it it opens for 2 secs and poof! its gone.

**Comment by yujincheng08** [comment]
hv the script prompt UAC request?

**Comment by Hehehehehehehehe1200** [comment]
No

**Comment by Hehehehehehehehe1200** [comment]
it promps an error for half a sec and poof! gone

**Comment by yujincheng08** [comment]
so it may because you dont hv enough permission

**Comment by Hehehehehehehehe1200** [comment]
wdym?

**Comment by yujincheng08** [comment]
i mean your permission cannot be evaluated to an administrator

**Comment by yujincheng08** [comment]
and since I cannot see the prompted error, we cannot help u but just guess :)

**Comment by yujincheng08** [comment]
you can launch a powershell and run the script manually `powershell -ExecutionPolicy Bypass -File install.ps1` and see what on earth is going on.

**Comment by Hehehehehehehehe1200** [comment]
ok thanks

**Comment by Hehehehehehehehe1200** [comment]
i know why now i have powershel 5.1 instead of 7

**Comment by yujincheng08** [comment]
so our script is not compatible with pwsh 7?

**Comment by Hehehehehehehehe1200** [comment]
still not workin :?

**Comment by yujincheng08** [comment]
no idea unless useful error msg is shown

**Comment by Hehehehehehehehe1200** [comment]
wait im looking for it please wait

**Comment by Hehehehehehehehe1200** [comment]
here is the picture: https://imgur.com/a/fcWyZZD

**Comment by yujincheng08** [comment]
https://stackoverflow.com/a/9167524

**Comment by Hehehehehehehehe1200** [comment]
already did it and no error but still opens for only a couple secs :/

**Comment by Hehehehehehehehe1200** [comment]
can u make me a powershell command that bypasses it ik that powershell has one but idk how to put the file direc. in it

the file directory is :C:\Users\Rita Conley\Desktop\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly

**Comment by Hehehehehehehehe1200** [comment]
🔢

**Comment by yujincheng08** [comment]
holding shift and right click thw wsa folder, select open powershell
then type `powershell -ExecutionPolicy Bypass -File install.ps1`

**Comment by Hehehehehehehehe1200** [comment]
mk

**Comment by Hehehehehehehehe1200** [comment]
Warning: failed to start as asministrator ??

**Comment by yujincheng08** [comment]
good. the problem is exactly what I thought.

**Comment by Hehehehehehehehe1200** [comment]
ok?

**Comment by Hehehehehehehehe1200** [comment]
wait wait wait

**Comment by Hehehehehehehehe1200** [comment]
how do i fix it tho?

**Comment by Leshu7w7** [comment]
Just run powershell as Administrator ([Here](https://www.javatpoint.com/powershell-run-as-administrator) you can find some ways to run it as Admin) then when it's open, you need to copy and paste in powershell the following command: `Set-ExecutionPolicy -ExecutionPolicy Bypass` and then try executing the script again, it should work as intended

**Comment by shrikant2002** [comment]
still not working after setting Set-ExecutionPolicy -ExecutionPolicy Bypass
