### ISSUE TITLE
WSA crashes when granting root privileges to MiXplorer

### ISSUE THREAD

**Issue by puiemonta1234** [LSPosed/MagiskOnWSA#149]
Steps to reproduce:
1. Install MiXplorer
2. Go to the Root tab on the left
3. Click Grant on Magisk's popup
4. WSA crashes

I also tested Root Checker, but that one doesn't crash

[logcat.zip](https://github.com/LSPosed/MagiskOnWSA/files/7751522/logcat.zip)

**Comment by yujincheng08** [comment]
```
12-21 11:51:02.147   996  1549 I ROOT    : mount -o rw,remount /dev/pmem0 /
```
MiXplorer tries to remount `/` as `rw` and that will cause crash on WSA. Don't enable auto remount feature.
