### ISSUE TITLE
WSA apps not running

### ISSUE THREAD

**Issue by Kevin8675** [LSPosed/MagiskOnWSA#150]
This issue seems to be a little similiar to #102 but has some differences. 

Running the app looks the same as #102 but after I run the app, the VmmemWSA task continues running, even after the app closes. Wsa worked before I updated to version 1.8.32828.0. Doing a quick look at the log, there does seem to be many errors. 

Can anyone help?

[22122021143739.log](https://github.com/LSPosed/MagiskOnWSA/files/7764832/22122021143739.log)

**Comment by HuskyDG** [comment]
That maybe WSA problem not Magisk

**Comment by 2001Muath** [comment]
don't work

https://1drv.ms/u/s!Anv5s3lwU_MbgXEnPTMrDVrjMz5O

**Comment by 2001Muath** [comment]
Stop-process : Cannot find a process with the name "wsaclient". Verify the process name and call the cmdlet again.

**Comment by Kevin8675** [comment]
> Stop-process : Cannot find a process with the name "wsaclient". Verify the process name and call the cmdlet again.

I am getting this error as well. When running Install.ps1, it breifly appears for less then a second.

**Comment by Kevin8675** [comment]
Completlely uninstalling and reinstalling WSA fixed this issue (can't believe I didn't try this earlier)
