### ISSUE TITLE
I don't know what to do

### ISSUE THREAD

**Issue by Jakeh9777** [LSPosed/MagiskOnWSA#157]
I keep getting this no matter what:
"WARNING: Failed to launch start as Administrator
Press any key to exit"

**Comment by Jakeh9777** [comment]
I also got this too:

Installing MagiskOnWSA...
Stop-Process : Cannot find a process with the name "wsaclient". Verify the process name and call the cmdlet again.
At C:\Users\Mr. Chillo\Downloads\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly\Install.ps1:68 char:1
+ Stop-Process -Name "wsaclient"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (wsaclient:String) [Stop-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand

Add-AppxPackage : Cannot find path 'C:\WINDOWS\system32\AppxManifest.xml' because it does not exist.
At C:\Users\Mr. Chillo\Downloads\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly\Install.ps1:69 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\system32\AppxManifest.xml:String) [Add-AppxPackage], ItemNot
   FoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

All Done
Press any key to exit

**Comment by Wombosvideo** [comment]
I got the same error. The problem was my script execution policy not allowing me to run any scripts. To overcome this, but not enable scripts globally, you can run PowerShell as **Administrator** in the extracted directory and run
```bash
powershell -ExecutionPolicy Bypass -File Install.ps1
```

PowerShell can be run as admin by pressing `Windows + X` and selecting `Windows Terminal (Admin)`. You then navigate to your extracted directory using `cd "<your-directory-path>"`.

**Comment by Wombosvideo** [comment]
> I also got this too:
> 
> Installing MagiskOnWSA... Stop-Process : Cannot find a process with the name "wsaclient". Verify the process name and call the cmdlet again. At C:\Users\USER\Downloads\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly\Install.ps1:68 char:1
> 
> * Stop-Process -Name "wsaclient"
> * ```
>     + CategoryInfo          : ObjectNotFound: (wsaclient:String) [Stop-Process], ProcessCommandException
>     + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand
>   ```
> 
> Add-AppxPackage : Cannot find path 'C:\WINDOWS\system32\AppxManifest.xml' because it does not exist. At C:\Users\USER\Downloads\WSA-with-magisk-GApps-pico_1.8.32828.0_x64_Release-Nightly\Install.ps1:69 char:1
> 
> * Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
> * ```
>     + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\system32\AppxManifest.xml:String) [Add-AppxPackage], ItemNot
>    FoundException
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
>   ```
> 
> All Done Press any key to exit

The first of these errors is thrown when Windows Subsystem for Android was not previously installed and/or is not running at the moment. Don't worry about this error.

The second error suggests you tried to run `Install.ps1` using its full path (in the wrong working directory). Try my method above and give feedback if you run into this problem again.

**Comment by Barshan-Mandal** [comment]
@all this version is bugful.Use previous

**Comment by Barshan-Mandal** [comment]
This community never helps
