### ISSUE TITLE
WSA Crashes after trying to merge the last update

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [LSPosed/MagiskOnWSA#158]
![image](https://user-images.githubusercontent.com/78225592/147780764-191505f3-558a-4425-9ca2-cc001773caa1.png)
It shows me this error above and It doesn’t't want to start even after the uninstallation and reinstallation of the app

**Comment by yujincheng08** [comment]
This error could be ignored.

**Comment by MohammedMehdiTBER** [comment]
> This error could be ignored.

Still wsa won't start.

**Comment by yujincheng08** [comment]
what do you mean by `won't start`

**Comment by MohammedMehdiTBER** [comment]
When I click on the icon of wsa in start menu, It doesn't start.

**Comment by yujincheng08** [comment]
what icon you click? icon of wsa or icon of wsa's app?

**Comment by MohammedMehdiTBER** [comment]
> what icon you click? icon of wsa or icon of wsa's app?

![image](https://user-images.githubusercontent.com/78225592/147781390-4a4fc66d-9fb9-4376-ba00-4d7c591aecbe.png)

**Comment by yujincheng08** [comment]
Then there's nothing we can do. It's not a bug of ours.

**Comment by MohammedMehdiTBER** [comment]
I removed the old folder and just extracted it as new, and the app launched then I restored my userdata.vhdx, yet It is taking a long time in the loading screen when you click on files to launch the android.
