### ISSUE TITLE
Blank icons after upgrading to latest build

### ISSUE THREAD

**Issue by ayesse** [LSPosed/MagiskOnWSA#160]
I followed the guide to upgrade to a newer build: I ran a new build, downloaded the artifact, overwritten all the files and ran Install.ps1. Everything went fine and works normally, but now all my android apps have a blank icon. When I click on apps shortcut properties and I click "Change icon" a warning pops up and says "Unable to find [...].ico", as if some icon files were deleted

![image](https://user-images.githubusercontent.com/24982281/147824022-468b9584-b2ae-45d4-a162-835b86fd962c.png)

![image](https://user-images.githubusercontent.com/24982281/147823975-f03e8019-f923-4190-a53b-56d843e0f868.png)

**Comment by yujincheng08** [comment]
See FAQ to manager icon by installing WSAHelper.
