### ISSUE TITLE
After installing the app shopee.apk(shopee) All windows disappeared. You have to reinstall all windows

### ISSUE THREAD

**Issue by tee4341** [LSPosed/MagiskOnWSA#164]
After installing the app shopee.apk(shopee) All windows disappeared. You have to reinstall all windows
https://www.mediafire.com/file/m6879fbxw6f5q9i/shopee-th-2-81-21.apk/file
https://youtu.be/JqV9yoiNBH4
https://youtu.be/_5-nWs-ri7M

**Comment by yujincheng08** [comment]
It's not our issue.
