### ISSUE TITLE
WSA working, with magisk root, but cannot use LSPosed

### ISSUE THREAD

**Issue by coinzdude** [LSPosed/MagiskOnWSA#168]
LSPosed is installed, but I cannot get past this below.

There's some mention of "install riru".  Without more details, I attempted to install rirud.apk from riru-v26.1.4.r522.8b379cedb5-release.zip but that did not make any visible change. 

![image](https://user-images.githubusercontent.com/58857646/148666647-f30c9dfc-34cc-4ea1-b135-83f9a2983a6e.png)

**Comment by yujincheng08** [comment]
Use zygisk version then.

**Comment by coinzdude** [comment]
I was able to use magisk and install the riru zip and I see this, but I still cannot use lsposed.  I will look for zygisk version of lsposed?

![image](https://user-images.githubusercontent.com/58857646/148666702-b09a57c5-54e9-4a33-9489-d247f47a78af.png)

**Comment by yujincheng08** [comment]
You just install riru. you didnt install lsposed... what the ...

**Comment by coinzdude** [comment]
I'm not sure. I am new to LSPosed/Riru. I only have used Xposed and modules through cyanogenmod and stock roms on android years back. 

The LSPosed app appears to be installed as part of the full MagiskOnWSA build script, and is also available in the google play store.  I will try to find "LSPosed zygisk" version to install. 

![image](https://user-images.githubusercontent.com/58857646/148666769-8fcd67bc-cb9f-428f-8436-4c7d8ffa8696.png)

**Comment by yujincheng08** [comment]
Flash the zip https://github.com/LSPosed/LSPosed/releases/tag/v1.6.5

**Comment by coinzdude** [comment]
Brilliant!
