### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by YOSI-COHEN** [LSPosed/MagiskOnWSA#172]
I downloaded the installation app, and ran the file but the command line opens for a moment and runs out.

**Comment by kuntalsaha05** [comment]
magisk in installing

**Comment by bicheondev** [comment]
I had the same issue, but here's how I fixed it.
1. Open Terminal as admin
2. Navigate(``cd``) to WSA-with-magisk~ file you extracted.
3. Enter ``PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1``
4. The Script will now start.

**Comment by YOSI-COHEN** [comment]
I did not understand where to insert "CD"
In a folder?
Showing error!

![image](https://user-images.githubusercontent.com/82176699/149508372-8175be65-a75a-4e5b-98bf-2a2cd62ed964.png)

**Comment by yujincheng08** [comment]
Input `cd "{X:\path\to\your\extracted\folder}"` and press `enter`, and remember to replace `{X:\path\to\your\extracted\folder}` including the `{}`, for example `cd "D:\wsa"`

**Comment by YOSI-COHEN** [comment]
I now put it in drive C
Tell me what to write in the code

**Comment by bicheondev** [comment]
you mean ``C:￦Install.ps1``? or ``C:￦(Some kind of folder)￦Install.ps1``?

**Comment by YOSI-COHEN** [comment]
![image](https://user-images.githubusercontent.com/82176699/149529324-3457c565-0488-46c7-953d-2384589bafc1.png)
