### ISSUE TITLE
Actions for WSA + OpenGApps Nano x64 stuck at downloading OpenGApps

### ISSUE THREAD

**Issue by ichlaffterlalu** [LSPosed/MagiskOnWSA#179]
The ARM64 job is succeeded but the x64 is stuck at downloading OpenGApps until it gets terminated automatically by GitHub.
![image](https://user-images.githubusercontent.com/5210946/149610127-4183678b-e66f-4add-a12a-917aa07f83b4.png)

**Comment by yujincheng08** [comment]
try again

**Comment by ichlaffterlalu** [comment]
![image](https://user-images.githubusercontent.com/5210946/149610237-97f5e3d5-45b6-4025-8d7e-e66557da0d7c.png)

Now it is a different error

**Comment by yujincheng08** [comment]
try again

**Comment by ichlaffterlalu** [comment]
Okay, successful trying after more than 5 tries...
I wonder if there's any reliable mirror other than SourceForge you can include.

**Comment by yujincheng08** [comment]
nah. I think thats github's issue.
