### ISSUE TITLE
Problems with registering windows.firewallRules - Line 68 Install.ps1

### ISSUE THREAD

**Issue by xp499** [LSPosed/MagiskOnWSA#182]
I'm having problems while manually executing Install.ps1 script claiming about this error:
`Installing MagiskOnWSA...`
`Stop-Process : No process with "wsaclient" name. Check process name and run cmdlet.mdlet again: C:\Users\user\Documents\WSA-with-magisk-NoGApps_1.8.32836.0_x64_Release-Nightly\Install.ps1: 68 Char: 1 Windows   cessing+ Stop-Process -Name "wsaclient" `                                                                                       `WSA-with-magisk-NoGApps_1.8.32836.0_x64_Release-Nightly\                               ción de    + CategoryInfo: ObjectNotFound: (wsaclient:String) [Stop-Process], ProcessCommandExceptionutionPolicy Bypass           + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand`
`C:\UAdd-AppxPackage : Implementation error with HRESULT: 0x80073CF6, Package could not register.                            AppxManifest.xml(191,6): error 0x800706D9: couldn't register                                                    MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe package because following detected error while registering extension windows.firewallRules: No endpoints available from endpoint designator. Try again and get in touch with package's publisher if error persists
NOTE: To obtain additional information, please check [ActivityId] 3857fac0-0bac-0000-1998-5838ac0bd801 on event registry or use CLI Get-AppPackageLog-ActivityId 3857fac0-0bac-0000-1998-5838ac0bd801
on C:\Users\user\Documents\WSA-with-magisk-NoGApps_1.8.32836.0_x64_Release-Nightly\Install.ps1: 69 Carácter: 1`
`+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\user\D...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

All Done
Press any key to exit`

**Comment by xp499** [comment]
I believe is all related to this script as i applied it earlier to deploying your SW from your repo: https://www.reddit.com/r/Windows11/comments/qcxyjl/disable_microsoft_defender_in_windows_11/

**Comment by yujincheng08** [comment]
our script has nothing to do with the firewall.

**Comment by iBrougher** [comment]
I have the same problem. I can install clean wsa, but this one getting me same error
![image](https://user-images.githubusercontent.com/83395945/150702191-efee5322-b51e-4c9f-93de-c6f0a8b5c736.png)
