### ISSUE TITLE
"Microsoft.VCLibs.140.00 missing

### ISSUE THREAD

**Issue by chaoscreater** [LSPosed/MagiskOnWSA#190]
FYI, I got this error when I ran the script and it's because I'm missing the VC++ redistributables. On a brand new Win11 install, it's gonna need that. Maybe worth packaging it into the script install?

Can use this:
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by yujincheng08** [comment]
We have vclibs including in the zip

https://github.com/LSPosed/MagiskOnWSA/blob/ffc75eaca7098c48e87eba9490c8153c2c2018e8/.github/workflows/magisk.yml#L57-L62

https://github.com/LSPosed/MagiskOnWSA/blob/ffc75eaca7098c48e87eba9490c8153c2c2018e8/.github/workflows/magisk.yml#L470

**Comment by chaoscreater** [comment]
Well, I'm using the latest nightly build on a brand new Win11 VM and I'm getting this, so something is wrong then:

https://github.com/chaoscreater/MagiskOnWSA/suites/5038058939/artifacts/150669606

I've created 5 Win11 VMs in Azure, fresh install. Out of the 5 VMs with identical SKU, 3 of them showed this error and the other 2 were OK. Using exactly the same build from Github.

**Comment by chaoscreater** [comment]
So, looks like the real fix is actually not by installing VC++ redistributables, but just running update in MS Store:
https://docs.microsoft.com/en-us/answers/questions/617012/windows-11-andriod-installing-wsa-powershell-0x800.html

Maybe worth doing a check in Powershell to see if the MS Store apps are up to date?
