### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Murderhead** [LSPosed/MagiskOnWSA#192]
How can I unistall the whole thing again?

**Comment by yujincheng08** [comment]
Yes.

**Comment by Murderhead** [comment]
How?

**Comment by mkelly72** [comment]
> How?

Same way you uninstall any other package. Settings > Apps > Apps & features then find Windows Subsystem for Android. Doing so will remove everything, including the userdata.vhdx which is where your Android user settings, installed apps and saved files resides.

**Comment by Murderhead** [comment]
Thanks, but I was hoping for an easier quicker way with an powershell script because I had lot's of freezes and bluescreens. But I managed to get ride of it. Hopefully everything runs stable again. I will see overtime.
