### ISSUE TITLE
Text editing causes GBoard to pop up

### ISSUE THREAD

**Issue by supertanno** [LSPosed/MagiskOnWSA#195]
When editing text in an app, GBoard pops up with seemingly no way to disable it, despite me using a hardware keyboard.

![afbeelding](https://user-images.githubusercontent.com/10236326/151287650-9e651ed7-27d0-4529-9097-c2022b6d4a8c.png)
![afbeelding](https://user-images.githubusercontent.com/10236326/151287762-254ee07c-3a63-48da-aba4-31c203cda7e2.png)

**Comment by supertanno** [comment]
Currently, there's a workaround that involves disabling GBoard in the app settings, but this isn't the best permanent fix and does make using the apps on a Windows tablet a lot harder.

**Comment by PeterNjeim** [comment]
This issue can't possibly be related to MagiskOnWSA, rather, WSA itself or even Android. I don't face this issue.
