### ISSUE TITLE
Ability to Changing Device Type

### ISSUE THREAD

**Issue by SolHeliosFire** [LSPosed/MagiskOnWSA#198]
I was wondering if It would be possible to change the device type? Currently, it thinks it's a Pixel 5 and uses the phone apps. Can you make it so that we can use tablet apps?

**Comment by cpalenshus** [comment]
To change it to a Samsung Tab S7, what values would we put in lines 355-361? Or how would we find these out?
I'm guessing the following is partially right:
355: "samsung"
356: "Samsung"
357-359: ?
360: "S7"
361: ?
