### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by AkzhanArdaki** [LSPosed/MagiskOnWSA#199]
After installing it by following video guide on main page i received an error. After i launch play store i need to login into my google account. After i press "Sign in" I'm receiving this message "Couldn't sign in. You don't have a network connection. This could be a temporary problem. Try again or connect to another WI-FI network". I'm using my PC witch does not have wifi module. What can i do with this problem?

**Comment by alex-sandro92** [comment]
My PC has no wifi but internet works on WSA, it is likely a temporary issue. Have you tried restarting wsa?

**Comment by AkzhanArdaki** [comment]
> My PC has no wifi but internet works on WSA, it is likely a temporary issue. Have you tried restarting wsa?

Restarting WSA didn't helped, but restarting PC did. Thank you anyway
