### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by ValgulNecron** [LSPosed/MagiskOnWSA#200]
![image_2022-01-29_182051](https://user-images.githubusercontent.com/39313199/151670611-5e33bc22-bdd0-4c2d-85bf-db519bac1a67.png)
when i launch the install.ps1 i have this error how to repair it since WSA dont want to lauch afeterward 

edit : for the part in french it means "imposible to find the procesus named "wsaclient". verify the name and called it

**Comment by yujincheng08** [comment]
this error can.be ignored.
