### ISSUE TITLE
Integrate with WSAPackagingTool

### ISSUE THREAD

**Issue by OnePeach47** [LSPosed/MagiskOnWSA#208]
Hello, can you please integrate MagiskOnWSA with [WSAPackagingTool](https://github.com/WSA-Community/WSAPackagingTool)?

[WSAPackagingTool](https://github.com/WSA-Community/WSAPackagingTool) allows you to repack modified WSA into custom .msixbundle and sideloading it into WindowsApps folder instead by using ```AddAppxPackage -Register```.

**Comment by yujincheng08** [comment]
I afraid, No:

1. That project does not have a proper license, but luckily it's just a very simple wrapper of makeappx.exe.
2. Those binaries are from Microsoft and can only be run on Windows, making it hard (but may still be possible via wine) to run on Linux
3. Repacking as `msixbundle` needs self-signing and it is hard to keep a unique cert for every single user on Github Action
