### ISSUE TITLE
怎么快捷方式全没了

### ISSUE THREAD

**Issue by NineMeowHL** [LSPosed/MagiskOnWSA#212]
![QQ截图20220205171413](https://user-images.githubusercontent.com/51258015/152636846-ff6a3f7d-e3ab-43ce-974a-f12e3dcf5b9b.png)

第一次安装的时候直接用Add-AppxPackage，没运行ps1文件，之后发现谷歌登录不了就用install.ps1重新弄了一次，弄完之后之前装的应用，快捷方式全没了，但是发现其实应用和用户数据还是在的，只不过怎么图标怎么都没了，这种情况请问怎么处理

**Comment by vvb2060** [comment]
阅读说明
