### ISSUE TITLE
Shamiko help

### ISSUE THREAD

**Issue by animetrom** [LSPosed/MagiskOnWSA#214]
I would like to download the shamiko module file, but the link that takes to the conversation I am not in the private group. Would you have the link to enter?
Link message that releases in FAQ: https://t.me/c/1414270883/25744

**Comment by fanterihackk** [comment]
> I would like to download the shamiko module file, but the link that takes to the conversation I am not in the private group. Would you have the link to enter?
> Link message that releases in FAQ: https://t.me/c/1414270883/25744

Write me I will help you
