### ISSUE TITLE
如何将数据移动到D盘

### ISSUE THREAD

**Issue by knock200508** [LSPosed/MagiskOnWSA#218]
如何将%USERPROFILE%\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx移动到D盘

**Comment by yujincheng08** [comment]
`New-Item -ItemType Junction -Path "Link" -Target "Source Target"`

**Comment by knock200508** [comment]
emmm，不是单纯的复制，是想把was的数据整个移到D盘。官方的可以在设置里移动，这个版本不知道如何操作

**Comment by yujincheng08** [comment]
谁告诉你这是复制？

**Comment by knock200508** [comment]
New-Item -ItemType Junction -Path "D:\" -Target "%USERPROFILE%\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx‘’是这样使用嘛？

**Comment by yujincheng08** [comment]
www.google.com 请
