### ISSUE TITLE
WSA screen resolution

### ISSUE THREAD

**Issue by henrynopo** [LSPosed/MagiskOnWSA#227]
Hi. This is a very productive solution to install WSA with GMS.

Has anyone encountered the screen resolution issue on some apps? Which has been raised in 
https://www.reddit.com/r/Windows11/comments/qe0av7/is_it_possible_to_change_the_screen_resolution_or/
https://techcommunity.microsoft.com/t5/windows-insider-program/changing-screen-resolution-orientation-in-wsa/m-p/2877385

Looking forward to some prompt solutions.

**Comment by RaSan147** [comment]
its microsoft made limitation, i don't think magisk can do any help about this issue 🤔

**Comment by yujincheng08** [comment]
Seek help from Microsoft
