### ISSUE TITLE
Stuck in Loop trying to use Family Link

### ISSUE THREAD

**Issue by RHOPKINS13** [LSPosed/MagiskOnWSA#232]
I've been trying to use this on my son's laptop, so he can play some educational games from the Google Play Store, some of which require Google Play Services to work. He has a child's account (under 13) that is managed via Family Link. Unfortunately, when I try to sign him in on the Play Store, it gives me an error: "This profile manager is required for Google Accounts managed with Family Link."

I built it using the "super" variant of opengapps. I've also tried manually sideloading the Family Link manager and helper APKs, but that did not help.

I found a "fix" for the issue here: https://forum.xda-developers.com/t/guide-ultimate-fix-for-google-family-link-onboarding-loop.4377475/

I've installed WSL, and can mount and modify system.img when WSA is turned off. It looks like PlayStoreOverlay.apk is already in /system/product/overlay, but I can't find the Family Link Helper and Family Link Manager APKs in /system/priv-app, and they need to be installed as System Apps. I've downloaded opengapps and extracted everything, but I can't find the Family Link APKs anywhere.

Can somebody help me out here? Can we fix this so that if someone logs in to a child's account on the play store, it doesn't end up stuck in this loop?

**Comment by yujincheng08** [comment]
Apparently, you are missing those family link apks. If you want to integrate those apks, you can upload files to `arm64/gapps/priv-app` and `x86_64/gapps/priv-app` in your repo and those apks will be automatically integrated into your WSA build.

**Comment by yujincheng08** [comment]
Apks could be downloaded from third-party websites like:

https://apkpure.com/family-link-manager/com.google.android.apps.kids.familylinkmanager
https://apkpure.com/family-link-child-and-teen/com.google.android.apps.kids.familylinkhelper
