### ISSUE TITLE
Install.ps1 : "A specified logon session does not exist. It may already have been terminated."

### ISSUE THREAD

**Issue by SmirkVG** [LSPosed/MagiskOnWSA#233]
The message, as it appears, looks like this:

```
Start-Process : This command cannot be run due to the error: A specified logon session does not exist. It may already
have been terminated.
At C:\WSA-with-magisk-GApps-pico_1.8.32837.0_x64_Release-Nightly\Install.ps1:15 char:5
+     Start-Process "wsa://com.topjohnwu.magisk" 
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       + CategoryInfo              : InvalidOperation: (:) [Start-Process], InvalidOperationException
       + FullyQualifiedErrorId  : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

The same error happens for the following command "Start-Process "wsa://com.android.vending"

From my understanding, PowerShell continues running scripts even if it encounters an error. The error I am encountering appears to be the last two commands anyway, so in theory, all the necessary components should have been installed(?). If I try to run these commands manually, it appears WSA did not get installed on the system since it prompts me to look for an app in the Store.

My Windows user account is a standard user signed in with a Microsoft account. I ran the Powershell script, and also tried the suggested workaround by using the Admin Windows Terminal and trying to manually start the script there. Same results.

Any tips? Thanks for your great work.

**Comment by yujincheng08** [comment]
I think there're some previous errors

**Comment by Burkino** [comment]
i have the same issue, if i run the install script it errors
the "solution" is to actually change over to an administrator account and run the install script.
HOWEVER, it will only get installed for that administrator and not other users

**Comment by SmirkVG** [comment]
> i have the same issue, if i run the install script it errors the "solution" is to actually change over to an administrator account and run the install script. HOWEVER, it will only get installed for that administrator and not other users
> 
> what you can do is
> 
> 1. open control panel
> 2. change your standard account to an administrator
> 3. run the install script
> 4. change your account back to a standard user

Thanks man, simple fix makes sense. After doing this, I ran into another issue where I was told the WSA was already installed even though I removed it -- it was because there was a reference to it leftover on my Admin account in the installed programs. After removing the program there, I was able to get things working!

So, PSA: don't try to run the install until you've ensured that any existing WSA's are uninstalled from _**all**_ user accounts and that the user account you're trying to install this WSA to is an administrator account.

**Comment by Hitomi98** [comment]
I tried this and am getting the error:
`Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFB, The provided package is already installed, and`

Any ideas?
