### ISSUE TITLE
only these files are in zip file and all folders are empty. there is serious problem in build. no vendor.img and many other files are missing

### ISSUE THREAD

**Issue by jagtarsidhu** [LSPosed/MagiskOnWSA#234]
![Screenshot 2022-02-17 152540](https://user-images.githubusercontent.com/34836866/154451454-0dd604c3-7d1f-41c2-84a5-f59686876f8f.png)

**Comment by yujincheng08** [comment]
apprently there is vendor.img in your build

https://github.com/jagtarsidhu/MagiskOnWSA/runs/5237340066?check_suite_focus=true#step:18:62

**Comment by jagtarsidhu** [comment]
> apprently there is vendor.img in your build
> 
> https://github.com/jagtarsidhu/MagiskOnWSA/runs/5237340066?check_suite_focus=true#step:18:62

But beleive me i downloaded 7-8 times and even downloaded another forkers build too.
But after extraction all folders are empty and some files are missing and installation going failed.
Where is the problem ?
I tried 7zip,winrar and native windows extractor also.

**Comment by yujincheng08** [comment]
It maybe helpful: https://github.com/LSPosed/MagiskOnWSA/issues/139#issuecomment-997902926

**Comment by jagtarsidhu** [comment]
> It maybe helpful: https://github.com/LSPosed/MagiskOnWSA/issues/139#issuecomment-997902926

How it can be possible ?
