### ISSUE TITLE
Build WSA FAILED

### ISSUE THREAD

**Issue by baba2580** [LSPosed/MagiskOnWSA#237]
[matrix](https://github.com/baba2580/MagiskOnWSA/runs/5260776005?check_suite_focus=true)
Actions jobs for this repository have been disabled by GitHub staff. If you are the repository owner, you can contact support via https://github.com/contact for more information.

Please help for solution @yujincheng08 
![wsa](https://user-images.githubusercontent.com/23245020/154818824-d01dbf8e-1c5e-4857-a090-68f3376346c5.jpg)

**Comment by shrugalots** [comment]
Any solutions?

**Comment by shrugalots** [comment]
Error from log
Err:102 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libosmesa6 amd64 21.2.6-0ubuntu0.1~20.04.1
  Connection failed [IP: 52.250.76.244 80]
Fetched 74.6 MB in 9min 48s (127 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libosmesa6_21.2.6-0ubuntu0.1~20.04.1_amd64.deb  Connection failed [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/MagiskOnWSA/actions/runs/1870585749

seems no problem

**Comment by baba2580** [comment]
> https://github.com/LSPosed/MagiskOnWSA/actions/runs/1870585749
> 
> seems no problem

https://github.com/baba2580/MagiskOnWSA/actions/runs/1877785710
