### ISSUE TITLE
Keyboard doesn't work

### ISSUE THREAD

**Issue by LZGM4702** [LSPosed/MagiskOnWSA#238]
Everything seems to work fine except the keyboard. I can't really log in or do much without it, honestly it's probably a setting that I changed at one point.

**Comment by RyanLee0114** [comment]
?

**Comment by PeterNjeim** [comment]
This repo is not for WSA itself, but for the script that patches it. To ask for WSA support or more features, please open a request in the Feedback Hub using the Apps > Windows Subsystem for Android™️ category. My keyboard works fine, don't know what could be causing yours to fail. Potentially take a look in the Android settings > System > Languages and input. Please close this issue as it is unrelated to MagiskOnWSA.
