### ISSUE TITLE
Build WSA Failed

### ISSUE THREAD

**Issue by baba2580** [LSPosed/MagiskOnWSA#240]
https://github.com/baba2580/MagiskOnWSA/actions/runs/1877785710

please help and solve

**Comment by yujincheng08** [comment]
You are blocked by Github. It's not our issue.

**Comment by baba2580** [comment]
> You are blocked by Github. It's not our issue.

why github blocked me

**Comment by yujincheng08** [comment]
Do you think I know the reason?

**Comment by baba2580** [comment]
how can i unblock for this repo

**Comment by baba2580** [comment]
I also posted this issue in community

**Comment by baba2580** [comment]
> Do you think I know the reason?

![ws](https://user-images.githubusercontent.com/23245020/155011158-95053f92-3c5b-4b18-8635-659fd602aa86.jpg)
