### ISSUE TITLE
MagiskOnWSA cannot install due to being unable to install a .xml app

### ISSUE THREAD

**Issue by boofiboi** [LSPosed/MagiskOnWSA#242]
![image](https://user-images.githubusercontent.com/79476279/155204246-7de73710-5647-4111-bee0-ff1afd677ede.png)
It always outputs this, then closes after a few seconds. Nothing is installed/changed on my system and I cannot install the .appx packages manually.

**Comment by yujincheng08** [comment]
Manually install it by `Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml` and see the error msg.

**Comment by boofiboi** [comment]
aaah, I see what is happening now.

The partition its extracted on is BTRFS.
![image](https://user-images.githubusercontent.com/79476279/155205241-9288a15c-5ab5-46e1-9f7e-5fc3a5704467.png)


Im gonna try extracting it to  my main drive.

**Comment by yujincheng08** [comment]
OK.
