### ISSUE TITLE
some games after install doesn't work

### ISSUE THREAD

**Issue by voulx** [LSPosed/MagiskOnWSA#244]
Hi I had installed the WSA via PICO and installed game Idle Iron Knight. However, when i click open it doesn't appear anything.

**Comment by PeterNjeim** [comment]
This repo is not for WSA itself, but for the script that patches it. To ask for WSA support or more features, please open a request in the Feedback Hub using the Apps > Windows Subsystem for Android™️ category. Please close this issue as it is unrelated to MagiskOnWSA.
