### ISSUE TITLE
Error installing on second Windows user account

### ISSUE THREAD

**Issue by calebcng** [LSPosed/MagiskOnWSA#250]
![image](https://user-images.githubusercontent.com/5797919/156122057-ca33903d-ef9c-44a3-b8ca-2f4d426b424a.png)

The installation runs perfectly on the first Windows user, but when I try to install it again on another user on the same computer, I get the following error message. How can I resolve this error?

Thanks!

**Comment by yujincheng08** [comment]
No way. WSA can only be installed in one user.
