### ISSUE TITLE
SELinux权限问题

### ISSUE THREAD

**Issue by himeno-hamster** [LSPosed/MagiskOnWSA#253]
在Magisk启用Zygisk，安装完Shamiko后，在Google Play上下载公主连接（jp.co.cygames.princessconnectredive），然后把游戏添加到配置排除列表（这游戏会检测root），之后启动游戏，游戏会在启动十多秒后强退。但是在执行setenforce 0之后一切正常。希望能在不手动更改selinux状态的情况下正常运行游戏

**Comment by yujincheng08** [comment]
setenforce 0 之后启动 PCR，启动成功之后 `su -c dmesg | grep audit` 的结果发上来看看

**Comment by himeno-hamster** [comment]
[    0.078328] audit: initializing netlink subsys (disabled)
[    0.078348] audit: type=2000 audit(1646482099.020:1): state=initialized audit_enabled=0 res=1
[    0.978053] audit: type=1403 audit(1646482101.070:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
[    0.979913] audit: type=1404 audit(1646482101.070:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
[    1.107297] audit: type=1400 audit(1646482101.190:4): avc:  denied  { read } for  pid=215 comm="init" name="product_file_contexts" dev="pmem3" ino=83 scontext=u:r:vendor_init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
[    1.122074] audit: type=1400 audit(1646482101.210:5): avc:  denied  { perfmon } for  pid=209 comm="init" capability=38  scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=capability2 permissive=0
[    1.187065] logd.auditd: start
[    2.759297] audit: type=1400 audit(1646482102.850:6): avc:  denied  { getattr } for  pid=317 comm="ls" path="/data/adb" dev="sda" ino=2867201 scontext=u:r:toolbox:s0 tcontext=u:object_r:adb_data_file:s0 tclass=dir permissive=0
[    2.902163] audit: type=1403 audit(1646482102.990:7): auid=4294967295 ses=4294967295 lsm=selinux res=1
[    3.649486] audit: type=1400 audit(1646482103.740:8): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup2" dev="sysfs" ino=18870 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[    3.650921] audit: type=1400 audit(1646482103.740:9): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup0" dev="sysfs" ino=13011 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[    3.652117] audit: type=1400 audit(1646482103.740:10): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup3" dev="sysfs" ino=18930 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[    5.216832] init: starting service 'logd-auditctl'...
[    5.260977] init: Service 'logd-auditctl' (pid 650) exited with status 0 oneshot service took 0.043000 seconds in background
[    5.260982] init: Sending signal 9 to service 'logd-auditctl' (pid 650) process group...
[    5.862906] kauditd_printk_skb: 13 callbacks suppressed
[    5.862907] audit: type=1400 audit(1646482105.950:24): avc:  denied  { write } for  pid=1384 comm="setprop" name="property_service" dev="tmpfs" ino=181 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
[    6.407417] audit: type=1400 audit(1646482106.490:25): avc:  denied  { setopt } for  pid=1556 comm="Binder:1309_4" scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:r:gmscore_app:s0:c512,c768 tclass=vsock_socket permissive=0
[    9.593727] audit: type=1400 audit(1646482109.680:26): avc:  denied  { getattr } for  pid=1556 comm="Binder:1309_4" name="/" dev="virtiofs" ino=1 scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:object_r:system_server_tmpfs:s0 tclass=filesystem permissive=0
[    9.602878] audit: type=1400 audit(1646482109.690:27): avc:  denied  { write } for  pid=3294 comm="setprop" name="property_service" dev="tmpfs" ino=181 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
[    9.679289] audit: type=1400 audit(1646482109.770:28): avc:  denied  { setopt } for  pid=1556 comm="Binder:1309_3" scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:r:gmscore_app:s0:c512,c768 tclass=vsock_socket permissive=0
[   11.430971] audit: type=1400 audit(1646482111.520:29): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup2" dev="sysfs" ino=18870 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[   11.432836] audit: type=1400 audit(1646482111.520:30): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup0" dev="sysfs" ino=13011 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[   11.434879] audit: type=1400 audit(1646482111.520:31): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup3" dev="sysfs" ino=18930 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[   11.436485] audit: type=1400 audit(1646482111.520:32): avc:  denied  { read } for  pid=270 comm="Binder:43_2" name="wakeup1" dev="sysfs" ino=13299 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[   12.471557] audit: type=1400 audit(1646482112.560:33): avc:  denied  { setopt } for  pid=1556 comm="IntentService[D" scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:r:gmscore_app:s0:c512,c768 tclass=vsock_socket permissive=0
[   12.606130] audit: type=1400 audit(1646482112.690:34): avc:  denied  { getattr } for  pid=1556 comm="IntentService[D" name="/" dev="virtiofs" ino=1 scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:object_r:system_server_tmpfs:s0 tclass=filesystem permissive=0
[   13.151177] audit: type=1400 audit(1646482113.240:35): avc:  denied  { getattr } for  pid=1556 comm="Binder:1309_4" name="/" dev="virtiofs" ino=1 scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:object_r:system_server_tmpfs:s0 tclass=filesystem permissive=0
[   14.843738] audit: type=1400 audit(1646482114.930:36): avc:  denied  { ioctl } for  pid=4710 comm="su" path="/dev/pts/0" dev="devpts" ino=3 ioctlcmd=0x5404 scontext=u:r:magisk_client:s0 tcontext=u:object_r:devpts:s0 tclass=chr_file permissive=0
[   26.859470] audit: type=1404 audit(1646482126.950:37): enforcing=0 old_enforcing=1 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
[   35.307666] audit: type=1400 audit(1646482135.390:38): avc:  denied  { read } for  pid=4844 comm="UnityMain" name="interrupts" dev="proc" ino=4026532029 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_interrupts:s0 tclass=file permissive=1
[   35.310216] audit: type=1400 audit(1646482135.390:39): avc:  denied  { open } for  pid=4844 comm="UnityMain" path="/proc/interrupts" dev="proc" ino=4026532029 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_interrupts:s0 tclass=file permissive=1
[   35.311338] audit: type=1400 audit(1646482135.390:40): avc:  denied  { getattr } for  pid=4844 comm="UnityMain" path="/proc/interrupts" dev="proc" ino=4026532029 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_interrupts:s0 tclass=file permissive=1
[   35.373805] audit: type=1400 audit(1646482135.460:41): avc:  denied  { getattr } for  pid=4844 comm="UnityMain" path="/proc/filesystems" dev="proc" ino=4026532077 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_filesystems:s0 tclass=file permissive=1
[   35.376539] audit: type=1400 audit(1646482135.460:42): avc:  denied  { read } for  pid=4844 comm="UnityMain" name="filesystems" dev="proc" ino=4026532077 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_filesystems:s0 tclass=file permissive=1
[   35.378284] audit: type=1400 audit(1646482135.460:43): avc:  denied  { open } for  pid=4844 comm="UnityMain" path="/proc/filesystems" dev="proc" ino=4026532077 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_filesystems:s0 tclass=file permissive=1
[   37.624985] audit: type=1400 audit(1646482137.710:44): avc:  granted  { execute } for  pid=4940 comm="nectredive:tab1" name="a.bin" dev="sda" ino=1138916 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c256,c512,c768 tclass=file
[   37.627706] audit: type=1400 audit(1646482137.710:45): avc:  granted  { execute } for  pid=4940 comm="a.bin" path="/data/data/jp.co.cygames.princessconnectredive/app_1b40/a.bin" dev="sda" ino=1138916 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c256,c512,c768 tclass=file
[   37.630666] audit: type=1400 audit(1646482137.720:46): avc:  granted  { execute } for  pid=4940 comm="a.bin" path="/data/data/jp.co.cygames.princessconnectredive/app_1b40/liba.so" dev="sda" ino=1138917 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c57,c256,c512,c768 tclass=file
[   43.774692] audit: type=1400 audit(1646482143.860:47): avc:  denied  { read } for  pid=4844 comm="Thread-42" name="drivers" dev="proc" ino=4026531852 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=1
[   43.776111] audit: type=1400 audit(1646482143.860:48): avc:  denied  { open } for  pid=4844 comm="Thread-42" path="/proc/tty/drivers" dev="proc" ino=4026531852 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=1
[   43.778102] audit: type=1400 audit(1646482143.860:49): avc:  denied  { getattr } for  pid=4844 comm="Thread-42" path="/proc/tty/drivers" dev="proc" ino=4026531852 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=1
[   43.779343] audit: type=1400 audit(1646482143.860:50): avc:  denied  { read } for  pid=4844 comm="Thread-42" name="u:object_r:serialno_prop:s0" dev="tmpfs" ino=144 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=1
[   43.780625] audit: type=1400 audit(1646482143.860:51): avc:  denied  { open } for  pid=4844 comm="Thread-42" path="/dev/__properties__/u:object_r:serialno_prop:s0" dev="tmpfs" ino=144 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=1
[   43.781933] audit: type=1400 audit(1646482143.860:52): avc:  denied  { getattr } for  pid=4844 comm="Thread-42" path="/dev/__properties__/u:object_r:serialno_prop:s0" dev="tmpfs" ino=144 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=1
[   43.783218] audit: type=1400 audit(1646482143.860:53): avc:  denied  { map } for  pid=4844 comm="Thread-42" path="/dev/__properties__/u:object_r:serialno_prop:s0" dev="tmpfs" ino=144 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=1

**Comment by yujincheng08** [comment]
看不出来哪些权限是 WSA 专属的。。。

你可以手动测试 `setenforce 1` 之后哪些权限 allow 之后可以用：
对上面 `scontext=u:r:untrusted_app:s0:c57,c256,c512,c768` 的日志逐条测试：
`su -c magiskpolicy --live "allow "untrusted_app {tcontext} {tclass} {perm}"`

比如，针对
```
[ 35.310216] audit: type=1400 audit(1646482135.390:39): avc: denied { open } for pid=4844 comm="UnityMain" path="/proc/interrupts" dev="proc" ino=4026532029 scontext=u:r:untrusted_app:s0:c57,c256,c512,c768 tcontext=u:object_r:proc_interrupts:s0 tclass=file permissive=1
```
`su -c magiskpolicy --live "allow "untrusted_app proc_interrupts file open"`

**Comment by himeno-hamster** [comment]
把所有的项都加了进去，游戏启动的时候没有新的denied了，但还是会闪退

**Comment by yujincheng08** [comment]
看起来可能是 noaudit 的规则

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/LSPosed/MagiskOnWSA/files/8192071/app-debug.zip)
集成这个 magisk 再看看 dmesg。这个 magisk 清掉了 dontaudit 规则。

**Comment by himeno-hamster** [comment]
magiskpolicy --live "allow untrusted_app app_data_file file execute_no_trans"
只执行这条就能用了

**Comment by yujincheng08** [comment]
# Block calling execve() on files in an apps home directory.
# This is a W^X violation (loading executable code from a writable
# home directory). For compatibility, allow for targetApi <= 28.
# b/112357170
neverallow {
  all_untrusted_apps
  -untrusted_app_25
  -untrusted_app_27
  -runas_app
} { app_data_file privapp_data_file }:file execute_no_trans;

这是 neverallow 所以不能加。
