### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSA#254]
![屏幕截图(7)](https://user-images.githubusercontent.com/88972478/156913848-085ac24a-aca9-44a4-9e5c-0e2b9aaa9c0f.png)

文件：https://github.com/Doddddd/MagiskOnWSA/actions/runs/1937547051
原版可以正常安装

**Comment by yujincheng08** [comment]
Duplicate of #107 #125 #38
