### ISSUE TITLE
Couldn't sign in google services

### ISSUE THREAD

**Issue by BGGR101** [LSPosed/MagiskOnWSA#255]
When I open play store and click sign in, after loading it says that there is a problem with google servers.
Is there anything I can do?
screenshot: [https://imgur.com/jPCVmuA](url)

**Comment by BGGR101** [comment]
bitdefender was blocking the connection.

**Comment by erwae** [comment]
> 

I encountered that too,Did you fix it?please tell me how,thank u!

**Comment by BGGR101** [comment]
> 

My antivirus (Bitdefender) was blocking the connection for some reason.
