### ISSUE TITLE
Not working keep on getting 

### ISSUE THREAD

**Issue by andythegreat87** [LSPosed/MagiskOnWSA#258]
I keep on getting this: 

The operation completed successfully.
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32837.0_x64__8wekyb3d8bbwe
because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.6"
published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64
processor architecture and minimum version 2.62108.18004.0, along with this package to install. The frameworks with
name "Microsoft.UI.Xaml.2.6" currently installed are
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32837.0_x64__8wekyb3d8bbwe
because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.6"
published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64
processor architecture and minimum version 2.62108.18004.0, along with this package to install. The frameworks with
name "Microsoft.UI.Xaml.2.6" currently installed are: {}
NOTE: For additional information, look for [ActivityId] 23de2296-31a1-0005-5997-de23a131d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 23de2296-31a1-0005-5997-de23a131d801
At D:\WSA-with-magisk-GApps-pico_1.8.32837.0_x64_Release-Nightly\Install.ps1:20 char:1
+ Add-AppxPackage -Register .\AppxManifest.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\WSA-with-mag...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Everything is enable that is needed

**Comment by Fredwuz** [comment]
go to https://store.rg-adguard.net/ and input `9P3395VX91NR` and select `ProductId` and `Slow` then download all the 
yyy<YourSystem>xxx.appx packages expect the last one that's 1.21GB and try to install them manually with `add-appxpackage -path "<pathtothepackage>"`
or if you have Modern Flyouts close it and try again for me it blocked the installation

**Comment by andythegreat87** [comment]
> go to https://store.rg-adguard.net/ and input `9P3395VX91NR` and select `ProductId` and `Slow` then download all the yyyxxx.appx packages expect the last one that's 1.21GB and try to install them manually with `add-appxpackage -path "<pathtothepackage>"` or if you have Modern Flyouts close it and try again for me it blocked the installation

It  works, thanks :)
