### ISSUE TITLE
WSA just stops launching eventually

### ISSUE THREAD

**Issue by khaledmoayad** [LSPosed/MagiskOnWSA#260]
Randomly (usually around a day or 2 from installation), WSA just decides to stop launching and I have to reinstall, this is the only fix i have found. WSA just says starting WSA and then just closes without any error messages and refuses to launch again. pls help

**Comment by yujincheng08** [comment]
Need log.

**Comment by khaledmoayad** [comment]
umm how do i get that

**Comment by yujincheng08** [comment]
read readme and u will know.

**Comment by khaledmoayad** [comment]
where is the readme?

**Comment by vadinoguerrero** [comment]
I had the same issue before uninstalling completely, I don't have a logcat (because I already uninstalled) but this is an issue that should be given more attention, after a couple of days apps don't open, and I can't even open the WSA settings

**Comment by khaledmoayad** [comment]
I don't even know where to find the logs.

**Comment by vadinoguerrero** [comment]
> 
Win + R and paste this:
%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat

**Comment by khaledmoayad** [comment]
ok so it started happening again, heres the log 
[21032022105055.log](https://github.com/LSPosed/MagiskOnWSA/files/8314108/21032022105055.log)

**Comment by yujincheng08** [comment]
```
03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at android.content.pm.PackageParserCacheHelper$ReadHelper.startAndInstall(PackageParserCacheHelper.java:62)

03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at com.android.server.pm.parsing.PackageCacher.fromCacheEntryStatic(PackageCacher.java:80)

03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at com.android.server.pm.parsing.PackageCacher.fromCacheEntry(PackageCacher.java:69)

03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at com.android.server.pm.parsing.PackageCacher.getCachedResult(PackageCacher.java:160)

03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:144)

03-21 10:51:04.724   181   287 F system_server: runtime.cc:655]   at com.android.server.pm.ParallelPackageParser.parsePackage(ParallelPackageParser.java:129)
```

PM is crashed with the above stack. Seems like a package cache is corrupted in your system. I think you should report it to Microsoft or opengapps.  If you can access data somehow, you can try to remove `/data/system/package_cache`.

**Comment by khaledmoayad** [comment]
this happens all the time i also think that wsa corrupts windows

**Comment by khaledmoayad** [comment]
plus if reinstalling wsa fixes it, i dont thing its a windows issue

**Comment by yujincheng08** [comment]
I never said it was windows' issue...
