### ISSUE TITLE
building fault

### ISSUE THREAD

**Issue by s793016** [LSPosed/MagiskOnWSA#267]
![圖片](https://user-images.githubusercontent.com/17686555/159097204-37bc78b4-c879-40a9-b4e7-5bf0464487d6.png)

**Comment by yujincheng08** [comment]
Use stable/beta magisk. magiskpolicy is now not a static build and causes the problem.

**Comment by s793016** [comment]
I used this and everything is ok now.
https://github.com/vvb2060/magisk_files/raw/alpha/app-release.apk

**Comment by yujincheng08** [comment]
Fixed. Now properly support 24302+ Magisk canary.
