### ISSUE TITLE
Workflow run failure

### ISSUE THREAD

**Issue by AxMan251005** [LSPosed/MagiskOnWSA#269]
I selected aroma variant and none as root solution for the workflow, but it is constantly failing. I checked the error and it was as follows :
Traceback (most recent call last):
  File "/home/runner/work/_temp/cf35e070-a6ce-4c1a-bd9b-4ab460c0b245.py", line 15, in <module>
    link = {i["name"]: i for i in j["archs"][abi_map[arch]]["apis"]["11.0"]["variants"]}[variant]["zip"]
KeyError: 'aroma'
Error: Process completed with exit code 1.

**Comment by yujincheng08** [comment]
If you have read readme, you will find:
> Support all OpenGApps variants except for aroma (aroma does not support x86_64, please use super instead)

**Comment by AxMan251005** [comment]
Well I tried super but it fails there as well. Error is something like : 

chown: cannot dereference 'system/system/priv-app/BuiltInPrintService/lib/x86_64/libwfds.so': No such file or directory
chown: cannot dereference 'system/system/priv-app/BuiltInPrintService/lib/x86_64/libcups.so': No such file or directory
chown: cannot dereference 'system/product/app/Camera2/lib/x86_64/libjni_jpegutil.so': No such file or directory
chown: cannot dereference 'system/product/app/Camera2/lib/x86_64/libjni_tinyplanet.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_eglfence.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_filtershow_filters.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_jpegstream.so': No such file or directory
Error: Process completed with exit code 1.

I even went all the way down to pico and got this error :

chown: cannot dereference 'system/system/app/PrintSpooler/lib/x86_64/libprintspooler_jni.so': No such file or directory
chown: cannot dereference 'system/system/priv-app/BuiltInPrintService/lib/x86_64/libwfds.so': No such file or directory
chown: cannot dereference 'system/system/priv-app/BuiltInPrintService/lib/x86_64/libcups.so': No such file or directory
chown: cannot dereference 'system/product/app/Camera2/lib/x86_64/libjni_jpegutil.so': No such file or directory
chown: cannot dereference 'system/product/app/Camera2/lib/x86_64/libjni_tinyplanet.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_eglfence.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_filtershow_filters.so': No such file or directory
chown: cannot dereference 'system/product/app/Gallery2/lib/x86_64/libjni_jpegstream.so': No such file or directory
Error: Process completed with exit code 1.

Seems like there is some error in the code for integration of GApps or something.

**Comment by yujincheng08** [comment]
Because you did not update the script. If you have read readme, you should know how to upgrade the script.

Why can't you read readme? Is it hard to read?

**Comment by AxMan251005** [comment]
Oh, sorry, I hadn't noticed that part.

Anyways, thanks!
