### ISSUE TITLE
Builds won't start

### ISSUE THREAD

**Issue by Pyrus01** [LSPosed/MagiskOnWSA#271]
![image](https://user-images.githubusercontent.com/25166655/159747119-06111e59-755c-4e2d-a648-721f74ffb342.png)
I tried waiting for a while, selecting different Magisk branches, no magisk at all, different Gapps packages, x64 and arm + x64, but the builds won't start. 

https://github.com/Pyrus01/MagiskOnWSA

**Comment by Pyrus01** [comment]
![image](https://user-images.githubusercontent.com/25166655/159747493-8988553a-a584-4052-a6fe-92f729230f60.png)
I get the message uptop, but even after refreshing for 10 minutes, no build starts.

**Comment by JasonKhew96** [comment]
https://githubstatus.com
