### ISSUE TITLE
RFC: Use Magisk's own build.yml inside the main build

### ISSUE THREAD

**Issue by pasqualirb** [LSPosed/MagiskOnWSA#28]
I took a brief look at the [Magisk's build.yml](https://github.com/LSPosed/MagiskOnWSA/blob/magisk/.github/workflows/build.yml) from the branch `magisk`, and I though about the possibility of integrating it to [this repo's magisk.yml](https://github.com/LSPosed/MagiskOnWSA/blob/main/.github/workflows/magisk.yml).

I've never used GitHub Actions, so I would have to do some prior research in order to try implementing this proposal. Does anyone knows whether this is straightforwardly achievable?

**Comment by yujincheng08** [comment]
Building Magisk is time-consuming. Is there any reason to build it on the fly?

**Comment by pasqualirb** [comment]
> Building Magisk is time-consuming. Is there any reason to build it on the fly?

As I understand, it would make the build of the custom Magisk.apk reproducible and trusted by GitHub Actions system.

**Comment by pasqualirb** [comment]
One alternative is to build magisk branch using GitHub Actions and fetch the Magisk.apk from the result of the build.

**Comment by yujincheng08** [comment]
That's why there's a place for u to input download link to Magisk apk. For most user, building Magisk is not that important.

**Comment by pasqualirb** [comment]
Just for the record, commit 0837b70d434b4042713137022bfd758f0dafdfe7 by @yujincheng08 introduced the first functional build with a package from [Magisk reposotory](https://github.com/topjohnwu/Magisk).
