### ISSUE TITLE
Integrate Majisk failed

### ISSUE THREAD

**Issue by RickyAsbury** [LSPosed/MagiskOnWSA#292]
can I get an explanation on this?
sorry I just don't know how to explain my issue but here's the image down below
![image](https://user-images.githubusercontent.com/75904443/161561314-ffca5c59-9b6d-4c69-b4f8-10a3b1059562.png)

**Comment by yujincheng08** [comment]
Update the script...

**Comment by RickyAsbury** [comment]
> Update the script...

how do I do that? still kinda new to github
