### ISSUE TITLE
Update/Installation Failure

### ISSUE THREAD

**Issue by allanrps** [LSPosed/MagiskOnWSA#294]
After a Windows update, I was experiences bugs with MagiskOnWSA 1.8.3 which interaction with the system tray, causing my system to freeze and kill WSA. Due to this, i attempted to upgrade to MagiskOnWSA 2203.4, but the install script failed and corrupted my WSA install, causing it to give an error about a missing file path whenever an app start was attempted. Uninstalled WSA and attempted to install both versions of WSA but both failed, giving error. This is when running manually from powerscript admin, when trying to run from file explorer the script immediately closes. I know the docs say that means my computer is incompatable, but I was just using WSA before, and i hope this could be fixed, or I hope its just an issue with my system that I can address. Thank you for the help!

```
Stop-Process : Cannot find a process with the name "wsaclient". Verify the process name and call the cmdlet again.
At D:\AndroidUtils\WSA-with-magisk-GApps-micro_2203.40000.1.0_x64_Release-Nightly\Install.ps1:68 char:1                 + Stop-Process -Name "wsaclient"                                                                                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                            + CategoryInfo          : ObjectNotFound: (wsaclient:String) [Stop-Process], ProcessCommandException                    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.
error 0x80070003: While preparing to process the request, the system failed to register the windows.comInterface
extension due to the following error: The system cannot find the path specified.
.
NOTE: For additional information, look for [ActivityId] 213042d5-4c06-0004-a0a5-4021064cd801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 213042d5-4c06-0004-a0a5-4021064cd801
At D:\AndroidUtils\WSA-with-magisk-GApps-micro_2203.40000.1.0_x64_Release-Nightly\Install.ps1:69 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\AndroidUtils...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by allanrps** [comment]
Sorry the Windows update which broke my install is KB5013284

**Comment by yujincheng08** [comment]
your script is out if date. try to update the script

**Comment by allanrps** [comment]
yes you are right! sorry I messed that up. unfortunately I just can not get the artifact archive to download properly, I have gotten an error from the script saying it is corrupted, and I have gotten errors trying to extract the archive. Maybe once I have a more stable connection things will be better....

**Comment by yujincheng08** [comment]
Maybe you are using some multithread downloaders. Try to use the one from the browser.

**Comment by allanrps** [comment]
I am using edge browser, no fancy downloaders here. Also, the typical download progress bar never loads, it just cycles and shows the download speed and file size.
