### ISSUE TITLE
Script no longer compiling the build

### ISSUE THREAD

**Issue by lirexxx** [LSPosed/MagiskOnWSA#296]
Please see the attached screenshots from 5 minutes ago. It happens every time:

![image](https://user-images.githubusercontent.com/94787562/162623673-24427e2b-58ba-4e0d-9093-58afeab2354b.png)

![image](https://user-images.githubusercontent.com/94787562/162623761-17e75ded-ce78-42e2-a64e-903a170e51ce.png)

**Comment by yujincheng08** [comment]
then why not update the script?

**Comment by lirexxx** [comment]
Because I have no idea how. I have no coding skills, that's why I use the pre-configured script.

**Comment by yujincheng08** [comment]
read README then
