### ISSUE TITLE
magisk 修复运行环境问题

### ISSUE THREAD

**Issue by yuanjie000** [LSPosed/MagiskOnWSA#297]
[使用的wsa版本](https://github.com/LSPosed/MagiskOnWSA/actions/runs/2141281964)
安装后运行magisk提示要修复运行环境，修补boot镜像，直接安装失败。在magisk里面启用zygisk也显示无效。安装lsp提示magisk未安装
如何修复？
![}@8I{81UQ 9` )ARON3ZKQV](https://user-images.githubusercontent.com/20902900/162921750-b0ed4aec-6e3c-4200-9e17-6e6ab563491c.png)

![907M`8748JL3WC QKS N)EI](https://user-images.githubusercontent.com/20902900/162921913-c1be4a6b-4fa9-4b5a-a293-f30e17586ed4.png)

![V89O}CJ5FS 5N` (VRK@W{8](https://user-images.githubusercontent.com/20902900/162922553-e57a64f8-5147-49e9-b4d5-6075c5945814.png)

**Comment by yujincheng08** [comment]
fixed by 74e041bc0fb21ec9284ec7729ca74815a84604b1
