### ISSUE TITLE
Install.ps autocloses on Newest Beta Channel

### ISSUE THREAD

**Issue by vincetan7890** [LSPosed/MagiskOnWSA#298]
Insider preview 22593.1 autocloses and doesnt let Install.ps run

**Comment by yujincheng08** [comment]
what err it shows?

**Comment by vincetan7890** [comment]
> 

 Autocloses before error can appear.

**Comment by yujincheng08** [comment]
try manually install

**Comment by vincetan7890** [comment]
> try manually install

ok thanks

**Comment by vincetan7890** [comment]
> try manually install

Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Bypass -Force;

this method worked

**Comment by yujincheng08** [comment]
Ok I will add this to install.ps1

**Comment by vincetan7890** [comment]
> Ok I will add this to install.ps1

thanks
