### ISSUE TITLE
Add install powershell or batch script to the final zip.

### ISSUE THREAD

**Issue by okibcn** [LSPosed/MagiskOnWSA#30]
This is just a suggestion to make it easier for even more people. Add a Powershell script file with the name INSTALL.PS1 with the code to install it. This is a suggestion for the content of the powershell script file:

```powershell
function Test-Administrator  
{  
    [OutputType([bool])]
    param()
    process {
        [Security.Principal.WindowsPrincipal]$user = [Security.Principal.WindowsIdentity]::GetCurrent();
        return $user.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator);
    }
}

if(-not (Test-Administrator))
{
    Write-Error "This script must be executed as Administrator.";
    exit 1
}

$ErrorActionPreference = "Stop";
Add-AppxPackage -Register ./AppxManifest.xml
```

**Comment by rakion99** [comment]
but just opening powershell and typing Add-AppxPackage -Register ./AppxManifest.xml is very easy, if they can't do that then they should not do it since they need to use adb too

**Comment by okibcn** [comment]
Well, this script tries to automate something you can also do manually. Why not automate the last step too?
