### ISSUE TITLE
Integration of custom apk in /system/priv-app

### ISSUE THREAD

**Issue by nabsboss** [LSPosed/MagiskOnWSA#304]
hi,

First thank you very much for your great work !!!

I use microG instead of gapps but the only issue is that we can't install the NetworkLocation.apk normally.
The workaround from xda https://forum.xda-developers.com/t/app-unifiednlp-floss-wi-fi-and-cell-tower-based-geolocation.2991544/ " is: If your system is not AOSP-based but GAPPS-free and the above instructions do not work for you, try placing NetworkLocation.apk directly in /system/priv-app/ and reboot.

Can you add an option for that in the workflow or integrate microG instead of Gapps please in the options.
I ask because it seem that it is impossible to push to /system/priv-app/, i tried everything and it is only read access only :(

Thanks

**Comment by zhongfly** [comment]
https://github.com/LSPosed/MagiskOnWSA/issues/232

**Comment by vvb2060** [comment]
Push to your own repository, not ours
