### ISSUE TITLE
Can not log into Google Account 

### ISSUE THREAD

**Issue by SageOfD6Path** [LSPosed/MagiskOnWSA#305]
Whenever I try to sign in to Google Play , it says "Couldn't sign in. There was a problem communicating with Google servers. 
Even the browser fails to load any page, it's like WSA doesn't have internet connection.

**Comment by Howard20181** [comment]
Please check the network connection
Check whether the network proxy is enabled, if so, disable it and try again

**Comment by erwae** [comment]
I also encountered the same problem. When I opened the Google Store, I was stuck on the "checking information" page. After a while, it showed that I couldn't log in. Please find a solution!

**Comment by yujincheng08** [comment]
Please check the network connection of WSA.

**Comment by SageOfD6Path** [comment]
Nah, Network connection and all is just fine. I found that the issue persists with nano builds. I installed pico build and everything works like a charm now.
