### ISSUE TITLE
Install Failure after Windows Update

### ISSUE THREAD

**Issue by allanrps** [LSPosed/MagiskOnWSA#307]
After a windows update, I am no longer able to install WSA. I was experiencing bugs, and tried to update, but the install corrupted my WSA and I was receiving a file not found error. Now when attempting to install the latest version of MagiskonWSA, the install script closes after less than a min when invoked from powershell as described.

**Comment by Howard20181** [comment]
#298

**Comment by allanrps** [comment]
this solution offered in #298 did not solve my issue, and also i am not on the beta channel but the retail channel

**Comment by Howard20181** [comment]
> this solution offered in #298 did not solve my issue, and also i am not on the beta channel but the retail channel

Need more information
What is your Windows version number?
Try to install it manually (manually run the command inside install.ps1 with administrator privileges)

**Comment by allanrps** [comment]
I am running Windows 11 Home Version 22H2 build 22593.1. I have actually installed WSA from the microsoft store and that is working. Unfortunately, I currently rely on WSA for communication through whatsapp, so i am not able to uninstall and test.
