### ISSUE TITLE
Corruption of the userdata.vhdx filesystem

### ISSUE THREAD

**Issue by OlyAndy** [LSPosed/MagiskOnWSA#308]
The filesystem often ends up corrupted. If I mount it through the Hyper-V/Windows Subsystem for Linux, I can fsck the system and it stays fixed for a while. I suspect the WSA service is stopping before the system properly syncs and unmounts the filesystem.

**Comment by Jlc1977** [comment]
This is what it's doing

**Comment by yujincheng08** [comment]
unfortunately this problem is from the original WSA and you should report to Microsoft directly.
