### ISSUE TITLE
Run Workflow has changed

### ISSUE THREAD

**Issue by Almighty188** [LSPosed/MagiskOnWSA#309]
![image](https://user-images.githubusercontent.com/78993393/163733348-794ea13a-af40-43b9-a236-0233c4772144.png)

It seems like the Run Workflow menu has changed, the instructions does not seem to cover this.

so the guide needs updating:

There are two items of interest:

![image](https://user-images.githubusercontent.com/78993393/163733393-82f7414a-4cf4-4962-afaa-6f0b2a4c650a.png)
Which version would each one install and which should one choose?

![image](https://user-images.githubusercontent.com/78993393/163733421-672c8dea-3475-4244-a30a-afd0d213804f.png)
Which version of Magiisk is each one?  Like which one is newer and are they all Magisk 24 minimum?

In your older instructions, there was a way to use Magisk Alpha so the hide works, is that still possible?  

There also does not seem to be a way to specify the link for Magisk.

**Comment by vkonvict** [comment]
> ![image](https://user-images.githubusercontent.com/78993393/163733348-794ea13a-af40-43b9-a236-0233c4772144.png)
> 
> It seems like the Run Workflow menu has changed, the instructions does not seem to cover this.
> 
> so the guide needs updating:
> 
> There are two items of interest:
> 
> ![image](https://user-images.githubusercontent.com/78993393/163733393-82f7414a-4cf4-4962-afaa-6f0b2a4c650a.png) Which version would each one install and which should one choose?
> 
> ![image](https://user-images.githubusercontent.com/78993393/163733421-672c8dea-3475-4244-a30a-afd0d213804f.png) Which version of Magiisk is each one? Like which one is newer and are they all Magisk 24 minimum?
> 
> In your older instructions, there was a way to use Magisk Alpha so the hide works, is that still possible?
> 
> There also does not seem to be a way to specify the link for Magisk.

i dont even see the run workflow button anymore
