### ISSUE TITLE
wsa not compleated download

### ISSUE THREAD

**Issue by mohammad1342** [LSPosed/MagiskOnWSA#311]
0s
Run import requests
Traceback (most recent call last):
  File "/home/runner/work/_temp/dcff7e6c-8fb5-4598-8eeb-aabd32ced620.py", line [1](https://github.com/LSPosed/MagiskOnWSA/runs/5691555028?check_suite_focus=true#step:3:1)6, in <module>
    link = a["href"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by bolshoytoster** [comment]
@mohammad1342 it looks like the error comes from github workflow:
https://github.com/LSPosed/MagiskOnWSA/blob/63609f1b32be37a98947df640058d66748ebc0ac/.github/workflows/magisk.yml#L122-L124

When `html.find` returns `None`.

My guess is that it's either a temporary error or there's something wrong with the workflow.

I've not really worked with workflows before, but it looks like the arch is defined here:
https://github.com/LSPosed/MagiskOnWSA/blob/63609f1b32be37a98947df640058d66748ebc0ac/.github/workflows/magisk.yml#L76-L87

As an array, then it's used as a string later:
https://github.com/LSPosed/MagiskOnWSA/blob/63609f1b32be37a98947df640058d66748ebc0ac/.github/workflows/magisk.yml#L112-L114

Again, I'm not sure about workflows but I think if possible it should be changed to take the first element of the array or initialize it to a string.

---

If possible could you try choosing `x64` or `arm64`, not both for the workflow.

**Comment by yujincheng08** [comment]
https://github.com/mohammad1342/MagiskOnWSA/actions/runs/2186444343
