### ISSUE TITLE
Could not download.

### ISSUE THREAD

**Issue by mo-absi** [LSPosed/MagiskOnWSA#318]
My internet is unstable and very slow. I couldn't download the file.
I already have the stock (Msixbundle) for WSA and a working WSL.
How can I do it offline using the files I already have?
I would appreciate it if you could help me guys.
I followed this tutorial "https://github.com/ADeltaX/WSAGAScript" and got everything working fine, but I do not know how to give root premisions to apps or integrate magisk.
I would appreciate it if you could help me guys.

**Comment by vvb2060** [comment]
You can use self-hosted runners to run this project in your own device.
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners
