### ISSUE TITLE
Any chance something can be done to "enable" the device admin feature?

### ISSUE THREAD

**Issue by felipecrs** [LSPosed/MagiskOnWSA#320]
For some reason, it seems to be disabled/hidden. More details:

- https://forum.xda-developers.com/t/windows-subsystem-for-android-hidden-settings-device-administrator-access.4399723/
- https://forum.xda-developers.com/t/windows-11-android-subsystem-microsoft-intune-passthrough-question.4351605/

**Comment by pagalmp40kk** [comment]
l

**Comment by jksdjnmyiuy** [comment]
pl enable the hidden setting device
