### ISSUE TITLE
Failed to download WSA

### ISSUE THREAD

**Issue by lsy223622** [LSPosed/MagiskOnWSA#324]
The workflow stopped in the step _Download WSA_. Tried all the WSA release types, but none of them worked.

### Console Log

Traceback (most recent call last):
  File "/home/runner/work/_temp/9e3d8f54-260f-47cf-a450-c1500e878d75.py", line 12, in <module>
    res = requests.post("https://store.rg-adguard.net/api/GetFiles", f"type=CategoryId&url=858014f3-3934-4abe-8078-4aa193e74ca8&ring={release_type}&lang=en-US", headers={
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Error: Process completed with exit code 1.

**Comment by Radiquum** [comment]
literally had this myself right now
try to add "verify=False" to .github/workflows/magisk.yml, so it will look something like that:
![image](https://user-images.githubusercontent.com/68120017/166158055-5428b37e-c171-45ff-9691-8891e0b4144a.png)

I know it'll probably make less secure connection, but it at least it's fast and working "fix"

**Comment by thesuperbob49** [comment]
> literally had this myself right now try to add "verify=False" to .github/workflows/magisk.yml, so it will look something like that: ![image](https://user-images.githubusercontent.com/68120017/166158055-5428b37e-c171-45ff-9691-8891e0b4144a.png)
> 
> I know it'll probably make less secure connection, but at least it's fast and working "fix"

I changed it from verify=false to verify=0 and that worked for me without problems.

**Comment by lsy223622** [comment]
> literally had this myself right now try to add "verify=False" to .github/workflows/magisk.yml, so it will look something like that: ![image](https://user-images.githubusercontent.com/68120017/166158055-5428b37e-c171-45ff-9691-8891e0b4144a.png)
> 
> I know it'll probably make less secure connection, but at least it's fast and working "fix"

Thank you for the temporary fix. It works perfectly, at least when connection safety is not a concern.
![Snipaste_2022-05-02_10-21-01](https://user-images.githubusercontent.com/57913213/166177155-bb2dd988-2095-418b-b1a9-5b270ce86882.png)
