### ISSUE TITLE
fetch and merged action script - build failed 

### ISSUE THREAD

**Issue by james28909** [LSPosed/MagiskOnWSA#325]
i used fetch and merge to update the actions script from upstream and the build is failing again. good thing there are a few old runs that were made a few weeks ago.

**Comment by yujincheng08** [comment]
you modified the script and made it fail
.

**Comment by james28909** [comment]
> you modified the script and made it fail .

you mean that little edit made it fail? the reason i did it was others were saying it worked for them. i also am not a github pro yet either lol. so i will delete that edit and try again. sorry and thanks
