### ISSUE TITLE
Install.ps1 执行在某个位置后卡住

### ISSUE THREAD

**Issue by zozero** [LSPosed/MagiskOnWSA#326]
Install.ps1 执行在某个位置后卡住，然后powershell就自动关闭了
![image](https://user-images.githubusercontent.com/40239741/166857705-2c5b3921-3bfc-4960-bf45-ddb6d67b2be6.png)
如果是直接右键执行Install.ps1窗口会一闪而逝

我的系统曾经安装过子系统，已经卸载。

我构建了许多WSA的版本依旧如此，电脑系统版本是win11 22610.1 ni_release；beta渠道

**Comment by atvking** [comment]
I am having the same issue, but this was my first attempt at installing any version of WSA. Using Powershell directly just flashes open and closed. Navigating to the directory using an admin terminal and running the command outlined in the instructions produces the same window posted by @zozero which then closes after about 20 seconds.

Running Windows 11 22H2 build 22610.1 (beta channel)

**Comment by zozero** [comment]
> I am having the same issue, but this was my first attempt at installing any version of WSA. Using Powershell directly just flashes open and closed. Navigating to the directory using an admin terminal and running the command outlined in the instructions produces the same window posted by @zozero which then closes after about 20 seconds.
> 
> Running Windows 11 22H2 build 22610.1 (beta channel)
> 
> ** Edit ** After updating to Windows 11 22H2 build 22616.1 (beta channel) it seems to install fine using the same build MagiskOnWSA build I tried yesterday.

thanks!
非常感谢，更新之后我发现系统变得更加好用了，甚至任务栏都可以透明了，以前任务栏的一个小bug也被修复。我也安装成功了，瞬间感觉世界有变美好了：），再次感谢
