### ISSUE TITLE
Bridge WSA into local network (See local network devices)

### ISSUE THREAD

**Issue by jandie1505** [LSPosed/MagiskOnWSA#329]
Is there any way to bridge the WSA into local network (that the WSA is connected with the same network my pc is connected with)?
I need this to show Google cast devices.

**Comment by Toggy85** [comment]
Want to put in Windows Subsystem for Android?

**Comment by jandie1505** [comment]
> Want to put in Windows Subsystem for Android?

I want to see the devices in my local network with WSA.

**Comment by Howard20181** [comment]
follow this thread
https://www.reddit.com/r/WSA/comments/s73fma/networking_solution_needed/

**Comment by jandie1505** [comment]
This method will work until I restart my computer. After restarting, I'm unable to get internet access on windows. To regain Internet access, i have to remove the wifi bridge in control panel. It also slows down my internet connection from 50 mbit/s to 1 mbit/s.

**Comment by PeterNjeim** [comment]
@jandie1505 try this<sup>[[1]](https://www.reddit.com/r/WSA/comments/ryhcho/question_regarding_networking/hxn4sf7)</sup>:

> I forgot the really important thing here, to avoid "bricking" your network interface after a reboot you need to do this
>
> 1. Turn off WSL (if you are using it) by issuing `wsl --shutdown` on cmd.
> 2. Open "Network Connections" from the Windows Control Panel, find your internet device, enable IPv4 and disable "Hyper-V virtual switch".
> 3. Open Hyper-V Manager and redo the bridge like in my original post.
> 4. Open WSA android settings and setting DHCP.
>
> Unfortunately I cannot provide you a better answer, i think that some savvy PowerShell guru can make this whole process "scriptable" and runnable automatically at the startup.

## References

1. ‘Question Regarding Networking’. _R/WSA_, 7 Jan. 2022, www.reddit.com/r/WSA/comments/ryhcho/question_regarding_networking/hxn4sf7.

**Comment by a0533057932** [comment]
Did the new Windows update not resolve the issue?
https://blogs.windows.com/windows-insider/2022/05/20/update-to-windows-subsystem-for-android-on-windows-11/
