### ISSUE TITLE
Downloading artifact issue

### ISSUE THREAD

**Issue by ahmedhosnypro** [LSPosed/MagiskOnWSA#333]
I can't download the artifact from github because I have slow connection, ant it is not supporting download resume,
so please uplode this file to google drive on any cloud supporting resum downloading 
WSA-with-magisk-GApps-pico_2203.40000.3.0_x64_Release-Nightly

**Comment by PeterNjeim** [comment]
Uploading to a cloud storage provider is not feasible as it would fill the free quota very quickly if more than 4 people used it. If you mean you want someone to personally upload the file for you, the filename you shared doesn't contain all the information, such as the Magisk channel or Microsoft Store channel, though I can guess the Magisk is stable and the Microsoft Store channel is retail. It should be easy for the project maintainers to build a sensible default for MagiskOnWSA: x86, retail channel, stable Magisk, and full GApps, and share that via a cloud storage provider whenever a new version is released, that way no one needs to wait 10-15 minutes for the action to run, and then even longer to download from GitHub's slow artifact servers. However I don't know if the licenses of WSA, Android, Open GApps, and Magisk permit this type of distribution.

Unfortunately I don't think there's a way to download GitHub artifacts the normal way. Azure Pipelines (the service GitHub uses) seems insistent on downloading in this unorthodox manner.

**Comment by AhmedHosnyAdmin** [comment]
> 
I managed to solve the problem by adding the following line to the end of the forked repo workflow which compresses the artifact to a smaller size and make a new release to the repo, here's the code: 
      - name: Compress
        uses: TonyBogdanov/zip@1.0
        with:
          args: zip -qq -r "./${{ env.artifact_name }}.zip" "./${{ matrix.arch }}/"
      - name: to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT }}
        with:
          file: "./${{ env.artifact_name }}.zip"
          tags: false
          draft: true
          update_latest_release: true

**Comment by AhmedHosnyAdmin** [comment]
> Uploading to a cloud storage provider is not feasible as it would fill the free quota very quickly if more than 4 people used it. If you mean you want someone to personally upload the file for you, the filename you shared doesn't contain all the information, such as the Magisk channel or Microsoft Store channel, though I can guess the Magisk is stable and the Microsoft Store channel is retail. It should be easy for the project maintainers to build a sensible default for MagiskOnWSA: x86, retail channel, stable Magisk, and full GApps, and share that via a cloud storage provider whenever a new version is released, that way no one needs to wait 10-15 minutes for the action to run, and then even longer to download from GitHub's slow artifact servers. However I don't know if the licenses of WSA, Android, Open GApps, and Magisk permit this type of distribution.
> 
> Unfortunately I don't think there's a way to download GitHub artifacts the normal way. Azure Pipelines (the service GitHub uses) seems insistent on downloading in this unorthodox manner.

check my forked repo here:
https://github.com/ahmedhosnypro/MagiskOnWSA/releases

**Comment by PeterNjeim** [comment]
> I managed to solve the problem by adding the following line to the end of the forked repo workflow which compresses the artifact to a smaller size and make a new release to the repo, here's the code: - name: Compress uses: TonyBogdanov/zip@1.0 with: args: zip -qq -r "./${{ env.artifact_name }}.zip" "./${{ matrix.arch }}/" - name: to release uses: xresloader/upload-to-github-release@v1 env: GITHUB_TOKEN: ${{ secrets.GIT }} with: file: "./${{ env.artifact_name }}.zip" tags: false draft: true update_latest_release: true

That's a much smarter way of doing it. I'll probably do that myself as well. You should make a Pull Request for it.

**Comment by AhmedHosnyAdmin** [comment]
downloading releases supporting resumable downloading, and better for publishing, 
I may suggest official comitter to make releases

**Comment by AhmedHosnyAdmin** [comment]
> > I managed to solve the problem by adding the following line to the end of the forked repo workflow which compresses the artifact to a smaller size and make a new release to the repo, here's the code: - name: Compress uses: TonyBogdanov/zip@1.0 with: args: zip -qq -r "./${{ env.artifact_name }}.zip" "./${{ matrix.arch }}/" - name: to release uses: xresloader/upload-to-github-release@v1 env: GITHUB_TOKEN: ${{ secrets.GIT }} with: file: "./${{ env.artifact_name }}.zip" tags: false draft: true update_latest_release: true
> 
> That's a much smarter way of doing it. I'll probably do that myself as well. You should make a Pull Request for it.

I made a pull request yesterday, they said just do it in your forked repo, but I'll do again

**Comment by yujincheng08** [comment]
9c667854f6e245ca8b24c48640dbf1f5bcc331c1
