### ISSUE TITLE
Not able to signin to google.

### ISSUE THREAD

**Issue by ashoktvm** [LSPosed/MagiskOnWSA#334]
I am not able to sign in to the play store. This is the error that pops up

![image](https://user-images.githubusercontent.com/45116583/168275839-6f1c1026-655a-4c1a-8f79-4d2bd7a9451e.png)

**Comment by razandtim** [comment]
Showed me the same.
But I exited and opened again Play Store and it worked logging me in.
So idk what happened..

**Comment by Howard20181** [comment]
Check network connection
