### ISSUE TITLE
How do I backup apps to uninstall Windows Subsystem?

### ISSUE THREAD

**Issue by razandtim** [LSPosed/MagiskOnWSA#335]
I want to uninstall Windows Subsystem because it started to crash and wasn't connecting to the internet.
But I want to keep the apps, so how can I backup my apps??

**Comment by Howard20181** [comment]
Backup `%localappdata%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx`

**Comment by razandtim** [comment]
Can you show me how to do that? The file is encrypted.

**Comment by Howard20181** [comment]
You can't decrypt it, you only can do a full backup.

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/168497670-158ff79c-3aaf-46be-8ec0-adc74748ed76.png)
