### ISSUE TITLE
Add missing VpnDialogs to /system/priv-apps?

### ISSUE THREAD

**Issue by NyaMisty** [LSPosed/MagiskOnWSA#337]
Hi, I've seen we've already added ExternalFileProvider, can we also add VpnDialogs so that we can use VPN apps like clash without App Ops?

**Comment by Howard20181** [comment]
You can use a proxy on Windows
Run this script as service.d

`redfin:/data/adb/service.d # cat WSA-set-proxy.sh`
```
#!/system/bin/sh

# start after emulated storage is setup
while [ ! -d "/storage/emulated/0/Android" ]; do
  sleep 3
done

gethostip() {
  ip=$(ip route list match 0 table all scope global | cut -F3)
  if [ -z "$ip" ]; then
    return 1
  else
    echo $ip
  fi
}

while ! (gethostip); do
  sleep 3
done

settings put global http_proxy $(gethostip):7890
settings put global https_proxy $(gethostip):7890
```

**Comment by NyaMisty** [comment]
@Howard20181 
As long as you used Android phones in China before, you would know setting up those thing won't work for all traffic.

**Comment by Howard20181** [comment]
```
adb shell 
settings put secure always_on_vpn_app com.github.kr328.clash # replace package name to your vpn app
reboot
```

**Comment by NyaMisty** [comment]
> ```
> adb shell 
> settings put secure always_on_vpn_app com.github.kr328.clash # replace package name to your vpn app
> reboot
> ```

That's exactly same as App Ops, just changed to command line version, so why not simply put the missing file in?

**Comment by Howard20181** [comment]
> That's exactly same as App Ops, just changed to command line version, so why not simply put the missing file in?

Need to sign your own embedded VpnDialogs application using the system's signature, we can't get Microsoft's signature

**Comment by NyaMisty** [comment]
> > That's exactly same as App Ops, just changed to command line version, so why not simply put the missing file in?
> 
> Need to sign your own embedded VpnDialogs application using the system's signature, we can't get Microsoft's signature

In this theory, external file provider shouldn't be able to be added from GSI

**Comment by vvb2060** [comment]
https://developer.android.com/guide/topics/manifest/permission-element

一个是 privileged 级别权限，丢priv-app就能拿到，一个是 signature 级别权限，需要和系统框架具有相同签名。这事你只能去找微软。

**Comment by NyaMisty** [comment]
> https://developer.android.com/guide/topics/manifest/permission-element
> 
> 一个需要 privileged 级别权限，apk丢priv-app就能拿到，一个需要 signature 级别权限，得和系统框架具有相同签名。这事你只能去找微软。

Got it, CONTROL_VPN needs privileged|signature: https://android.googlesource.com/platform/frameworks/base/+/01875b0274e74f97edf6b0d5c92de822e0555d03/core/res/AndroidManifest.xml#2182

**Comment by vvb2060** [comment]
等等，那个|是「或」的意思，看起来是记错了。我试试看加进去能不能用

**Comment by NyaMisty** [comment]
Well but there's still a  BIND_VPN_SERVICE, does this matter?
https://android.googlesource.com/platform/frameworks/base/+/01875b0274e74f97edf6b0d5c92de822e0555d03/core/res/AndroidManifest.xml#1982

**Comment by NyaMisty** [comment]
In VpnDialogs's manifest there only these:
https://android.googlesource.com/platform/frameworks/base.git/+/master/packages/VpnDialogs/AndroidManifest.xml

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/168471260-3577a8c1-bcfd-4424-8bd3-d8f8345e6c5f.png)

**Comment by NyaMisty** [comment]
Oh, the manifest I've gived is outdated:
base framework's manifest: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android11-gsi/core/res/AndroidManifest.xml#1983, always on vpn needs signature

but control_vpn should enough?

**Comment by vvb2060** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}: java.lang.SecurityException: ConnectivityService: Neither user 10054 nor current process has android.permission.CONTROL_ALWAYS_ON_VPN

**Comment by NyaMisty** [comment]
Can we delete this permission? Using tools like apktools

**Comment by Howard20181** [comment]
> Can we delete this permission? Using tools like apktools

Try it yourself.
You can get the source code of VpnDialogs from AOSP and then modify it.

**Comment by NyaMisty** [comment]
> > Can we delete this permission? Using tools like apktools
> 
> Try it yourself. You can get the source code of VpnDialogs from AOSP and then modify it.

LOL, needn't to do that. GSI have prebuilt CI for you.
What I don't know is how to test them out in WSA. I used to have writable system, but WSA is not

**Comment by Howard20181** [comment]
> LOL, needn't to do that. GSI have prebuilt CI for you. What I don't know is how to test them out in WSA. I used to have writable system, but WSA is not

Magisk module

**Comment by vvb2060** [comment]
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/VpnDialogs/src/com/android/vpndialogs/ConfirmDialog.java;l=72

把这个功能删除，即可移除 CONTROL_ALWAYS_ON_VPN 权限。这样应该就能用了

**Comment by NyaMisty** [comment]
> https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/VpnDialogs/src/com/android/vpndialogs/ConfirmDialog.java;l=72
> 
> 把这个功能删除，即可移除 CONTROL_ALWAYS_ON_VPN 权限。这样应该就能用了

Should be simpler, in Android 11 there's a extra guard, so permission error should be automatically caught, simply editing AndroidManifest should be enough:
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r48:frameworks/base/packages/VpnDialogs/src/com/android/vpndialogs/ConfirmDialog.java

**Comment by vvb2060** [comment]
RemoteException不是SecurityException的超类

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/168474739-1f85d9d3-3cca-420e-8574-77b0262c0a28.png)

**Comment by vvb2060** [comment]
由于只需要读取名字，所以可用`settings get secure always_on_vpn_app`替代完成功能，这仅需要`android.permission.INTERACT_ACROSS_USERS`。我打算重写完成这个功能，而不是现在这样直接修改字节码。
