### ISSUE TITLE
it seemed that lsposed framework can't work properly

### ISSUE THREAD

**Issue by HanHan233** [LSPosed/MagiskOnWSA#34]
![image](https://user-images.githubusercontent.com/64469437/139539997-229c3f27-786d-4f2f-8713-275985cc1da7.png)
![image](https://user-images.githubusercontent.com/64469437/139540057-c74a37aa-e2d7-4314-8c01-ecc1329bb426.png)

**Comment by yujincheng08** [comment]
Zygisk: Yes...

**Comment by HanHan233** [comment]
![image](https://user-images.githubusercontent.com/64469437/139541241-73b13ccd-93f9-4fae-a454-4e8b75570dbb.png)
i have turned it off and lsp can now work.
it was my first time to use touch zygisk.(((
