### ISSUE TITLE
i see this error every time i try to install it

### ISSUE THREAD

**Issue by HelloWorldV6** [LSPosed/MagiskOnWSA#343]
i tried everything it gives the same error when i try to install normal wsa but it works even so there was an error but magisk onwsa dosent work 
![Screenshot 2022-05-16 183638](https://user-images.githubusercontent.com/90615785/168641502-882aa834-f4b2-42f0-bfdf-9269dd2e89cf.png)

**Comment by PeterNjeim** [comment]
Make sure to uninstall the Microsoft Store version of WSA first. If you already did that, then please share the logs with the command it asks you to run in the error message: `Get-AppPackageLog -ActivityID <id>`

**Comment by PeterNjeim** [comment]
Alternatively follow the steps here: https://answers.microsoft.com/en-us/windows/forum/all/cant-remove-w10-packages-error-0x80073cfa/c224a864-b604-42b8-a770-57049e0dc50a

**Comment by HelloWorldV6** [comment]
***here are the logs:***
Time                      ID           Message
----                      --           -------
5/17/2022 9:03:37 AM      603          Started deployment Register operation on a package with main parameter
                                       AppxManifest.xml and Options
                                       ForceApplicationShutdownOption,DevelopmentModeOption,ForceUpdateFromAnyVersion
                                       and 0. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing
                                       app deployment issues.
5/17/2022 9:03:37 AM      216          App manifest validation warning: Declared namespace
                                       http://schemas.microsoft.com/developer/appx/2015/build is inapplicable, it
                                       will be ignored during manifest processing.
5/17/2022 9:03:37 AM      709          Rejecting a request to register from AppxBundleManifest.xml because the
                                       manifest is not in the package root.
5/17/2022 9:03:37 AM      404          AppX Deployment operation failed for package  with error 0x80070057. The
                                       specific error text for this failure is: Rejecting a request to register from
                                       AppxBundleManifest.xml because the manifest is not in the package root.
***i tried the method it didnt work***

**Comment by HelloWorldV6** [comment]
i get the same error when i try to install microsoft store ver but even so it says install feaild it works

**Comment by PeterNjeim** [comment]
When you say you get the same error from the Microsoft Store version, do you mean that the error code is shown in the Microsoft Store, under the install button?

I'm surprised the method I shared didn't work, did it give any error messages?

**Comment by HelloWorldV6** [comment]
Not from Microsoft store I got the package from a website that download stuff from Microsoft servers maybe it's called ad guard or something the method you give made was appear but when I run it it doesn't install Google play and it's not rooted which means that is the normal version I tried to uninstall it with couple of ways but it doesn't get uninstalled it's just hidden I have 4 users in my computer,if you cannot help me can you please tell me where is all was files located I will try to delete them

**Comment by PeterNjeim** [comment]
MagiskOnWSA also uses the store-rg.adguard website, except it adds Magisk and GApps to it later.

Run the troubleshooter found here: https://answers.microsoft.com/en-us/windows/forum/all/how-to-manually-uninstall-a-store-app/963863e4-4c0b-4565-af90-f5bc7ecf3f47, then see if uninstalling it is possible. If it still isn't, the method I shared earlier should fix the uninstallation problem, maybe try running it in an admin PowerShell?

**Comment by HelloWorldV6** [comment]
i ran it as admin the troubleshooter is not working it seem like it is a windows bug,can you please tell me where is wsa files if you know i will try to unistall it by my self ,thanks

**Comment by AhmedHosnyAdmin** [comment]
try using app like Iobit unninstaller
(download it from  
https://lrepacks.net/repaki-sistemnyh-programm/227-iobit-uninstaller-amp-portable.html)  to uninstall wsa 
![image](https://user-images.githubusercontent.com/24454782/169025600-7d16ac35-bbc1-493c-ab2c-f855b0b27252.png)

![image](https://user-images.githubusercontent.com/24454782/169025463-9337c737-2d8d-4ade-bc41-19d50b71f6b6.png)

 if this won't woek use forced mode to uninstallation 

if you extracted wsa pakeage and installed using "Add-AppxPackage -Register AppxManifest.xml"
then wsa is running from the folder caontainin the "AppxManifest.xml" file
ex: Add-AppxPackage -Register "C:\Windows Subsystem for Android\AppxManifest.xml"

wsa data location
 "%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache"
and search for "WindowsSubsystemForAndroid"

you can use registry finder (download it from google search)
![image](https://user-images.githubusercontent.com/24454782/169024838-e55401c7-e0f7-4cac-80e4-133827272011.png)
 and search for "WindowsSubsystemForAndroid"
![image](https://user-images.githubusercontent.com/24454782/169024995-440a5fe4-c559-40a0-a8f1-628f926d52b8.png)

select all valuse and export them, then delete them all, restart

**Comment by HelloWorldV6** [comment]
how to use forced mode in iobit unistaller

**Comment by PeterNjeim** [comment]
Did you follow Ahmed's instructions? Here is the relevant image from his post:
> ![](https://user-images.githubusercontent.com/24454782/169026791-b7cabab5-52b7-408f-b65d-5da5a68810c9.png)

**Comment by HelloWorldV6** [comment]
didnt work i think its windows error i have to close this
