### ISSUE TITLE
I cannot install, I receive this error "Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor."

### ISSUE THREAD

**Issue by Behnam-Emamian** [LSPosed/MagiskOnWSA#346]
![image](https://user-images.githubusercontent.com/9818491/168967637-cc8cd9ff-8ced-4856-838f-9d0b3a5cca61.png)

**Comment by AhmedHosnyAdmin** [comment]
you can use the 5th line to show what gone wrong
copy it and run in powershell

maybe it can't find some files, 
try to extract all files againg 
maybe antivrus deleted some files or your downloaded file was interrupted,

**Comment by MirionQs** [comment]
Because ./WsaProxy/WsaProxy.dll file is missing
