### ISSUE TITLE
Better solution to GitHub storage abuse

### ISSUE THREAD

**Issue by PeterNjeim** [LSPosed/MagiskOnWSA#349]
A recent<sup>[[1]](https://github.com/LSPosed/MagiskOnWSA/commit/494a52c5a307eeeb5ca7ec8242324d6be8cfd2c2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60)</sup> claim was added to the README:
> Keeping old workflow runs can take up a lot of storage resources and is suspected to be abusive, which can lead to banning

This is true<sup>[[2]](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#9-excessive-bandwidth-use)</sup>:

> 9. Excessive Bandwidth Use
> The Service's bandwidth limitations vary based on the features you use. If we determine your bandwidth usage to be significantly excessive in relation to other users of similar features, we reserve the right to suspend your Account, throttle your file hosting, or otherwise limit your activity until you can reduce your bandwidth consumption. We also reserve the right—after providing advance notice—to delete repositories that we determine to be placing undue strain on our infrastructure. For guidance on acceptable use of object storage in repositories, refer to "[What is my disk quota?](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota)". For more details on specific features' bandwidth limitations, see the [GitHub Additional Product Terms](https://docs.github.com/en/github/site-policy/github-additional-product-terms).`

However the solution implemented (deleting old Actions runs) is improper. A solution is already provided by GitHub, simply go to the repository settings and adjust the artifact retention period<sup>[[3]](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization)</sup>:

> By default, the artifacts and log files generated by workflows are retained for 90 days before they are automatically deleted. You can adjust the retention period, depending on the type of repository:
>
> - For public repositories: you can change this retention period to anywhere between 1 day or 90 days.

Another GitHub-endorsed solution is to use Releases instead<sup>[[4]](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries)</sup>:

> Distributing large binaries
If you need to distribute large files within your repository, you can create releases on GitHub.com. Releases allow you to package software, release notes, and links to binary files, for other people to use. For more information, visit "[About releases](https://docs.github.com/en/github/administering-a-repository/about-releases)."
>
> We don't limit the total size of the binary files in the release or the bandwidth used to deliver them. However, each individual file must be smaller than 2 GB.

Compression allows the file to be less than 2 GB. Releases also allow the file to be downloaded without limited bandwidth, unlike Actions artifacts. Releases are also designed to be stored in a central repository, causing even less strain on GitHub's servers. GitHub reserves the right to delete problematic repositories, such as this one, for encouraging forks of duplicated data. A central Releases page would achieve the following:

1. Reduce storage strain on GitHub by not requiring users to fork and store more data
2. Reduce GitHub Actions runner usage by not requiring an Action to be run in a fork
3. Reduce store.rg-adguard.net API usage by only running the Action once per GApps, Magisk, and architecture combination
4. Reduce GitHub bandwidth usage by not requiring artifact uploads in forks of the same binaries
5. Reduce complexity for users by not requiring them to download binaries in an unorthodox way, by forking and running an Action
6. Reduce time wasted by users waiting for an Action to complete
7. Reduce time wasted by users waiting for an artifact to download at slow speeds (and fail entirely without a resume option on slow connections)

I understand there has been resistance to this change by a few contributors (but notably not all of them). The resistance has so far been unjustified, with no stated reason for not implementing the change. Since Howard seems to be concerned with GitHub's data usage, I'm sure he'll consider this change, as it will dramatically reduce the strain on GitHub's servers.

<details>
<summary>

## References
</summary>

1. "Explain Why the Old Workflow Runs Should Be Deleted · LSPosed/MagiskOnWSA@494a&#8206;52c". _GitHub_, [https:&#8206;//github.com/LSPosed/MagiskOnWSA/commit/494a52c5a307eeeb5ca7ec8242324d6be8cfd2c2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60](https://github.com/LSPosed/MagiskOnWSA/commit/494a52c5a307eeeb5ca7ec8242324d6be8cfd2c2).
2. "GitHub Acceptable Use Policies". _GitHub Docs_, https://ghdocs-prod.azurewebsites.net/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#9-excessive-bandwidth-use.
3. "Configuring the Retention Period for GitHub Actions Artifacts and Logs in Your Organization". _GitHub Docs_, https://ghdocs-prod.azurewebsites.net/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization.
4. "About Large Files on GitHub". _GitHub Docs_, https://ghdocs-prod.azurewebsites.net/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries.
</details>

**Comment by Rexogamer** [comment]
> I understand there has been resistance to this change by a few contributors (but notably not all of them). The resistance has so far been unjustified, with no stated reason for not implementing the change.

Out of curiosity, are there any issue where said resistance has come up? I'm curious to see if there's any extra context

**Comment by PeterNjeim** [comment]
It started here: https://github.com/LSPosed/MagiskOnWSA/issues/333
Then the pull requests are where the resistence emerged:
https://github.com/LSPosed/MagiskOnWSA/pull/339
https://github.com/LSPosed/MagiskOnWSA/pull/340
https://github.com/LSPosed/MagiskOnWSA/pull/341
https://github.com/LSPosed/MagiskOnWSA/pull/342

**Comment by Rexogamer** [comment]
Without wanting to cause any drama/further tensions, the response to these requests does seem rather hostile and vague and I fail to see a clear reason why these proposals are a bad idea

**Comment by yujincheng08** [comment]
We have internally discussed this issue, and we decided we won't make releases. The reasons are as follows:
1. There're too many combinations of choices: WSA version, OpenGApps version, Magisk version, etc. We cannot list all possible decisions, and yet hard to decide what are the most demands.
2. Illegal concern about releasing modified versions of WSA.
3. We have to tediously trace the updates of WSA, OpenGApps and Magisk to update the release.
4. Some users are concerned about the trustability of the pre-built releases.

We previously tried to upload the artifacts to the release page, but it requires users to set an API Token for uploading. So we gave up this choice.

**Comment by PeterNjeim** [comment]
> We previously tried to upload the artifacts to the release page, but it requires users to set an API Token for uploading. So we gave up this choice.

Look at my fork. No need to upload artifacts at all. Default token is enough to upload a Release. With artifacts I get 2 MB/s download speed. With Releases I get 95 MB/s download speed.

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/169660628-340fd31a-b578-4307-b8d4-01cc626961b0.png)

**Comment by PeterNjeim** [comment]
![image](https://user-images.githubusercontent.com/26418974/169661047-489fee89-5c18-46eb-aa09-9e37723adfb3.png)
Pretty sure you need a tag_name as well. Regardless, are you specifying your own token or using the default token `${{ github.token }}`. I use the default token (by not specifying it at all). If it still doesn't work, try putting:
```yaml
permissions:
  contents: write
```
at the top of the workflow file.

Example of formatting: 
![image](https://user-images.githubusercontent.com/26418974/169661144-c1eb3811-ec12-4926-bd1c-ca3ad90317f7.png)

**Comment by PeterNjeim** [comment]
If it still doesn't work, adding instructions to tell the user to go to the repository settings and enable write access could also work:
![image](https://user-images.githubusercontent.com/26418974/169661372-364db59e-26da-4372-a371-7cbe9b00a9f9.png)

![image](https://user-images.githubusercontent.com/26418974/169661387-81dba4bd-b366-40eb-8034-9c2053840ccd.png)

![image](https://user-images.githubusercontent.com/26418974/169661392-4047bd85-0667-4f20-b5dd-8c962b2de819.png)

**Comment by yujincheng08** [comment]
> adding instructions to tell the user to go to the repository settings and enable write access

That's what we don't want to do. Just let it go...

**Comment by PeterNjeim** [comment]
Please do not ignore messages. I sent 2 solutions, you only replied to one of them. I didn't have the time to test earlier but now I did. Adding:
```yaml
permissions:
  contents: write
```
as I said earlier (and the README of softprops/action-gh-release also says to do this), solves the issue, no extra user input is needed! Now users can enjoy 47x times faster download speeds!
