### ISSUE TITLE
How would you go in on updating this, once WSA Receives an update without Reinstalling the Whole Thing ?

### ISSUE THREAD

**Issue by Kristijan1001** [LSPosed/MagiskOnWSA#35]
How would you go in on updating this, once WSA Receives an update without Reinstalling the Whole Thing, You wouldnt want to reinstall all apps every update ya know ?

**Comment by yujincheng08** [comment]
In README.MD

> Unzip the artifact and uninstall WSA if you have an official installation or replace the pevious unzipped artifact if you have a manual installation

**Comment by Kristijan1001** [comment]
> In README.MD
> 
> > Unzip the artifact and uninstall WSA if you have an official installation or replace the pevious unzipped artifact if you have a manual installation

This doesnt answer the question i asked. This is the second time this gets closed without an actual answer ??????

**Comment by Kristijan1001** [comment]
Like i don't understand the stubborneds lmao. Here is a guy saying that is possible to do without reinstall. Which thread got insta closed also.

https://github.com/LSPosed/MagiskOnWSA/issues/21

**Comment by yujincheng08** [comment]
> replace the previous unzipped artifact if you have a manual installation

this is the anwser

**Comment by yujincheng08** [comment]
> Like i don't understand the stubborneds lmao. Here is a guy saying that is possible to do without reinstall. Which thread got insta closed also.
> 
> #21

Close because we added this to the readme.

**Comment by Kristijan1001** [comment]
> > replace the previous unzipped artifact if you have a manual installation
> 
> this is the anwser

Sorry, but that can be elaborated. Have no idea what that means. Should i just unzip the archive and replace everything.

**Comment by yujincheng08** [comment]
> Sorry, but that can be elaborated

If you think this is not elaborated enough, you can help us to polish it.

> Should i just unzip the archive and replace everything.

Y

**Comment by Kristijan1001** [comment]
> > Sorry, but that can be elaborated
> 
> If you think this is not elaborated enough, you can help us to polish it.
> 
> > Should i just unzip the archive and replace everything.
> 
> Y

I am just asking for help. What is with the attitude ? Jesus... I ain't the only one confused by it. You literally have 3 dislikes on the post you made.

**Comment by yujincheng08** [comment]
> I am just asking for help. What is with the attitude ? Jesus... I ain't the only one confused by it. You literally have 3 dislikes on the post you made.

I did help you. And what's with the attribute? Jesus...

**Comment by Kristijan1001** [comment]
It looks like there is a language barrier going on here or a lot of stubbornness. Take care dude.

**Comment by SonaliBendre** [comment]
> It looks like there is a language barrier going on here or a lot of stubbornness. Take care dude.

No, its just PoWEr of CcP

**Comment by BlueGlassBlock** [comment]
It's just inside the default app installing drive.
![image](https://user-images.githubusercontent.com/50769752/140614504-620114aa-ba52-4b34-ade6-8afa6f32771b.png)
It has NOTHING to do with the app directory (which is extracted from the .zip file).
