### ISSUE TITLE
WSA build now failing after WSA update to Android 12.1

### ISSUE THREAD

**Issue by flutterp0ne** [LSPosed/MagiskOnWSA#351]

**Comment by PeterNjeim** [comment]
Wow never knew it was updated: https://www.windowscentral.com/windows-11-subsystem-android-updated-12.1.

I'll take a look at what causes the error

**Comment by jovanzers** [comment]
Failing in Extract GApps and expand images

**Comment by yujincheng08** [comment]
we should enlarge the resize2fs size

**Comment by yujincheng08** [comment]
product.img or system_ext.img is now larger

**Comment by PeterNjeim** [comment]
OpenGApps for Android 12.1/12L, though not built for x86_64: https://drive.google.com/drive/folders/1ae_5jUOVG-spr63T0jyBpj6n3Anh4xKL

**Comment by PeterNjeim** [comment]
> I'll try building myself from: [opengapps/opengapps#959](https://github.com/opengapps/opengapps/pull/959)

Here is pico GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/QmcWnPtdKR3pnmmkwcNhFwXbQtjuJfvK9irk2jurdC8K63
full GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/Qmbh8NKAtiaYSgXHj7GTXMcU2AqxCp3jof31Gneffr8XNi
(links will only work when my PC is on (when I'm not sleeping))

Note that full GApps causes WSA 12.1/12L to fail to complete the boot procedure (this happens with 11.0 full GApps as well)

**Comment by alex-sandro92** [comment]
> > I'll try building myself from: [opengapps/opengapps#959](https://github.com/opengapps/opengapps/pull/959)
> 
> Here is pico GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/QmcWnPtdKR3pnmmkwcNhFwXbQtjuJfvK9irk2jurdC8K63?filename=open_gapps-x86_64-12L-pico-20220521-UNOFFICIAL.zip full GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/Qmbh8NKAtiaYSgXHj7GTXMcU2AqxCp3jof31Gneffr8XNi?filename=open_gapps-x86_64-12L-full-20220520-UNOFFICIAL.zip (links will only work when my PC is on (when I'm not sleeping))
> 
> Note that full GApps causes WSA 12.1/12L to fail to complete the boot procedure (this happens with 11.0 full GApps as well)

Does it work for you? I tried building gapps nano and pico but wsa fail to boot with both of them...

**Comment by PeterNjeim** [comment]
Works with pico for me

**Comment by benferizi** [comment]
Thanks a lot !On May 21, 2022 6:13 PM, Peter Njeim ***@***.***> wrote:

I'll try building myself from: opengapps/opengapps#959

Here is pico GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/QmcWnPtdKR3pnmmkwcNhFwXbQtjuJfvK9irk2jurdC8K63
full GApps 12.1/12L: http://peternjeim.ddns.net:8081/ipfs/Qmbh8NKAtiaYSgXHj7GTXMcU2AqxCp3jof31Gneffr8XNi
(links will only work when my PC is on (when I'm not sleeping))
Note that full GApps causes WSA 12.1/12L to fail to complete the boot procedure (this happens with 11.0 full GApps as well)

**Comment by alex-sandro92** [comment]
> Works with pico for me.
> 
> Try my build on the Releases page here: https://github.com/PeterNjeim/MagiskOnWSA/releases

Thank you! But I get the same problem with a fresh installation of your package... I will investigate on this

```
Source
Windows Subsystem for Android(TM)

Summary
Stopped responding and was closed

Date
‎23/‎5/‎2022 12:29

Status
Report sent

Description
A problem caused this program to stop interacting with Windows.
Faulting Application Path:	C:\Users\angela\Documents\wsa\WsaClient\WsaClient.exe

Problem signature
Problem Event Name:	MoAppHangXProc
Package Full Name:	MicrosoftCorporationII.WindowsSubsystemForAndroid_2204.40000.15.0_x64__8wekyb3d8bbwe
Application Name:	praid:App
Application Version:	2204.40000.15.0
Application Timestamp:	6277155c
Hang Signature:	04d3
Hang Type:	2097216
Waiting on Package Full Name:	UNKNOWN
Waiting on Application Name:	WsaService.exe
Waiting on Application Version:	0.0.0.0
Versione SO:	10.0.22621.2.0.0.768.101
ID impostazioni locali:	1040
Additional Hang Signature 1:	04d330a94de19a3a2fd149b718c4e7d1
Additional Hang Signature 2:	f2cc
Additional Hang Signature 3:	f2cc31e396dc50698348bc6e0b82f072
Additional Hang Signature 4:	04d3
Additional Hang Signature 5:	04d330a94de19a3a2fd149b718c4e7d1
Additional Hang Signature 6:	f2cc
Additional Hang Signature 7:	f2cc31e396dc50698348bc6e0b82f072

Extra information about the problem
Bucket ID:	9eec0bffe838fa89d4b737fed7c158d1 (1492723369177602257)
```
