### ISSUE TITLE
Build WSA failed

### ISSUE THREAD

**Issue by noahhhi** [LSPosed/MagiskOnWSA#353]
requests.exceptions.SSLError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Error: Process completed with exit code 1.

**Comment by vvb2060** [comment]
Your branch is [12 commits behind](https://github.com/noahhhi/MagiskOnWSA/compare/main...LSPosed:main) LSPosed:main
