### ISSUE TITLE
Skip Magisk

### ISSUE THREAD

**Issue by azhe403** [LSPosed/MagiskOnWSA#358]
Can you provide option to skip magisk, because seem not work in Android 12

![image](https://user-images.githubusercontent.com/17938038/169641888-fb9120e8-a27d-40c0-aa8b-50657ab6fa7e.png)

**Comment by yujincheng08** [comment]
root solution

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/169642348-0a15e1f9-685a-4565-a755-71e7d7edfcba.png)

**Comment by PeterNjeim** [comment]
> Can you provide option to skip magisk, because seem not work in Android 12

Magisk works, what doesn't work is full GApps. I had to switch to pico for it to boot.
