### ISSUE TITLE
Android 12.1

### ISSUE THREAD

**Issue by Slion** [LSPosed/MagiskOnWSA#360]
Is this now using the latest WSA update?
Would it work in the Beta channel even though that update is only for the Dev channel?

See:
https://blogs.windows.com/windows-insider/2022/05/20/update-to-windows-subsystem-for-android-on-windows-11/

**Comment by vvb2060** [comment]
https://github.com/LSPosed/MagiskOnWSA/commit/3d00cea9c549d0ee8f55a0c8aabfbf82025e61ef

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/169649532-36fb4c3c-d60c-4a73-b764-8c3da357f750.png)
