### ISSUE TITLE
No Windows Subsystem for Android

### ISSUE THREAD

**Issue by Bartholomew22** [LSPosed/MagiskOnWSA#361]
The Power Shell install process completes with a display flash.  There is no Windows Subsystem for Android found.  I'm not a coder so I have no idea how to diagnose this issue.  I tried installing both the X64 and the arm64 packages.

My environment is: Windows 11 Build 25120, Intel i7 w/16gb memory, 4k display

**Comment by Howard20181** [comment]
Need more info.

Use a text editor to open `install.ps1` and execute the command manually. Submit error message.
