### ISSUE TITLE
WSA Android 12 crashes with gapps included

### ISSUE THREAD

**Issue by flutterp0ne** [LSPosed/MagiskOnWSA#364]
Here's a logcat if it helps
[20220522023058.log](https://github.com/LSPosed/MagiskOnWSA/files/8748571/20220522023058.log)

**Comment by Howard20181** [comment]
The Opengapps build for Android 12 has not been released and is now using Android 11 as a replacement. The problem will not be solved until a new version of Opengapps is released and the pico version is recommended.
