### ISSUE TITLE
ARM PC won't install after update to Android 12

### ISSUE THREAD

**Issue by lisyclover** [LSPosed/MagiskOnWSA#367]
I am using arm pc, even if I don't choose to integrate gapp, I still can't complete the installation, I can only install the official version

**Comment by Howard20181** [comment]
No logs or screenshots.

**Comment by lisyclover** [comment]
> 

sorry  ,how do i get that

**Comment by lisyclover** [comment]
> No logs or screenshots.
sorry,how do i get that
