### ISSUE TITLE
WSA启动失败

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSA#368]
安装最新12L的WSA（root+nano）后启动时弹出启动框，不久(大约一分钟)后启动框自动关闭，WSA无法启动

**Comment by fairms** [comment]
似乎只有pico能够允许

**Comment by a0533057932** [comment]
PICO NOGAPSS employees
I get complaints about FULL and STOCK not working

**Comment by Howard20181** [comment]
https://github.com/LSPosed/MagiskOnWSA/issues/364#issuecomment-1133797773
