### ISSUE TITLE
WSA Won't Start After Updating to Latest Version

### ISSUE THREAD

**Issue by MHN452** [LSPosed/MagiskOnWSA#369]
I reinstalled the new WSA but it won't start now. I could open the new settings but trying to open Files doesn't work. It would show the "Starting Windows Subsystem for Android" window and then it'd disappear. Log attached below

[23052022172430.log](https://github.com/LSPosed/MagiskOnWSA/files/8753785/23052022172430.log)

**Comment by yujincheng08** [comment]
opengapps does not fully support Android 12L. Use `pico` variant.
