### ISSUE TITLE
WSA Stuck in Loading and Google Play Store Doesn't Install

### ISSUE THREAD

**Issue by bamblakopz** [LSPosed/MagiskOnWSA#374]
**Here is what it says in Event Viewer:**
The program WsaClient.exe version 2203.40000.3.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

 EventData 

  AppName WsaClient.exe 
  AppVersion 2203.40000.3.0 
  ProcessId 0x1280 
  StartTime 0x1d86efc3cbee2c5 
  TerminationTime 4294967295 
  ExeFileName C:\Google Play Store\WsaClient\WsaClient.exe 
  ReportId 1495435b-4a75-4785-bcc9-bfa01bd3f351 
  PackageFullName MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe 
  PackageRelativeAppId App 
  HangType Quiesce 

**It tells me to review further in Security and Maintenance, and here is what it says there:**

Source
Windows Subsystem for Android(TM)

Summary
Stopped working

Date
‎5/‎23/‎2022 5:55 PM

Status
Report sent

Description
Faulting Application Path:	C:\Google Play Store\WsaClient\WsaClient.exe

Problem signature
Problem Event Name:	MoBEX
Package Full Name:	MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe
Application Name:	praid:App
Application Version:	2203.40000.3.0
Application Timestamp:	623e3ecc
Fault Module Name:	WsaClient.exe
Fault Module Version:	2203.40000.3.0
Fault Module Timestamp:	623e3ecc
Exception Offset:	00000000000399c5
Exception Code:	c0000409
Exception Data:	0000000000000007
OS Version:	10.0.22621.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	cf48
Additional Information 2:	cf482a423c90fc42d6c71eb7586f2ca3
Additional Information 3:	c87b
Additional Information 4:	c87be7cd743fbd09ed3fe3eb5a287738

Extra information about the problem
Bucket ID:	df83e7244319ea92c5179fddf0b0d5d0 (1519859174835541456)

**Comment by bamblakopz** [comment]
Uninstalled everything and started over completely. I have the same issue, where it just is stuck in loading and Google Play Store doesn't install. This is the error I have in the event viewer:

Faulting application name: WsaClient.exe, version: 2203.40000.3.0, time stamp: 0x623e3ecc
Faulting module name: WsaClient.exe, version: 2203.40000.3.0, time stamp: 0x623e3ecc
Exception code: 0xc0000409
Fault offset: 0x00000000000399c5
Faulting process id: 0x0x35E0
Faulting application start time: 0x0x1D86F16836D1F87
Faulting application path: C:\Windows Subsystem for Android\WsaClient\WsaClient.exe
Faulting module path: C:\Windows Subsystem for Android\WsaClient\WsaClient.exe
Report Id: 54959f38-aca3-4f9c-b790-3f4086379dea
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by bamblakopzALT** [comment]
Can you elaborate? Do you mean which variant I chose? Or did I miss a step?

**Comment by alex-sandro92** [comment]
Yes, he means the variant

**Comment by bamblakopzALT** [comment]
> 

I did use the Pico one initially. But I had other issues I’ve since resolved. I can try that one again.

**Comment by bamblakopzALT** [comment]
> Does the official original version(from Microsoft Store) start properly?

I’m not sure what you mean here. I’ve only ever downloaded and installed the one through GitHub

**Comment by alex-sandro92** [comment]
> Does the official original version(from Microsoft Store) start properly?

yes, the problem is OpenGApps which doesn't fully support Android 12

**Comment by alex-sandro92** [comment]
> > > Does the official original version(from Microsoft Store) start properly?
> > 
> > 
> > yes, the problem is OpenGApps which doesn't fully support Android 12
> 
> Confused on how I should proceed with all of this. I’ll download the pico version again. Anything else I need to do?

This is how I made it work:

1) Right click on WSA > app settings > repair and reset data
2) Uninstall WSA
3) Delete content of WSA folder (where you extract the package)
4) Build the package you need selecting **the Pico variant** in the action tab
5) Download it and install it

**Comment by Howard20181** [comment]
> > Does the official original version(from Microsoft Store) start properly?
> 
> yes, the problem is OpenGApps which doesn't fully support Android 12

Version 2203 base on Android 11

**Comment by bamblakopz** [comment]
I've uninstalled WSA. I've made sure that my drivers were updated and my computer in general is updated. 

I then again downloaded the PICO variant. I come up with the same issue. Here is the event tracker info again:

Faulting application name: WsaClient.exe, version: 2203.40000.3.0, time stamp: 0x623e3ecc
Faulting module name: WsaClient.exe, version: 2203.40000.3.0, time stamp: 0x623e3ecc
Exception code: 0xc0000409
Fault offset: 0x00000000000399c5
Faulting process id: 0x0x5C8
Faulting application start time: 0x0x1D86FBF338FE00C
Faulting application path: C:\Windows Subsystem for Android\WsaClient\WsaClient.exe
Faulting module path: C:\Windows Subsystem for Android\WsaClient\WsaClient.exe
Report Id: 9a7d0e8d-5e24-4f26-8084-00d1d191dc47
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by bamblakopz** [comment]
Any more ideas? I've worked on this off and on for 4 days. Troubleshot and problem solved to get SO close. It is infuriating to be so close just have the WSA loading forever and the Google Play App never downloading.

**Comment by Howard20181** [comment]
Install WSA from https://apps.microsoft.com/store/detail/windows-subsystem-for-android%E2%84%A2-with-amazon-appstore/9P3395VX91NR to check that the original version is working properly

**Comment by WebWire-NL** [comment]
> Any more ideas? I've worked on this off and on for 4 days. Troubleshot and problem solved to get SO close. It is infuriating to be so close just to have the WSA loading forever and the Google Play App never downloading.

If the google is just to Install Google Play (no root) i would follow the normal approach for now.... Google for: dos2unix apply.sh windows subsystem android google play

**Comment by PeterNjeim** [comment]
> I've uninstalled WSA

@bamblakopz Did you only uninstall it? Or did you do what @alex-sandro92 said: https://github.com/LSPosed/MagiskOnWSA/issues/374#issuecomment-1136384442 and fully repaired and reset WSA before uninstalling and removing the folder you extracted completely. If you follow those steps (video instructions if it's still unclear: https://github.com/LSPosed/MagiskOnWSA/issues/351#issuecomment-1134833750), then pico GApps should work fine. If you're unsure about your own build, download the version from my Releases page instead: https://github.com/PeterNjeim/MagiskOnWSA/releases/download/c19fe50/WSA-with-magisk-GApps-pico_2204.40000.15.0_x64_Release-Nightly.zip

**Comment by DaKingof** [comment]
> > I've uninstalled WSA
> 
> @bamblakopz Did you only uninstall it? Or did you do what @alex-sandro92 said: [#374 (comment)](https://github.com/LSPosed/MagiskOnWSA/issues/374#issuecomment-1136384442) and fully repaired and reset WSA before uninstalling and removing the folder you extracted completely. If you follow those steps (video instructions if it's still unclear: [#351 (comment)](https://github.com/LSPosed/MagiskOnWSA/issues/351#issuecomment-1134833750)), then pico GApps should work fine. If you're unsure about your own build, download the version from my Releases page instead: https://github.com/PeterNjeim/MagiskOnWSA/releases/download/c19fe50/WSA-with-magisk-GApps-pico_2204.40000.15.0_x64_Release-Nightly.zip

thank you. Your build works just fine. The first time I tried to install my build on my virtual machine it worked just fine and then an update came in and programs wouldn't open anymore. I whiped my drive a few times thinking maybe it was some of my tinkering that broke it so I was very careful to do it all properly this time and still nothing with current build with 3.0 at the end. When attempting to instal mine the two windows would open up almost imediately. It would only take a couple seconds for the powershel to finish. I'm assuming it's not processing the things it should so there must be an error in the build itself as your version took about two minutes before these same windows open and it worked just like the first time I opened it. Thanks again.

**Comment by ashoktvm** [comment]
Does this stable version have android 12 or do we have to select insider slow?

**Comment by Howard20181** [comment]
> Does this stable version have android 12 or do we have to select insider slow?

Insider fast only.

**Comment by ashoktvm** [comment]
Process is failing now as Downloading WSA

![image](https://user-images.githubusercontent.com/45116583/171262714-c57f6710-2150-467a-9857-bebb3d762059.png)

**Comment by PeterNjeim** [comment]
> Process is failing now as Downloading WSA
> 
> ![image](https://user-images.githubusercontent.com/45116583/171262714-c57f6710-2150-467a-9857-bebb3d762059.png)
> 

Your problem is unrelated to this issue. This is not a forum. Please open a new issue dedicated to your problem.

**Comment by PeterNjeim** [comment]
Request that this issue be closed @Howard20181. It's due to the user not properly uninstalling their previous A11 version of WSA (with the repair and reset buttons).

**Comment by PeterNjeim** [comment]
You didn't respond to me when I @'d you saying you followed the steps, therefore I thought you were inactive. Regardless, since the issue is not reproducible, it should be closed, not because you've "given up".

**Comment by DaKingof** [comment]
> You didn't respond to me when I @'d you saying you followed the steps, therefore I thought you were inactive. Regardless, since the issue is not reproducible, it should be closed, not because you've "given up".

I'm literally having the same exact issue and my comment was hidden.

**Comment by PeterNjeim** [comment]
> > You didn't respond to me when I @'d you saying you followed the steps, therefore I thought you were inactive. Regardless, since the issue is not reproducible, it should be closed, not because you've "given up".
> 
> I'm literally having the same exact issue with this build and my comment was hidden.

Well, I meant it wasn't reproducible after the proper uninstallation steps were taken. Since they claimed they followed these uninstallation steps and are still having the issue, we can't reproduce it.

Did you try fully uninstalling my build and try this repo's one again?

**Comment by DaKingof** [comment]
> > > You didn't respond to me when I @'d you saying you followed the steps, therefore I thought you were inactive. Regardless, since the issue is not reproducible, it should be closed, not because you've "given up".
> > 
> > 
> > I'm literally having the same exact issue with this build and my comment was hidden.
> 
> Well, I meant it wasn't reproducible after the proper uninstallation steps were taken. Since they claimed they followed these uninstallation steps and are still having the issue, we can't reproduce it.
> 
> Did you try fully uninstalling my build and try this repo's one again?

I did it many times and only your build works. I think maybe it's because I am using an SSD and they banned this drive from WSA? I noticed when I go to the Microsoft official it says it's incompatible because of my drive, but it works just fine with your version.

**Comment by PeterNjeim** [comment]
You need to specify your drive and specifically what the Microsoft Store tells you. "SSD" is a category of drive and is used by most computers these days, and so can't possibly be the problem

**Comment by DaKingof** [comment]
This is what my store says when following the link posted above to MS store. I'm not sure why it would say that either, but it does.

![image](https://user-images.githubusercontent.com/31186364/173705801-8ced2883-df35-4791-aedd-57c840286ff7.png)

**Comment by PeterNjeim** [comment]
@DaKingof please share a screenshot of your Task Manager on the Performance tab

**Comment by DaKingof** [comment]
This is while using the version you posted @PeterNjeim 
![image](https://user-images.githubusercontent.com/31186364/173714779-9f018652-16cb-49a6-82c1-053300d76731.png)

**Comment by PeterNjeim** [comment]
The screenshot doesn't depend on what's going on with your PC btw, just wanted to check if your SSD had a problem.

You see how under your disk it says "HDD"? That's the problem.

Open an admin command prompt and run `winsat disk -drive C` to re-benchmark the drive, hopefully it'll show up as an SSD in Task Manager. If it still doesn't, let me know

**Comment by PeterNjeim** [comment]
Hello guys, full GApps works on WSA Android 12.1 now! Try the one in my latest release: https://github.com/PeterNjeim/MagiskOnWSA/releases/download/WSA/WSA-with-magisk-GApps-full_2204.40000.19.0_x64_Release-Nightly.zip
