### ISSUE TITLE
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF9, 无法安装。请联系你的软件供应商。

### ISSUE THREAD

**Issue by gamecss** [LSPosed/MagiskOnWSA#38]
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF9, 无法安装。请联系你的软件供应商。 (异常来自 HRESULT:0x80073CF9)
正在拒绝从 AppxBundleManifest.xml 进行注册的请求，因为部件清单(manifest)没有位于程序包根目录中。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] 64b33030-c8d7-0002-03c5-b964d7c8d701，或使用命令行 Get-AppPackageLo
g -ActivityID 64b33030-c8d7-0002-03c5-b964d7c8d701
所在位置 行:1 字符: 1
+ Add-AppxPackage -Register .\AppxManifest.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\WSA64\AppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by gamecss** [comment]
@yujincheng08

**Comment by gamecss** [comment]
![image](https://user-images.githubusercontent.com/52902973/139581083-6dba934f-569f-4b09-a562-4b963a50be7c.png)
@yujincheng08

**Comment by Lulutima** [comment]
Try `Remove-AppxPackage MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe -AllUsers` before

**Comment by xstmass** [comment]
Maybe add command in the post above to in install script? She solves the author's problem @yujincheng08

**Comment by Howard20181** [comment]
卸载已安装的原版WSA再试

**Comment by gamecss** [comment]
> Try `Remove-AppxPackage MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe -AllUsers` before

no installed

**Comment by vignakke** [comment]
> > Try `Remove-AppxPackage MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe -AllUsers` before
> 
> no installed

I had the same problem, I solved it by downloading "everything" and with this search: "MicrosoftCorporationII.WindowsSubsystemForAndroid" and the command that Lulutima sent with each package I found

**Comment by Jerry12798** [comment]
> > > Try `Remove-AppxPackage MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe -AllUsers` before
> > 
> > 
> > no installed
> 
> I had the same problem, I solved it by downloading "everything" and with this search: "MicrosoftCorporationII.WindowsSubsystemForAndroid" and the command that Lulutima sent with each package I found

What is downloading everything? You removed everything you downloaded? I have the same issue and need a bit more context to try  your fix

**Comment by vignakke** [comment]
> > > > Try `Remove-AppxPackage MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe -AllUsers` before
> > > 
> > > 
> > > no installed
> > 
> > 
> > I had the same problem, I solved it by downloading "everything" and with this search: "MicrosoftCorporationII.WindowsSubsystemForAndroid" and the command that Lulutima sent with each package I found
> 
> What is downloading everything? You removed everything you downloaded? I have the same issue and need a bit more context to try your fix

sorry for late, everything is a software to find ALL files on ur computer
