### ISSUE TITLE
Build Stop because dependencies 

### ISSUE THREAD

**Issue by wine97** [LSPosed/MagiskOnWSA#380]
If I try to build the project i got a problem with the tar dependencie

**Comment by vvb2060** [comment]
no info

**Comment by wine97** [comment]
i dont need to send you the full log here is the snipped

Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for udev (245.4-4ubuntu3.17) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for wine (5.0-3ubuntu1) ...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
