### ISSUE TITLE
Build problems with TAR

### ISSUE THREAD

**Issue by wine97** [LSPosed/MagiskOnWSA#381]
Since my last post was closed directly after 30 seconds without looking at the log, I have problems with the build again because it cannot find tar here is the log sipped 

Setting up libzvbi0:amd64 (0.2.35-17) ...
Setting up libgstreamer-plugins-base1.0-0:amd64 (1.16.2-4ubuntu0.1) ...
Setting up libopenal1:amd64 (1:1.19.1-1) ...
Setting up python3-networkx (2.4-3ubuntu1) ...
/usr/lib/python3/dist-packages/networkx/readwrite/tests/test_graphml.py:933: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert H.nodes['n1']['special'] is 0
/usr/lib/python3/dist-packages/networkx/readwrite/tests/test_graphml.py:935: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert H.edges['n0','n1',1]['special'] is 0
Setting up libavutil56:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up libv4l-0:amd64 (1.18.0-2build1) ...
Setting up libgphoto2-6:amd64 (2.5.25-0ubuntu0.1) ...
Setting up libgstreamer-plugins-good1.0-0:amd64 (1.16.2-1ubuntu2.1) ...
Setting up gstreamer1.0-plugins-base:amd64 (1.16.2-4ubuntu0.1) ...
Setting up va-driver-all:amd64 (2.7.0-2) ...
Setting up libshout3:amd64 (2.4.3-1) ...
Setting up libjack-jackd2-0:amd64 (1.9.12~dfsg-2ubuntu2) ...
Setting up vdpau-driver-all:amd64 (1.3-1ubuntu2) ...
Setting up libsndfile1:amd64 (1.0.28-7ubuntu0.1) ...
Setting up python3-setools (4.2.2-1ubuntu2) ...
Setting up gstreamer1.0-x:amd64 (1.16.2-4ubuntu0.1) ...
Setting up libpulse0:amd64 (1:13.99.1-1ubuntu3.13) ...
Setting up gstreamer1.0-plugins-good:amd64 (1.16.2-1ubuntu2.1) ...
Setting up setools (4.2.2-1ubuntu2) ...
Setting up libsane:amd64 (1.0.29-0ubuntu5.2) ...
Adding scanner group...
Setting up libswresample3:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up libavcodec58:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up sane-utils (1.0.29-0ubuntu5.2) ...
update-inetd: warning: cannot add service, /etc/inetd.conf does not exist
Adding saned group and user...
Adding user saned to group scanner
Setting up libsdl2-2.0-0:amd64 (2.0.10+dfsg1-3) ...
Setting up libasound2-plugins:amd64 (1.2.2-1ubuntu1) ...
Setting up libfaudio0:amd64 (20.04-2) ...
Setting up libwine:amd64 (5.0-3ubuntu1) ...
Setting up wine64 (5.0-3ubuntu1) ...
Setting up wine (5.0-3ubuntu1) ...
Setting up winetricks (0.0+20200412-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for udev (245.4-4ubuntu3.17) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for wine (5.0-3ubuntu1) ...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.

**Comment by vvb2060** [comment]
read readme
