### ISSUE TITLE
the new version WSA 2203 i think having a small bugs 

### ISSUE THREAD

**Issue by williamvyong** [LSPosed/MagiskOnWSA#383]
new version WSA 2203 having a minor bugs like wireless debugging having some problem 
sorry cause im not pro ,correct me tq 
cause i try to install TAPO but every 5 minute automatically pops up telling me that im not using same ip with my router 
so i think is version problem cause when i use old version of WSA no pop up just having full screen problem 
but after install new version only this ip problem make me headache

**Comment by vvb2060** [comment]
ask Microsoft
