### ISSUE TITLE
Unable to open the Install powershell script in Windows powershell

### ISSUE THREAD

**Issue by chandansoumya28** [LSPosed/MagiskOnWSA#384]
While opening the install script an error occurs. 

function Test-Administrator
{
    [OutputType([bool])]
    param()
    process {
        [Security.Principal.WindowsPrincipal]$user = [Security.Principal.WindowsIdentity]::GetCurrent();
        return $user.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator);
    }
}

if(-not (Test-Administrator))
{
    Start-Process -Verb RunAs powershell.exe -Args "-executionpolicy bypass -command Set-Location `"$PSScriptRoot`"; `"$PSCommandPath`""
    exit
}

$ErrorActionPreference = "Stop";
Add-AppxPackage -Register .\AppxManifest.xml

**Comment by Howard20181** [comment]
No logs or screenshots.
