### ISSUE TITLE
Error when I run Install.ps1

### ISSUE THREAD

**Issue by mapomme1108** [LSPosed/MagiskOnWSA#385]
Hello,

I have successfully build the WSA package but when I run Install.ps1, there is this error message 

`Add-AppxPackage: Deployment failed with HRESULT: 0x80073CFD, A requirement for an installation could not be met`

I don't know what to do.

Help would be greatly appriciated.

Thanks :)

**Comment by yujincheng08** [comment]
Your system does not support WSA.

**Comment by mapomme1108** [comment]
Hello,

What are the supported systèmes?

I have Windows 11 Pro

**Comment by Howard20181** [comment]
Check if a new version of WSA has been installed (downgrading is not allowed).
Check if it is an arm64 system, which requires a corresponding architecture.

**Comment by Howard20181** [comment]
<html>
<body>
<h2 class="" style="font-size: 3em; color: rgb(30, 30, 30); margin-bottom: 20px; padding-bottom: 0px; font-weight: 300; box-sizing: border-box; font-family: &quot;Segoe UI Light&quot;, &quot;Segoe WP Light&quot;, wf_segoe-ui_light, wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Helvetica, Tahoma, Arial, sans-serif; line-height: 1.33; margin-top: 48px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Device requirements</h2><p style="font-size: 1.6em; box-sizing: border-box; color: rgb(30, 30, 30); line-height: 1.5; padding: 0px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, wf_segoe-ui_normal, &quot;Helvetica Neue&quot;, &quot;BBAlpha Sans&quot;, &quot;S60 Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Make sure your device has Windows 11 installed. To see the minimum requirements needed for your PC, go to <a href="https://www.microsoft.com/windows/windows-11-specifications" target="_blank" class="ocpExternalLink" ms.cmpgrp="content" ms.pgarea="Body" style="color: rgb(0, 108, 172); text-decoration: none; box-sizing: border-box;">Windows 11 Specs and System Requirements</a>. To use mobile apps on your device, your PC also needs to meet these requirements:</p><p style="font-size: 1.6em; box-sizing: border-box; color: rgb(30, 30, 30); line-height: 1.5; padding: 0px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, wf_segoe-ui_normal, &quot;Helvetica Neue&quot;, &quot;BBAlpha Sans&quot;, &quot;S60 Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

RAM | 8 GB (minimum)16 GB (recommended)
-- | --
Storage type | Solid State Drive (SSD)
Processor | Intel Core i3 8th Gen (minimum) or aboveAMD Ryzen 3000 (minimum) or aboveQualcomm Snapdragon 8c (minimum) or above
Processor architecture | x64 or ARM64
Virtual Machine Platform | This setting needs to be enabled. For more info, go to Enable virtualization on Windows 11 PCs.


</body>
</html>
