### ISSUE TITLE
gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by Lummox342** [LSPosed/MagiskOnWSA#393]
When running the build after a fork. No matter what options are selected. The build process fails due to a missing file it would appear. FAQ didn't seem to help. I have R/W permissions on for my workflow runs.

Run pip3 install beautifulsoup4 lxml
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting lxml
  Downloading lxml-4.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4, lxml
Successfully installed beautifulsoup4-4.11.1 lxml-4.9.0 soupsieve-2.3.2.post1
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
Hit:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Get:7 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1833 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [337 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [15.4 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1010 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [144 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [926 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [208 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [20.7 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [23.7 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [860 B]
Get:17 http://azure.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1491 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu focal-security/main Translation-en [257 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [10.4 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [948 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu focal-security/restricted Translation-en [135 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [705 kB]
Get:23 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [161 kB]
Get:24 http://azure.archive.ubuntu.com/ubuntu focal-security/universe Translation-en [126 kB]
Get:25 http://azure.archive.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.5 kB]
Fetched 8711 kB in 2s (4563 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
patchelf is already the newest version (0.10-2build1).
The following additional packages will be installed:
  cabextract fonts-wine fuseiso gstreamer1.0-plugins-base
  gstreamer1.0-plugins-good gstreamer1.0-x i965-va-driver
Setting up libsoxr0:amd64 (0.1.3-2build1) ...
Setting up libcapi20-3:amd64 (1:3.27-3) ...
Setting up libaom0:amd64 (1.0.0.errata1-3build1) ...
Setting up libvkd3d1:amd64 (1.1-4) ...
Setting up update-inetd (4.50) ...
Setting up libxvidcore4:amd64 (2:1.3.7-1) ...
Setting up libgphoto2-l10n (2.5.25-0ubuntu0.1) ...
Setting up libflac8:amd64 (1.3.3-1build1) ...
Setting up fonts-wine (5.0-3ubuntu1) ...
Setting up python3-decorator (4.4.2-0ubuntu1) ...
Setting up fuseiso (20070708-3.2build1) ...
Setting up libva2:amd64 (2.7.0-2) ...
Setting up libigdgmm11:amd64 (20.1.1+ds1-1) ...
Setting up libcodec2-0.9:amd64 (0.9.2-2) ...
Setting up lzip (1.21-6build1) ...
Setting up libopus0:amd64 (1.3.1-0ubuntu1) ...
Setting up intel-media-va-driver:amd64 (20.1.1+dfsg1-1) ...
Setting up libstb0:amd64 (0.0~git20190817.1.052dce1-1) ...
Setting up liborc-0.4-0:amd64 (1:0.4.31-1) ...
Setting up python3-numpy (1:1.17.4-5ubuntu3) ...
Setting up libsndio7.0:amd64 (1.5.0-3) ...
Setting up libtag1v5:amd64 (1.11.1+dfsg.1-0.3ubuntu2) ...
Setting up libva-drm2:amd64 (2.7.0-2) ...
Setting up libdv4:amd64 (1.0.0-12) ...
Setting up ocl-icd-libopencl1:amd64 (2.2.11-1ubuntu1) ...
Setting up libasyncns0:amd64 (0.8-6) ...
Setting up libvdpau1:amd64 (1.3-1ubuntu2) ...
Setting up libwavpack1:amd64 (5.2.0-1ubuntu0.1) ...
Setting up libtheora0:amd64 (1.1.1+dfsg.1-15ubuntu2) ...
Setting up libv4lconvert0:amd64 (1.18.0-2build1) ...
Setting up libopenjp2-7:amd64 (2.3.1-1ubuntu4.20.04.1) ...
Setting up libopenal-data (1:1.19.1-1) ...
Setting up libglu1-mesa:amd64 (9.0.1-1build1) ...
Setting up libgphoto2-port12:amd64 (2.5.25-0ubuntu0.1) ...
Setting up mesa-va-drivers:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libsane-common (1.0.29-0ubuntu5.2) ...
Setting up libieee1284-3:amd64 (0.2.11-13build1) ...
Setting up libsamplerate0:amd64 (0.1.9-2) ...
Setting up libva-x11-2:amd64 (2.7.0-2) ...
Setting up libzvbi-common (0.2.35-17) ...
Setting up libmp3lame0:amd64 (3.100-3) ...
Setting up i965-va-driver:amd64 (2.4.0-0ubuntu1) ...
Setting up libvorbisenc2:amd64 (1.3.6-2ubuntu1) ...
Setting up libaa1:amd64 (1.4p5-46) ...
Setting up libiec61883-0:amd64 (1.2.0-3) ...
Setting up libosmesa6:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libavc1394-0:amd64 (0.5.4-5) ...
Setting up mesa-vdpau-drivers:amd64 (21.2.6-0ubuntu0.1~20.04.2) ...
Setting up libzvbi0:amd64 (0.2.35-17) ...
Setting up libgstreamer-plugins-base1.0-0:amd64 (1.16.2-4ubuntu0.1) ...
Setting up libopenal1:amd64 (1:1.19.1-1) ...
Setting up python3-networkx (2.4-3ubuntu1) ...
/usr/lib/python3/dist-packages/networkx/readwrite/tests/test_graphml.py:933: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert H.nodes['n1']['special'] is 0
/usr/lib/python3/dist-packages/networkx/readwrite/tests/test_graphml.py:935: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert H.edges['n0','n1',1]['special'] is 0
Setting up libavutil56:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up libv4l-0:amd64 (1.18.0-2build1) ...
Setting up libgphoto2-6:amd64 (2.5.25-0ubuntu0.1) ...
Setting up libgstreamer-plugins-good1.0-0:amd64 (1.16.2-1ubuntu2.1) ...
Setting up gstreamer1.0-plugins-base:amd64 (1.16.2-4ubuntu0.1) ...
Setting up va-driver-all:amd64 (2.7.0-2) ...
Setting up libshout3:amd64 (2.4.3-1) ...
Setting up libjack-jackd2-0:amd64 (1.9.12~dfsg-2ubuntu2) ...
Setting up vdpau-driver-all:amd64 (1.3-1ubuntu2) ...
Setting up libsndfile1:amd64 (1.0.28-7ubuntu0.1) ...
Setting up python3-setools (4.2.2-1ubuntu2) ...
Setting up gstreamer1.0-x:amd64 (1.16.2-4ubuntu0.1) ...
Setting up libpulse0:amd64 (1:13.99.1-1ubuntu3.13) ...
Setting up gstreamer1.0-plugins-good:amd64 (1.16.2-1ubuntu2.1) ...
Setting up setools (4.2.2-1ubuntu2) ...
Setting up libsane:amd64 (1.0.29-0ubuntu5.2) ...
Adding scanner group...
Setting up libswresample3:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up libavcodec58:amd64 (7:4.2.4-1ubuntu0.1) ...
Setting up sane-utils (1.0.29-0ubuntu5.2) ...
update-inetd: warning: cannot add service, /etc/inetd.conf does not exist
Adding saned group and user...
Adding user saned to group scanner
Setting up libsdl2-2.0-0:amd64 (2.0.10+dfsg1-3) ...
Setting up libasound2-plugins:amd64 (1.2.2-1ubuntu1) ...
Setting up libfaudio0:amd64 (20.04-2) ...
Setting up libwine:amd64 (5.0-3ubuntu1) ...
Setting up wine64 (5.0-3ubuntu1) ...
Setting up wine (5.0-3ubuntu1) ...
Setting up winetricks (0.0+20200412-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for udev (245.4-4ubuntu3.17) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for wine (5.0-3ubuntu1) ...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.

**Comment by vvb2060** [comment]
read readme
