### ISSUE TITLE
Previously working normal WSA now crashes on load after uninstalling MagiskOnWSA

### ISSUE THREAD

**Issue by ethan-xd** [LSPosed/MagiskOnWSA#396]
I had a working WSA install (although sideloaded with Add-AppXPackage because I'm outside the USA), and then uninstalled it to install MagiskOnWSA version.

MagiskOnWSA crashed on trying to open any app, so I uninstalled it and decided to go back to regular WSA.

However, now the previously working, freshly reinstalled, 3 times repair/reset WSA install crashes on opening an app, like your install. I cannot figure out what the .ps1 script changed that would cause this behaviour.

```
Faulting application name: WsaClient.exe, version: 2203.40000.3.0, time stamp: 0x623e3ecc
Faulting module name: combase.dll, version: 10.0.22000.653, time stamp: 0x3428f024
Exception code: 0xc0000602
Fault offset: 0x00000000002218bf
Faulting process id: 0xdf0
Faulting application start time: 0x01d8781ee7daf5ed
Faulting application path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Faulting module path: C:\WINDOWS\System32\combase.dll
Report Id: 5c1050f1-5139-44f5-98b0-a500a4fbd7e5
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2203.40000.3.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```
[05062022022516.log](https://github.com/LSPosed/MagiskOnWSA/files/8838046/05062022022516.log)

Any idea what causes this??

**Comment by Howard20181** [comment]
Have you try release fast ring?

**Comment by ethan-xd** [comment]
I'm still getting the same error.

**Comment by Howard20181** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6879

**Comment by Howard20181** [comment]
Report to Microsoft.
