### ISSUE TITLE
How to fix the Error[I'm telling how]

### ISSUE THREAD

**Issue by xiaozhiqi1005172** [LSPosed/MagiskOnWSA#397]
https://github.com/LSPosed/MagiskOnWSA/files/8839193/run.zip
copy it to where wsa is,and just use powershell to run it

**Comment by Howard20181** [comment]
https://github.com/LSPosed/MagiskOnWSA/blob/0c54452496163d00496bfe6f94b8aa6e17a1d0e7/.github/workflows/magisk.yml#L609
