### ISSUE TITLE
2204 build.prop directory 

### ISSUE THREAD

**Issue by abaynp** [LSPosed/MagiskOnWSA#401]
I haven't tried to build 2204 tho, but I've checked build.prop for system_ext and product is inside etc folder. I'm not sure whether [this line](https://github.com/LSPosed/MagiskOnWSA/blob/0c54452496163d00496bfe6f94b8aa6e17a1d0e7/.github/workflows/magisk.yml#L511
) needs to be fixed or not, not a coder my self.

**Comment by yujincheng08** [comment]
no need
