### ISSUE TITLE
Basically Two Questions: 1. Working without Hyper V 2. Waydroid 

### ISSUE THREAD

**Issue by afzl-wtu** [LSPosed/MagiskOnWSA#402]
1. I installed Windows 11 yesterday and directly (without Turning any Windows features On or Off ) ran install script. It restarted my Laptop and then I again ran the script and it installed WSA everything is working fine but it consumes lot of GPU and CPU when playing animation or video in WSA.
My question is, Is it possible to install WSA without WSL or turning Hyper V feature in Windows? Because I did not read anywhere in Tutorial to turn on these features manually, or Script do it automatically?
This is current screenshot of System:
![image](https://user-images.githubusercontent.com/64379149/172893759-abde3c87-bdf5-43d2-ab3d-05af2122872b.png)
You can see, script did not turn on Hyper V or WSL. Is it Ok?

2. Is Waydroid (Android Container for Linux) and WSA is same thing or they differ? Which one is efficient and provides near native android performance?

**Comment by yujincheng08** [comment]
> My question is, Is it possible to install WSA without WSL or turning Hyper V feature in Windows

No

> Waydroid

They are different.

**Comment by afzl-wtu** [comment]
> > My question is, Is it possible to install WSA without WSL or turning Hyper V feature in Windows
> 
> No
> 
> > Waydroid
> 
> They are different.
It is my humble request can you please elaborate.
How WSA is running ? you can see Hyper V is turned off?

**Comment by afzl-wtu** [comment]
Should I turn it On manually?

**Comment by PeterNjeim** [comment]
I don't use Hyper-V and WSA works fine, just like you. I do use WSL though, but it's not required for WSA, because it's working for you, clearly. There's no need to enable Hyper-V or WSL to use WSA.

As for your high CPU and GPU usage, this is probably because WSA currently translates OpenGL ES 3.0 to Direct3D 11, using something called [ANGLE](https://github.com/google/angle), which is quite inefficient, especially for your very slow GPU. When WSA plays a video, I doubt that it's using your GPU's efficient video decoding engine, instead it's probably doing everything in the 3D engine inefficiently, raising both CPU and GPU usage.

Hopefully in the future WSA will instead do Vulkan to Direct3D 12 conversion, or even native Vulkan instead. Maybe one day.

**Comment by PeterNjeim** [comment]
Actually just checked and WSA does use the Video Codec 0 engine on my GPU, but playback is indeed still choppy and inefficient. It's probably just ANGLE at this point.

**Comment by afzl-wtu** [comment]
> I don't use Hyper-V and WSA works fine, just like you. I do use WSL though, but it's not required for WSA, because it's working for you, clearly. There's no need to enable Hyper-V or WSL to use WSA.
> 
> As for your high CPU and GPU usage, this is probably because WSA currently translates OpenGL ES 3.0 to Direct3D 11, using something called [ANGLE](https://github.com/google/angle), which is quite inefficient, especially for your very slow GPU. When WSA plays a video, I doubt that it's using your GPU's efficient video decoding engine, instead it's probably doing everything in the 3D engine inefficiently, raising both CPU and GPU usage.
> 
> Hopefully in the future WSA will instead do Vulkan to Direct3D 12 conversion, or even native Vulkan instead. Maybe one day.

I see. So WSA is just like any other emulator which uses hypervisor level 2. So waydroid in linux is much faster then WSA.
Thanks for your detailed reply.

**Comment by PeterNjeim** [comment]
I wouldn't call hypervisor level 1 "much" faster than hypervisor level 2, but if Waydroid is level 1 then it would indeed be faster. Also, please refrain from using the term "emulator" to refer to virtual machines, they are different things, as you probably know.
