### ISSUE TITLE
Error in "Dependencies"

### ISSUE THREAD

**Issue by saulozt** [LSPosed/MagiskOnWSA#405]
When I run the Action I get an error on Dependencies.

Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for udev (245.4-4ubuntu3.17) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for wine (5.0-3ubuntu1) ...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.

**Comment by yujincheng08** [comment]
try again. its github's issue
