### ISSUE TITLE
Since OpenGapps doesn't officially support Android 12.1 yet, lock the variant to pico!

### ISSUE THREAD

**Issue by AnhDOS** [LSPosed/MagiskOnWSA#412]
I'd like to use stock or full variant but it auto switched to Pico.

**Comment by yujincheng08** [comment]
Since OpenGapps doesn't officially support Android 12.1 yet, lock the variant to pico

**Comment by AnhDOS** [comment]
How to use the lower Android version?

**Comment by yujincheng08** [comment]
select `retail` release type.

**Comment by AnhDOS** [comment]
I selected retail actually.

**Comment by yujincheng08** [comment]
Then no way :)

**Comment by AnhDOS** [comment]
So I should wait until this Repo support it?

**Comment by yujincheng08** [comment]
there's nothing to do with this repo...

**Comment by PeterNjeim** [comment]
GApps full does support WSA 12.1 now. Try the one in my latest release: https://github.com/PeterNjeim/MagiskOnWSA/releases/download/WSA/WSA-with-magisk-GApps-full_2204.40000.19.0_x64_Release-Nightly.zip

**Comment by AnhDOS** [comment]
> GApps full does support WSA 12.1 now. Try the one in my latest release: https://github.com/PeterNjeim/MagiskOnWSA/releases/download/WSA/WSA-with-magisk-GApps-full_2204.40000.19.0_x64_Release-Nightly.zip

Could you please teach me how to build it? I compiled the latest source of this repo but it still generate picon version only.
