### ISSUE TITLE
A way to disguise app running on WSA

### ISSUE THREAD

**Issue by phob** [LSPosed/MagiskOnWSA#416]
Is there any way to disguise running in WSA?
GLTools, Device Faker, Spoof My Device are all LSPosed modules that don't seem to work anymore and it's pretty easy to figure out that this is an emulator. But that's exactly what (X)LSPosed is supposed to be able to disguise. None of the modules seem to work with Android 12 anymore.
![image](https://user-images.githubusercontent.com/2318031/174054887-05869d6f-dd60-49a2-b6e7-e88c9a2e94ff.png)

```
API version
93

Injection Interface
Zygisk

Dex Optimizer Wrapper
Supported

Framework version
1.8.3 (6552)

Manager version
1.8.3 (6552)

System version
12 (API 32)

Device
Google Google Pixel 5 

System ABI
x86_64
```

**Comment by PeterNjeim** [comment]
WSA is a virtual machine, not an emulator. I don't have a comment on your exact request though, hopefully someone else can help you soon
