### ISSUE TITLE
Full GApps for WSA Android 12.1 is now supported

### ISSUE THREAD

**Issue by PeterNjeim** [LSPosed/MagiskOnWSA#417]
Please update the repo by removing the pico restriction on 12.1, and use the newest GApps. Also, any updates on this issue?: https://github.com/LSPosed/MagiskOnWSA/issues/349#issuecomment-1133739971. It requires no user input, which was your main concern, but you never responded for some reason. Also not sure why you locked the issues related to pico/full GApps on WSA Android 12.1. It would be better if you shared why the issue was being locked, because right now it seems weirdly hostile (as other users have noted previously). Is it because I'm sharing my fork? Hopefully not, this is an open source project, right? Thanks in advance

**Comment by vvb2060** [comment]
Open a new issue and quote it instead of replying on an already closed issue.  
Open source projects don't mean you can do whatever you want.

**Comment by PeterNjeim** [comment]
The issue was directly related to what I said though, it was closed since there was no solution at the time, now there is a solution, so I should comment on the same issue (in reality the issue should be re-opened, or even better, never closed in the first place until a solution was available). Regardless, I appreciate the explanation and accept it.

**Comment by yujincheng08** [comment]
opengapps does not support 12 yet: https://api.opengapps.org/list

**Comment by vvb2060** [comment]
We cannot trust 3rd party openGapps especially hosted on home pc via ddns.

**Comment by PeterNjeim** [comment]
OpenGapps does support 12.1, you're simply referring to their API. Building it yourself with this PR: https://github.com/opengapps/opengapps/pull/959 works as expected (I did it). Here are the builds: https://ipfs.infura.io/ipfs/QmULfSMwWuukQR7r9KEvwD2XzsChHTvpswmNqJyEU64jwM?filename=open_gapps-x86_64-12L-full-20220616-UNOFFICIAL.zip
https://ipfs.infura.io/ipfs/QmPDiAyqUvZHo9QU7WfoEE9XMqC8ppGyUsSwKQY7chfwHX?filename=open_gapps-x86_64-12L-pico-20220616-UNOFFICIAL.zip

**Comment by PeterNjeim** [comment]
> We cannot trust 3rd party openGapps especially hosted on home pc via ddns.

My DDNS is just for speed, IPFS is actually hosted by many peers, not just me. Not only that, no need to trust me, build it yourself and use it for this repo :)

**Comment by yujincheng08** [comment]
That PR is not even merged!

**Comment by PeterNjeim** [comment]
It's not merged because they're testing "website compatibility". So far nothing wrong's been found with the PR itself

**Comment by yujincheng08** [comment]
So it's still under test :)

**Comment by PeterNjeim** [comment]
Also, I forgot to mention but there is a problem with the build process since opengapps has updated since the PR was made. After you git pull origin master after checking out the PR locally, you'll need to modify the scripts/inc.buildtarget.sh file and remove some if statements from lines 223-226 and 298-301 (make sure to keep the double-semi-colon (;;))

**Comment by yujincheng08** [comment]
Just wait for the official prebuilt version.
