### ISSUE TITLE
Doesn't work on Windows 11 Business Edition Enterprise

### ISSUE THREAD

**Issue by oxygene08** [LSPosed/MagiskOnWSA#422]
winver is 22000.739 (updated today) and the WSA package used for the build process is 2204.40000.19.0, yet I keep getting the following error:
`Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.`
The windows itself was also installed today so it's a clean install and Microsoft's "Amazon" version of WSA works flawlessly. Any suggestion?

**Comment by Howard20181** [comment]
Check that you have chosen the correct architecture.

**Comment by oxygene08** [comment]
it's x64 on an Intel core i5

**Comment by clmcgrath** [comment]
Also having issues ,  with Windows 11 pro Insider Beta channel 
![image](https://user-images.githubusercontent.com/452012/174416605-97178eee-40e0-4d8a-8ff7-1708ac7cf44e.png)
Magisk, and other apps open with starting was screen then crash with no error 
![image](https://user-images.githubusercontent.com/452012/174416712-2c5aa4ea-c598-4596-8a53-393f27146fc5.png)
using 
WSA-with-magisk-NoGApps_2204.40000.19.0_x64_Release-Nightly image from actions build x64 
running i9 12990k / RTX 3060 / 32gb ddr5 ram

**Comment by oxygene08** [comment]
oh dear I had no idea.
thanks you just saved my life.
