### ISSUE TITLE
Issues with crashing on win 11 insider preview 

### ISSUE THREAD

**Issue by clmcgrath** [LSPosed/MagiskOnWSA#423]
Currently having issues with Windows 11 pro Insider Beta channel 
![image](https://user-images.githubusercontent.com/452012/174416605-97178eee-40e0-4d8a-8ff7-1708ac7cf44e.png)
Magisk, and other apps open with starting WSA screen then crash with no error 
![image](https://user-images.githubusercontent.com/452012/174416712-2c5aa4ea-c598-4596-8a53-393f27146fc5.png)
![image](https://user-images.githubusercontent.com/452012/174416852-02843e7c-cb10-4677-8a7d-62c978a3d252.png)

using 
WSA-with-magisk-NoGApps_2204.40000.19.0_x64_Release-Nightly image from actions build x64 
running i9 12990k / RTX 3060 / 32gb ddr5 ram

**Comment by vvb2060** [comment]
WSA-with-magisk-NoGApps_2204.40000.19.0_x64_Release-Nightly

NoGApps

**Comment by clmcgrath** [comment]
???

**Comment by mfisher224** [comment]
Same issue here. Got it to install but crashes after a few seconds of "Starting Windows Subsystem for Android". Also on Beta.
