### ISSUE TITLE
Video shows install off LSPosed-zygisk-v.1.6.2-6185-release.zip but not mentioned in readme

### ISSUE THREAD

**Issue by roughiain** [LSPosed/MagiskOnWSA#43]
The video shows the install of `LSPosed-zygisk-v.1.6.2-6185-release.zip` but no links to the file or mention of it in the documents.

**Comment by MayuriNFC** [comment]
> The video shows the install of `LSPosed-zygisk-v.1.6.2-6185-release.zip` but no links to the file or mention of it in the documents.

https://github.com/LSPosed/LSPosed/actions
Maybe this is what you are looking for

**Comment by roughiain** [comment]
Will try
