### ISSUE TITLE
A non-PICO Google package

### ISSUE THREAD

**Issue by a0533057932** [LSPosed/MagiskOnWSA#430]
Is there any way to download WSA today with a FULL or STOCK package or any non-PICO package?
Each ring I choose downloads the Android 12L and the PICO package anyway
post Scriptum. Perhaps the right question is how to set up an Android 11 download

**Comment by muhyunusomar** [comment]
There aren't available GAPPS available for android 12. But you can download FULL or STOCK packages for another versions of android. If you're setting up Android on Windows 11 so you can download PICO package of Android 11.

**Comment by a0533057932** [comment]
I know there are no GAPPS for Android 12
The problem I opened is that it is no longer possible to download Android 11 where all the GAPPS packages could have been downloaded

**Comment by yujincheng08** [comment]
Sorry, https://store.rg-adguard.net no longer provides the Android 11 version of WSA.

![image](https://user-images.githubusercontent.com/5022927/175253670-98dc6fcf-d5cf-49b5-8fd9-adf21e19598a.png)
