### ISSUE TITLE
Magisk installed but no playstore

### ISSUE THREAD

**Issue by UniversalParadox** [LSPosed/MagiskOnWSA#431]
Hi guys,

Sorry if this has been answered or not but trying to get this installed and I get to the point of where Magisk is installed BUT there is no google play store after installation. I've made sure of the following and still nothing.

Dev mode enabled on Win11
Dev mode enabled on Subsystem after installation
Did manual run of the install.ps1 after uninstalling everything.
Disabled windows firewall

**Comment by yujincheng08** [comment]
But you didn't select gapps.
