### ISSUE TITLE
Issue with logging in for Google Mobile Services with GApps (tested with pico)

### ISSUE THREAD

**Issue by Delta18-Git** [LSPosed/MagiskOnWSA#44]
When I installed this fork of WSA, I selected the pico GApps so I can get Play Store access. However, it doesn't seem to be working on Windows 11 Insider, Beta Build 22000.282.
![image](https://user-images.githubusercontent.com/64347927/139691518-d1ccc9a6-9ede-49ad-99a2-2cab78fd44eb.png)

**Comment by kristibektashi** [comment]
Try selecting Nano

**Comment by Delta18-Git** [comment]
Ok. I also was however unable to install or really do anything with Magisk. I also installed AuroraDroid but it was failing to get any apps. I however uninstalled WSA to try and re do the process, so will not be able to give screenshots yet.

**Comment by Delta18-Git** [comment]
Why was this closed?

**Comment by Delta18-Git** [comment]
Reinstalled with nano GApps. Still can't use Magisk nor Play store.

Magisk:
![image](https://user-images.githubusercontent.com/64347927/139720622-44a27df6-135f-4e80-8ce1-f01d4b40f20a.png)

Play Store:
![image](https://user-images.githubusercontent.com/64347927/139720658-cda073d7-a53e-4ce2-8124-b7f58783f081.png)

**Comment by Delta18-Git** [comment]
Can someone reopen this or tell me why this was closed?
@vvb2060?

**Comment by Delta18-Git** [comment]
Sorry if this wasn't meant to go here, or if it wasn't relevant.

**Comment by Howard20181** [comment]
Check your Internet connection

**Comment by Delta18-Git** [comment]
I am connected to the internet, and it doesn't explain why I am unable to install any Magisk modules either. It doesn't work for the Amazon Appstore as well, and it just loops back to the sign in button. 
I am writing this out on the same laptop with these problems and my internet is fine.

**Comment by Howard20181** [comment]
Try to install a browser in WSA and browse Google

**Comment by Delta18-Git** [comment]
Magisk Logs if useful:

[magisk_log_2021-11-02T00_00_47Z (1).log](https://github.com/LSPosed/MagiskOnWSA/files/7455420/magisk_log_2021-11-02T00_00_47Z.1.log)

**Comment by Delta18-Git** [comment]
> Try to install a browser in WSA and browse Google

Ok. Will install Bromite.

**Comment by Delta18-Git** [comment]
Update: Was using Cloudflare WARP which was interfering in the Android apps internet, but Magisk still doesn't work and Zygisk never says yes although I have turned off and started WSA many times.
