### ISSUE TITLE
WSA in German, how i can get this

### ISSUE THREAD

**Issue by zafirab19** [LSPosed/MagiskOnWSA#443]
Good Evening, i have made my own WSA Package with Gapps, how i can include the german language?, by your package is the subsystem on my computer german.

how you do this?

**Comment by Howard20181** [comment]
@zafirab19 https://github.com/LSPosed/MagiskOnWSA/blob/1f3721dbd941a096e53a0b14001ab1a4ae2759f2/.github/workflows/magisk.yml#L402

**Comment by zafirab19** [comment]
im not understand what that is, what have you make there?

is this commands for linux oder shell or what?
