### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by BoscoChung1234** [LSPosed/MagiskOnWSA#444]
When running a build of WSA, it gives an error

e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
system_ext: 83/96 files (1.2% non-contiguous), 33596/33697 blocks
resize2fs 1.45.5 (07-Jan-2020)
resize2fs: New size smaller than minimum (33596)
Error: Process completed with exit code 1.
![image](https://user-images.githubusercontent.com/49752794/176985262-76d07fed-82c0-49ac-a3bd-23562161562d.png)

**Comment by Howard20181** [comment]
![IMG_20220702_120441](https://user-images.githubusercontent.com/40033067/176985869-f8166619-1a3a-47d1-a5af-4caba036c405.jpg)
