### ISSUE TITLE
Failed Building

### ISSUE THREAD

**Issue by Nanboom233** [LSPosed/MagiskOnWSA#445]
![image](https://user-images.githubusercontent.com/43744483/176991845-e4ae8399-b738-4cd6-9e80-05ec68a90b24.png)

**Comment by Nanboom233** [comment]
![image](https://user-images.githubusercontent.com/43744483/176991876-66b57c6d-2083-4b0d-bd1e-59bc68cc3b6d.png)

**Comment by yujincheng08** [comment]
try again.
