### ISSUE TITLE
Can't launch WSA after updated 2205.40000.14.0_x64_Release-Nightly ! 无法启动WSA  !

### ISSUE THREAD

**Issue by HumanMusicX** [LSPosed/MagiskOnWSA#453]
Can't open any Apps after updated 2205.40000.14.0_x64_Release-Nightly !
安装了最新更新之后就无法启动WSA的所有APP !

[log file]👇

[20220709161351.log](https://github.com/LSPosed/MagiskOnWSA/files/9076108/20220709161351.log)

**Comment by Mohamed-Helal-qw** [comment]
Same problem

**Comment by Howard20181** [comment]
> Can't open any Apps after updated 2205.40000.14.0_x64_Release-Nightly ! 安装了最新更新之后就无法启动WSA的所有APP !
> 
> [log file]👇
> 
> [20220709161351.log](https://github.com/LSPosed/MagiskOnWSA/files/9076108/20220709161351.log)

尝试构建一个无gapps的版本测试能不能启动

**Comment by Howard20181** [comment]
现在微软撤包了，等下个版本且OpenGapps支持Android 12.1后遇到问题再反馈吧

**Comment by HumanMusicX** [comment]
> 现在微软撤包了，等下个版本且OpenGapps支持Android 12.1后遇到问题再反馈吧

我把之前一直继承数据的版本完全卸载之后（备份了userdata.vhdx文件），然后重新安装了一边，就正常了，但是当我用之前的替换掉userdata.vhdx文件之后，就又出现无法启动的问题。重新换回初始的userdata.vhdx文件就又一切正常了。不知道对你们有没有帮助。
