### ISSUE TITLE
Updating to Newest Release: Now Display is Sideways and UI Interaction is Difficult

### ISSUE THREAD

**Issue by richaardvark** [LSPosed/MagiskOnWSA#459]
I have been running MagiskOnWSA without issue for several months.  I just now forked the latest release and ran the workflow to update my WSA to the newest version.  Everything went smoothly and there were no errors displayed.  However, now half of my WSA applications are loading sideways/are displayed in the wrong orientation. I have tried pressing "control + F11" as a quick Google search shows that this will toggle between landscape and portrait modes on WSA and it does indeed to this but while the display is no longer sideways the touch and swipe actions on this app are still processing/happening as sideways and I am unable to toggle wireless ADB debugging from the Developer Settings menu (see screenshot below). How cant I resole this issue and make the WSA UI actually usable once again?  Thanks!

![image](https://user-images.githubusercontent.com/41244847/178152549-162d1c93-18f0-4006-a412-3cc842e047e1.png)

**Comment by Howard20181** [comment]
https://stackoverflow.com/questions/25864385/changing-android-device-orientation-with-adb

**Comment by richaardvark** [comment]
Why was this closed? You never resolved my issue. I am not asking for a new feature to be added here... I am simply asking for the existing release to function properly as it is currently unusable with the display turned sideways, half cut off, and unable to be interacted with by the user.

**Comment by Howard20181** [comment]
> Why was this closed? You never resolved my issue. I am not asking for a new feature to be added here... I am simply asking for the existing release to function properly as it is currently unusable with the display turned sideways, half cut off, and unable to be interacted with by the user.

Ask Microsoft for help.

**Comment by richaardvark** [comment]
> https://stackoverflow.com/questions/25864385/changing-android-device-orientation-with-adb

I am familiar with how to change the device orientation using ADB. I cannot authorize ADB however because I cannot see the user interface. It is impossible to authorize any ADB connections so therefore I cannot run any ADB commands.

**Comment by richaardvark** [comment]
> > Why was this closed? You never resolved my issue. I am not asking for a new feature to be added here... I am simply asking for the existing release to function properly as it is currently unusable with the display turned sideways, half cut off, and unable to be interacted with by the user.
> 
> Ask Microsoft for help.

MagiskOnWSA is not a Microsoft product.

**Comment by yujincheng08** [comment]
> MagiskOnWSA is not a Microsoft product.

So all possible issues by WSA should be solved by us. Charming.

**Comment by Howard20181** [comment]
WSA's adb does not require authorization.

We didn't modifiy this part, and we can't fix the problem with WSA itself.
