### ISSUE TITLE
If i download x64 magiskonwsa after 755mb it shows completed download. But when 8 process to install comes error because file is not downloadable or not downloading i try manu times in different browsers and different devices but result is same please solve it

### ISSUE THREAD

**Issue by m-d-zeeshan** [LSPosed/MagiskOnWSA#460]
If i download x64 magiskonwsa after 755mb it shows completed download. But when 8 process to install comes error because file is not downloadable or not downloading i try manu times in different browsers and different devices but result is same please solve it

**Comment by yujincheng08** [comment]
i cannot understand ur language.

**Comment by thecientific** [comment]
I have the same issue, when we try downlead the file WSA-with-magisk-NoGApps_2205.40000.14.0_x64_Release-Nightly.zip show complete from 700mb to 800mb, I try use different computer and different internet provider, same result. The question is, GitHub place limit download for big files?
