### ISSUE TITLE
Install script cannot run on Powershell 7

### ISSUE THREAD

**Issue by c6ForH66** [LSPosed/MagiskOnWSA#461]
I tried to run the script on Powershell 7(Powershell 5.1 is OK), but the window just closed after showing "the operation was done successfully" and then there was just no response.

**Comment by PeterNjeim** [comment]
I've been using PowerShell 7 for the past several months, no issues on my end

**Comment by partymike** [comment]
I was running into the same issue on my surface pro x, but it did start to install about 4 to 5 mins after the "the operation was done successfully" message - I would say just leave the console open to see if it completes.
