### ISSUE TITLE
Any way to install MagiskOnWSA for multiple windows users?

### ISSUE THREAD

**Issue by neonitly** [LSPosed/MagiskOnWSA#466]
Apologies if this has been answered already, but I can't find it in the closed tickets.

I have three different user accounts on my PC, all of them administrators. 
I can successfully install MagiskOnWSA on one account, no problem. However WSA is not available for the other two users. When I try to run the install again on a second user profile, I get the 0x80073CFB error saying that the provided package is already installed.

Does anyone know if there's a way to install WSA for all users or manually install it for each user successfully?

**Comment by yujincheng08** [comment]
Ask microsoft.
