### ISSUE TITLE
Advanced Networking Not Available

### ISSUE THREAD

**Issue by jimmietron** [LSPosed/MagiskOnWSA#468]
First off, thank you for your work. I searched opened and closed issues and didn't find anything concerning this. My understanding is that Build 2204.40000.19.0 introduced the advanced networking option where WSA can see other devices on the same network. I updated to "WSA-with-magisk-GApps-pico_2204.40000.19.0_x64_Release-Nightly" and now 2205.40000.14.0, and it seems like all the new features are available, except for advanced networking. Is there something I'm missing? Thank you!
<img width="733" alt="screenshot" src="https://user-images.githubusercontent.com/96714198/179135146-ae4a3b89-d760-44de-926e-95604143ea46.png">
?BTW, my computer is a HP Pavilion x360 Convertible Laptop- 14m-dw0023dx with 10th Gen Intel Core i5 1035G1, 16 GB RAM, 256 GB SSD with about 93 GB free space, Windows 11 21H2 build 22000.795.

**Comment by armandojrod** [comment]
It shows for me but greyed out 

![image](https://user-images.githubusercontent.com/10835960/179338752-b488af1e-1409-464a-bab5-18dcb552ae22.png)

**Comment by yujincheng08** [comment]
> It shows for me but greyed out, same WSA version with Pico Gapps
> 
> ![image](https://user-images.githubusercontent.com/10835960/179338752-b488af1e-1409-464a-bab5-18dcb552ae22.png)
> 

bcz u have a vpn enabled

**Comment by armandojrod** [comment]
> > It shows for me but greyed out, same WSA version with Pico Gapps

> bcz u have a vpn enabled

I have one installed on Windows but it isnt enabled at the time I took the screenshot, its Cyberghost, the thing running is the service and the setting its same even when the service is also stopped

(I dont know if its a bug in WSA or only this version tho)

**Comment by yujincheng08** [comment]
Not our issue.
