### ISSUE TITLE
Resolution and vca runtime

### ISSUE THREAD

**Issue by janat08** [LSPosed/MagiskOnWSA#469]
I opened the wsa settings app, and I got like 3 errors about vca and the like. Is that where I'd find resolution settings? Things are too big on my screen.

**Comment by yujincheng08** [comment]
Ask microsoft.

**Comment by janat08** [comment]
Or you can install another android version that comes with play services and works. The apps I was looking to use required play services.

**Comment by janat08** [comment]
Although they don't have resolution settings.
