### ISSUE TITLE
Memory usage on Surface Pro X (ARM x64) is using > 2GB RAM

### ISSUE THREAD

**Issue by Yusof333** [LSPosed/MagiskOnWSA#477]
Is it normal to have > 2GB RAM used? This pushes a 8GB RAM Surface Pro X to a crawl (1-2GB free after starting) and crashing Android Apps on the tablet. Perhaps there's some build option to reduce the memory footprint?

Good job with the project. Thanks.

**Comment by Yusof333** [comment]
The process is called VmmemWSA using 2.2GB. WSA for Android using ~ 300MB max.

**Comment by Howard20181** [comment]
> Is it normal to have > 2GB RAM used? 

This is normal, as it can allocate up to 6GB.
> Perhaps there's some build option to reduce the memory footprint?

Ask Microsoft for help.
