### ISSUE TITLE
Cannot run WSA. 

### ISSUE THREAD

**Issue by viethung9at1** [LSPosed/MagiskOnWSA#478]
The starting dialog show then disappear and Task manager shows that WSA not running (eat only under 100MB of RAM)
P/s: I have fixed the error but with the uninstall in Setting

**Comment by callng** [comment]
> The starting dialog show then disappear and Task manager shows that WSA not running (eat only under 100MB of RAM) P/s: I have fixed the error but with the uninstall in Setting

Delete 【%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx】Then rerun WSA
