### ISSUE TITLE
WSA won't download

### ISSUE THREAD

**Issue by RickyAsbury** [LSPosed/MagiskOnWSA#479]
![image](https://user-images.githubusercontent.com/75904443/180335862-a99e2f2b-ea38-4cb2-8da0-39003c29be61.png)
again don't know how to explain this but here's the image

**Comment by RickyAsbury** [comment]
aand edge didn't get the entire image sorry anyways that happened while it was trying to download WSA

**Comment by nnnphu269** [comment]
yup me too

**Comment by SeymourSays** [comment]
From a closed Issue, it seems this is an issue the developers can't fix. Most likely to do with the download source(Where the Build Action downloads the WSA files)
Best bet is to rerun every so often to attempt to get the download through, although it is still down when I checked ~15 minutes ago.

**Comment by yujincheng08** [comment]
Fixed by #481
