### ISSUE TITLE
Suggesting to use of MindTheGapps

### ISSUE THREAD

**Issue by someone5678** [LSPosed/MagiskOnWSA#485]
https://gitlab.com/MindTheGapps/vendor_gapps

This package supports all the arch just like OpenGapps does.
But it's even more smaller than OpenGapps' Pico package.
It's maintained by LineageOS' devs.

Since it should be manually build the package,
If possible, I suggests download the gapps apks, permissions, etc. directly from the GitLab repo and merge into WSA package during Github Action.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/MagiskOnWSA/tree/mindthegapps

Tried. But with no luck. We need to download AOSP source code and compiles for hours.
