### ISSUE TITLE
Getting virtualization error even though it's enabled

### ISSUE THREAD

**Issue by Mr-Nobody1** [LSPosed/MagiskOnWSA#489]
![image](https://user-images.githubusercontent.com/73386704/181633110-6db5db4f-672f-4699-bccc-c7b621d46b38.png)

**Comment by yujincheng08** [comment]
check ur bios

**Comment by Mr-Nobody1** [comment]
> check ur bios

Already did..it is enabled there and also HYPER V is also enabled but it still doesn't work

**Comment by yujincheng08** [comment]
> HYPER V is also enabled

Virtual Machine Platform is not HYPER V.


![image](https://user-images.githubusercontent.com/5022927/181788569-2db2fee3-75ee-49f0-bbc3-4527ef664cd9.png)

**Comment by Mr-Nobody1** [comment]
Still!
![image](https://user-images.githubusercontent.com/73386704/181796339-7e9ad749-f17d-45bc-a80b-5acf9b16d3de.png)

**Comment by Mr-Nobody1** [comment]
![image](https://user-images.githubusercontent.com/73386704/181796454-c9a252e9-a633-4e14-abf9-1d9f83bc387a.png)

**Comment by Mr-Nobody1** [comment]
A few months ago, It worked perfectly fine but idk after I tried again it is not working now

**Comment by Mr-Nobody1** [comment]
should I try restarting and re-enabling virtualization from the bios?
