### ISSUE TITLE
Stack-Based buffer error

### ISSUE THREAD

**Issue by Mr-Nobody1** [LSPosed/MagiskOnWSA#492]
![image](https://user-images.githubusercontent.com/73386704/181804257-8a089029-77f6-4fbe-9d1b-129e1ee233ee.png)

And still getting the virtualization error even though everything is done right (Yes, I have checked my bios and extra features)

the above error pops up when I open the WsaSetting.exe

**Comment by yujincheng08** [comment]
Ask Microsoft.
