### ISSUE TITLE
consistently getting gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by AskAlice** [LSPosed/MagiskOnWSA#496]
I've rerun this job three times, and the second time i waited 18 hours before rerunning it
https://github.com/AskAlice/wsa/runs/7637890886?check_suite_focus=true#step:2:695
```
Processing triggers for wine (5.0-3ubuntu1) ...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
##[debug]Finishing: Dependencies
```

**Comment by yujincheng08** [comment]
Seek help here: https://github.com/orgs/community/discussions/categories/actions-and-packages
