### ISSUE TITLE
error when running script surface pro x

### ISSUE THREAD

**Issue by partymike** [LSPosed/MagiskOnWSA#502]
I get the following error using the arm64 version (i've installed the x64 version on a surface pro 8 with no issues):

Get-WindowsOptionalFeature: C:\Users\mike\Downloads\WSA-with-magisk-GApps-pico_2205.40000.21.0_arm64_Release-Nightly\Install.ps1:42
Line |
  42 |  $VMP = Get-WindowsOptionalFeature -Online -FeatureName 'VirtualMachin …
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered

Enable-WindowsOptionalFeature: VirtualMachinePlatform [Running                                                       ]

The script then asks to reboot - however under optional windows features the "virtual machine platform" is enabled & the surface pro x has virtualisation enabled in the BIOS by default (it runs minimal BIOS).

After reboot the same process happens again above - I've gone through it 3 times and also tried manually disabling the "virtual machine platform" rebooting and re-enabling but the script still fails on line 42 as above.

Can you assist?

**Comment by partymike** [comment]
I ended up just editing the install.ps1 file to remove the check against the virtual machine being selected, and then the script ran fine to completion - if that helps anyone who has the same issue in the future.

**Comment by Na-Ku** [comment]
> I ended up just editing the install.ps1 file to remove the check against the virtual machine being selected, and then the script ran fine to completion - if that helps anyone who has the same issue in the future.

I think this purpose should be merged
