### ISSUE TITLE
Can not get real root access

### ISSUE THREAD

**Issue by liaolunhui** [LSPosed/MagiskOnWSA#503]
Can not manipulate root file system.
I use Root Browser to add file to / and /system/etc/security/cacerts/ , it say fail.
But I already granted root access via migisk to Root Browser.

**Comment by canyie** [comment]
https://twitter.com/topjohnwu/status/1170404633371525120?s=19

**Comment by HuskyDG** [comment]
You can use WSL, mount `system.img` and edit
