### ISSUE TITLE
如图，无法定位程序输入点 于动态链接库

### ISSUE THREAD

**Issue by 1457384613gh** [LSPosed/MagiskOnWSA#504]
![image](https://user-images.githubusercontent.com/69227436/183272490-9e88fd88-5b80-4007-85b0-f9141ded2b57.png)

**Comment by Howard20181** [comment]
向微软反馈

**Comment by 1457384613gh** [comment]
> 向微软反馈

你的意思是，这是 WSA的问题。
安装原版，也会这样？

**Comment by Howard20181** [comment]
> > 向微软反馈
> 
> 你的意思是，这是 WSA的问题。 安装原版，也会这样？

未对该部分修改
我们无法修复
