### ISSUE TITLE
Build Faild

### ISSUE THREAD

**Issue by sahoonalinikanta** [LSPosed/MagiskOnWSA#508]
While executing the workflow ,it is failing again and again. I am trying to add Magisk in the RP variant for x64

**Comment by yujincheng08** [comment]
update your repo

**Comment by sahoonalinikanta** [comment]
sahoonalinikanta <https://github.com/sahoonalinikanta/sahoonalinikanta>   

 �

 �

With Regards

Nalinikanta Sahoo

 �
