### ISSUE TITLE
Magisk without gApps

### ISSUE THREAD

**Issue by MaxG-Enpal** [LSPosed/MagiskOnWSA#54]
Is it possible to provied an build just with magisk without gApps or with MicroG?

**Comment by aymhor** [comment]
ok thanks

**Comment by yujincheng08** [comment]
Fill `none` as GApps variant.

**Comment by MaxG-Enpal** [comment]
> 
> 
> Fill `none` as GApps variant.

Thanks.
I tried to run the ps1 file and it just closes after that.
Is it bad if I have WSA already installed?

**Comment by yujincheng08** [comment]
you need to uninstall the original one first
