### ISSUE TITLE
Uninstall of Magisk - Unable to detect target image

### ISSUE THREAD

**Issue by Loggsie** [LSPosed/MagiskOnWSA#55]
Uninstall of Magisk fails with 'Unable to detect target image'

![Magisk Uninstall](https://user-images.githubusercontent.com/89365430/140159645-aa05cc47-bd29-4b06-841a-369811223bde.jpg)

**Comment by yujincheng08** [comment]
WSA does not contain boot.img, so there's no way to uninstall it but replace it with the original installation.
