### ISSUE TITLE
Zygisk cause all apps crash

### ISSUE THREAD

**Issue by HuskyDG** [LSPosed/MagiskOnWSA#57]
When Zygisk is enabled in Magisk Settings, a time later, i have a problem that i cannot open any app in WSA, only notification can be pop up

Seems like this problem: https://github.com/topjohnwu/Magisk/issues/4872

**Comment by yujincheng08** [comment]
Yes, and that has been fixed. Please wait for the new canary build.

**Comment by yujincheng08** [comment]
It has been fix in the new canary release. https://github.com/topjohnwu/magisk-files/commit/59a2026a80990d9295ee8750b2aacd8f9beff30a

**Comment by HuskyDG** [comment]
Thanks
