### ISSUE TITLE
Magisk manager keep flashing and prompts for reboot

### ISSUE THREAD

**Issue by mcitew** [LSPosed/MagiskOnWSA#58]
After running magisk manager, it keeps promoting for reboot and cannot get it of the prompting. Seems not even responding to clicking on reboot or cancel buttons. 

Instructions call for "fixing the environment', but how ?

**Comment by yujincheng08** [comment]
It is caused by a bug from Magisk and has been fixed: https://github.com/topjohnwu/Magisk/pull/4817. Please make sure the Magisk you are using is Magisk later than this build. I think you are using older version of Magisk?

**Comment by mcitew** [comment]
Ok it is fixed with magisk canary build. But I have issue #57 now. I will close this.
