### ISSUE TITLE
About Magisk

### ISSUE THREAD

**Issue by Zaphkito** [LSPosed/MagiskOnWSA#60]
How can I update magisk version?
Only run workflow again?
Can I update it myself?

**Comment by Zaphkito** [comment]
I mean this
![image](https://user-images.githubusercontent.com/64299266/140618668-505ea83c-9a3d-49c7-8602-e6e2c73672a9.png)

**Comment by yujincheng08** [comment]
You cannot update it since the installation is read-only. The only way to upgrade it is by rerunning the workflow and replacing the previous version. By replacing, I mean overwrite the zip content and execute `install.ps1` again. You don't need to uninstall.
