### ISSUE TITLE
Merge the contents of the resource(language) package into the side-loaded folder

### ISSUE THREAD

**Issue by qwerty472123** [LSPosed/MagiskOnWSA#61]
I found a way to merge language packs (like `WsaPackage_1.7.32815.0_language-zh-hans.msix`) into the unpacked directory for side-loading(In another word, a solution for #36):

1. Merge others: Just unpack the resource package into the unpacked directory(without AppxBlockMap.xml AppxManifest.xml AppxSignature.p7x resources.pri [Content_Types].xml). (This step can be ignore for language pack.)
2. Merge AppxManifest.xml: Just merge the `/Package/Resources` in it.

As an example, the original `Resources` node in the main package's AppxManifest.xml is

```xml
  <Resources>
    <Resource Language="EN-US" />
    <Resource Language="EN-GB" />
    <Resource uap:Scale="200" />
  </Resources>
```

and the node in resource pack(`WsaPackage_1.7.32815.0_language-zh-hans.msix`) is

```xml
<Resources><Resource Language="zh-cn"/></Resources>
```

Then, the result is

```xml
  <Resources>
    <Resource Language="EN-US" />
    <Resource Language="EN-GB" />
    <Resource uap:Scale="200" />
    <Resource Language="zh-cn" />
  </Resources>
```

For ease of description, the following assumes that the merged `AppxManifest.xml` is in `X:\path\to\WSA\AppxManifest.xml`.

3. Merge resources.pri(The **CORE** step):
    1. rename the original pri file to `ori.pri`, and rename the pri in resource pack to `res.pri`. (Or any other names you like).
    2. Create a new xml file named `priconfig.xml`, and write the following content into it:

        ```xml
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <resources targetOsVersion="10.0.0" majorVersion="1">
	        <index root="\" startIndexAt="\">
		        <indexer-config type="folder" foldernameAsQualifier="true" filenameAsQualifier="true" qualifierDelimiter="."/>
		        <indexer-config type="PRI"/>
	        </index>
        </resources>
        ```

    3. Create a temporary directory at `X:\path\to\tmp`, and organize the previously mentioned files in the following form:

        ```plain
        X:\path\to
        \---tmp
            |   priconfig.xml
            |
            \---pris
                    ori.pri
                    res.pri
        ```

        (Just put pri files into `X:\path\to\tmp\pris` and put the `priconfig.xml` into `X:\path\to\tmp`)

    4. Get makepri.exe(It is a part of Windows SDK. You can find it by open `x64 Native Tools Command Prompt for VS 2019` after installing VS and Windows SDK. In my computer, it located at `C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\makepri.exe`) and run it as following:

        ```cmd
        makepri.exe new /pr X:\path\to\tmp\pris /cf X:\path\to\tmp\priconfig.xml /mn X:\path\to\WSA\AppxManifest.xml /of X:\path\to\tmp\resources.pri /o
        ```

    5. The generated `resources.pri` in `X:\path\to\tmp` is the merged one, put it to the side-load directory.

And I wonder if such a process can be integrated into workflow.

**Comment by yujincheng08** [comment]
That is interesting. But is there linux alternative for `makepri`?

**Comment by haohaoget** [comment]
> I found a way to merge language packs (like `WsaPackage_1.7.32815.0_language-zh-hans.msix`) into the unpacked directory for side-loading(In another word, a solution for #36):
> 
> 1. Merge others: Just unpack the resource package into the unpacked directory(without AppxBlockMap.xml AppxManifest.xml AppxSignature.p7x resources.pri [Content_Types].xml). (This step can be ignore for language pack.)
> 2. Merge AppxManifest.xml: Just merge the `/Package/Resources` in it.
> 
> As an example, the original `Resources` node in the main package's AppxManifest.xml is
> 
> ```
>   <Resources>
>     <Resource Language="EN-US" />
>     <Resource Language="EN-GB" />
>     <Resource uap:Scale="200" />
>     <Resource Language="zh-cn" />
>   </Resources>
> ```
> 
> and the node in resource pack(`WsaPackage_1.7.32815.0_language-zh-hans.msix`) is
> 
> ```
> <Resources><Resource Language="zh-cn"/></Resources>
> ```
> 
> Then, the result is
> 
> ```
>   <Resources>
>     <Resource Language="EN-US" />
>     <Resource Language="EN-GB" />
>     <Resource uap:Scale="200" />
>     <Resource Language="zh-cn" />
>   </Resources>
> ```
> 
> For ease of description, the following assumes that the merged `AppxManifest.xml` is in `X:\path\to\WSA\AppxManifest.xml`.
> 
> 1. Merge resources.pri(The **CORE** step):
>    
>    1. rename the original pri file to `ori.pri`, and rename the pri in resource pack to `res.pri`. (Or any other names you like).
>    2. Create a new xml file named `priconfig.xml`, and write the following content into it:
>       ```
>       <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>       <resources targetOsVersion="10.0.0" majorVersion="1">
>           <index root="\" startIndexAt="\">
>               <indexer-config type="folder" foldernameAsQualifier="true" filenameAsQualifier="true" qualifierDelimiter="."/>
>               <indexer-config type="PRI"/>
>           </index>
>       </resources>
>       ```
>    3. Create a temporary directory at `X:\path\to\tmp`, and organize the previously mentioned files in the following form:
>       ```
>       X:\path\to
>       \---tmp
>           |   priconfig.xml
>           |
>           \---pris
>                   ori.pri
>                   res.pri
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       (Just put pri files into `X:\path\to\tmp\pris` and put the `priconfig.xml` into `X:\path\to\tmp`)
>    4. Get makepri.exe(It is a part of Windows SDK. You can find it by open `x64 Native Tools Command Prompt for VS 2019` after installing VS and Windows SDK. In my computer, it located at `C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\makepri.exe`) and run it as following:
>       ```batchfile
>       makepri.exe new /pr X:\path\to\tmp\pris /cf X:\path\to\tmp\priconfig.xml /mn X:\path\to\WSA\AppxManifest.xml /of X:\path\to\tmp\resources.pri /o
>       ```
>    5. The generated `resources.pri` in `X:\path\to\tmp` is the merged one, put it to the side-load directory.
> 
> And I wonder if such a process can be integrated into workflow.

大佬可以提供一个你已经合并好的文件吗？安装SDK20g太大了电脑空间不够了

**Comment by qwerty472123** [comment]
> That is interesting. But is there linux alternative for `makepri`?

I cannot find such an alternative.

<https://github.com/actions/virtual-environments> mentioned Github Actions support Windows env. I think it may be the easiest solution.

Another possible solution is to use a technique like Wine.

The only position makepri.exe calls COM object is parsing AppxMainifest.xml to get index name(at /Package/Identity/@Name), which can be avoided by replaced `/mn X:\path\to\WSA\AppxManifest.xml` by `/in MicrosoftCorporationII.WindowsSubsystemForAndroid`(or other index indicated in the AppxMainifest.xml). It also calls some WinAPI to deal strings/read files/sync, but no too complex API has been called. So I think finding a toy implementation of PELoader, and replacing VirtualAlloc by mmap, and implementing its export functions which are used by hand is also a feasible solution. But I don't have enough time recently.

**Comment by yujincheng08** [comment]
> > That is interesting. But is there linux alternative for `makepri`?
> 
> I cannot find such an alternative.
> 
> https://github.com/actions/virtual-environments mentioned Github Actions support Windows env. I think it may be the easiest solution.
> 
> Another possible solution is to use a technique like Wine.
> 
> The only position makepri.exe calls COM object is parsing AppxMainifest.xml to get index name(at /Package/Identity/@name), which can be avoided by replaced `/mn X:\path\to\WSA\AppxManifest.xml` by `/in MicrosoftCorporationII.WindowsSubsystemForAndroid`(or other index indicated in the AppxMainifest.xml). It also calls some WinAPI to deal strings/read files/sync, but no too complex API has been called. So I think finding a toy implementation of PELoader, and replacing VirtualAlloc by mmap, and implementing its export functions which are used by hand is also a feasible solution. But I don't have enough time recently.

I see. Then we need two steps for it: first, generate merged resources from win env, and then everything together in linux

**Comment by qwerty472123** [comment]
@haohaoget makepri.exe 应该是一个可以独立运行的小程序。
你也可以在其他地方下载这个程序，比如 [其他 Github 项目](https://github.com/electron-userland/electron-builder-binaries/blob/master/winCodeSign/windows-10/x64/makepri.exe)。

**Comment by Sonic853** [comment]
it work for me. thanks!

**Comment by koubafire** [comment]
ERROR: PRI175: 0x80073b26 - Processing Resources failed with error: Operaci Load/UnloadPriFiles nelze použít s balíčky prostředků.

ERROR: PRI222: 0x80073b26 - Unspecified error occurred.

What with this?

**Comment by okibcn** [comment]
@yujincheng08 , Maybe I can do that during the installation script. However, that way all the languages should be bundled with the installer.

**Comment by yujincheng08** [comment]
@okibcn I think doing this during the installation script is better since data transfering between different workflow needs artifacts which may confuse users.

**Comment by yujincheng08** [comment]
Wine is working. Tried:
```
apt install wine winetricks
winetricks msxml6
wine64 makepri.exe new /pr pris /in MicrosoftCorporationII.WindowsSubsystemForAndroid /cf priconfig.xml /of resources.pri /o
```
and it did generate a `resources.pri` file
