### ISSUE TITLE
Recent WSA update 1.8.32322.0 prevents being able to login to Google Play Store

### ISSUE THREAD

**Issue by clubtech** [LSPosed/MagiskOnWSA#62]
Clicking the login button in Play Store no longer works (does not do anything). 
This started with the recent WSA build released yesterday (WSA version 1.8.32322.0).

**Comment by Arch-Storm** [comment]
Same problem here on 1.8.32322.0.

**Comment by crocer211** [comment]
you have to setenforce to zero in a adb shell with su using setenforce 0 for me that works at least

**Comment by Sayor0630** [comment]
> you have to setenforce to zero in a adb shell with su using setenforce 0 for me that works at leat

Doens't work!
![image](https://user-images.githubusercontent.com/77576588/141040120-ffdf87f6-1364-47ba-b78a-28981bf93699.png)

**Comment by KumaTea** [comment]
> you have to setenforce to zero in a adb shell with su using setenforce 0 for me that works at least

Thanks! It works like a charm.

![image](https://user-images.githubusercontent.com/36222458/141057370-03a54e64-d327-411e-a464-5b886464654c.png)

**Comment by HuskyDG** [comment]
It need to fix because i want to keep selinux enforcing

**Comment by Sayor0630** [comment]
> It need to fix because i want to keep selinux enforcing

Are you the developer of MagiskOnWSA?

**Comment by yujincheng08** [comment]
Thx for the notification. I will update the selinux.

**Comment by Sayor0630** [comment]
> Thx for the notification. I will update the SELinux.

Thank you. Please, do it fast if you can.

**Comment by HuskyDG** [comment]
> > It need to fix because i want to keep selinux enforcing
> 
> Are you the developer of MagiskOnWSA?

No, @yujincheng08 is developer of this project

**Comment by Sayor0630** [comment]
> > > It need to fix because i want to keep selinux enforcing
> > 
> > 
> > Are you the developer of MagiskOnWSA?
> 
> No, @yujincheng08 is developer of this project

oh. ok. But why he has just a contributor badge?
