### ISSUE TITLE
How to fix google signin issue

### ISSUE THREAD

**Issue by pazhanir** [LSPosed/MagiskOnWSA#66]
im trying to build a no magisk build. the build was success but im unable to signin into google

**Comment by yujincheng08** [comment]
How about build with magisk?

**Comment by HuskyDG** [comment]
> im trying to build a no magisk build. the build was success but im unable to signin into google

You need to change Selinux mode to Permissive
By ABD connect to WSA

```
adb connect localhost:58526
adb shell
su
setenforce 0
```

I hope it will be fixed soon as i want to keep it enforcing

**Comment by yujincheng08** [comment]
> > im trying to build a no magisk build. the build was success but im unable to signin into google
> 
> You need to change Selinux mode to Permissive By ABD connect to WSA (You will need Root)
> 
> ```
> adb connect localhost:58526
> adb shell
> su
> setenforce 0
> ```
> 
> I hope it will be fixed soon as i want to keep it enforcing

This issue has been fixed...

**Comment by yujincheng08** [comment]
I checked this build myself and it works like a charm.
https://github.com/LSPosed/MagiskOnWSA/actions/runs/1443352711

And I see the issuer has created its own build without magisk. So closing it.
