### ISSUE TITLE
hey, i just wanna know where could i get the magisk.apk for WSA?

### ISSUE THREAD

**Issue by MurkyWang** [LSPosed/MagiskOnWSA#67]
acroding to step 11 on the manual, the magisk.apk should be built by my own, but i cant find it anywhere.
so i downloaded and installed it from the url "https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk"
which could work with no error, but also no way to fix the environment.
i suppose i didnt get the right magisk.apk. or where did i go wrong?
PS its the latest version of WSA.
![屏幕截图 2021-11-11 003758](https://user-images.githubusercontent.com/54443955/141154561-72858231-7d00-41a7-8321-be139917ff27.png)

**Comment by yujincheng08** [comment]
https://github.com/MurkyWang/MagiskOnWSA/actions/runs/1444951999

you input `magisk, none` which means there wont have magisk integrated.
