### ISSUE TITLE
Update magisk procedure on WSA

### ISSUE THREAD

**Issue by mcitew** [LSPosed/MagiskOnWSA#70]
I have got magisk and magisk manager and root working on WSA, but for some reason say I want to try a different version of magisk and magisk manager, what can I do to update the integrated version with another ? Will it work if I just install the new magisk.zip via magisk manager ?

**Comment by yujincheng08** [comment]
when running workflow, fill your own magisk's download link. you cannot update integrated magisk within WSA since all partitions are readonly.
