### ISSUE TITLE
Where does one get the Magisk.apk file?  

### ISSUE THREAD

**Issue by Almighty188** [LSPosed/MagiskOnWSA#74]
Where does one get the Magisk.apk file?

**Comment by haohaoget** [comment]
in magisk.yml you can find default: 'https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk'

**Comment by yujincheng08** [comment]
Use the one you used to trigger the workflow.

**Comment by Almighty188** [comment]
> Use the one you used to trigger the workflow.

Where exactly can I find it as I did the workflow the same way as illustrated in the main page by running workflow but I don't see the apk anywhere.

**Comment by yujincheng08** [comment]
> > Use the one you used to trigger the workflow.
> 
> Where exactly can I find it as I did the workflow the same way as illustrated in the main page by running workflow but I don't see the apk anywhere.

You are required to input download link of magisk apk. And well, you know the download link, right?

**Comment by Almighty188** [comment]
> > > Use the one you used to trigger the workflow.
> > 
> > 
> > Where exactly can I find it as I did the workflow the same way as illustrated in the main page by running workflow but I don't see the apk anywhere.
> 
> You are required to input the download link of magisk apk. And well, you know the download link, right?

I think I skipped that step as I was looking at your README.md and it seems I only did the stock part when it came to step 5.  I looked at the master workflow and I can see that it's 'https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk' so I probably used whatever was default.  Still new to Github.
