### ISSUE TITLE
virtualization enabled???? how to???

### ISSUE THREAD

**Issue by Hectorlascano** [LSPosed/MagiskOnWSA#77]
![wsa_error](https://user-images.githubusercontent.com/94115951/141387693-1ebd76d7-f3b9-49b4-b466-338eb89b9b68.png)
hi, first, thanks to you all doing this for us.
second, can any of you helpe me? 
the image shows the error....

**Comment by Raju** [comment]
Please run the below command in powershell.

Open PowerShell as Administrator and run:

`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/141413131-8d197f1f-57fa-497f-9f34-bdbf1ad66bdc.png)
This one.

**Comment by Hectorlascano** [comment]
Thanks
