### ISSUE TITLE
I can't download the complete x64-zip,i try many times to download

### ISSUE THREAD

**Issue by jackblackjjx** [LSPosed/MagiskOnWSA#78]
As above,when i download it ok,It just has 500+M, I extract it, it promots me it is a destory zip，I change my network many times ,too.
but downloaded zip also damaged

**Comment by yujincheng08** [comment]
Github is showing the uncompressed size of artifacts. The download size is compressed. So this is expected.

**Comment by tfragment** [comment]
@jackblackjjx  You can download this if you're having problems with github.
I downloaded it via vps and uploaded it to [Mediafire](https://www.mediafire.com/file/w5609c03iutonnb/WSA-with-magisk-GApps-nano_1.8.32822.0_x64_Release-Nightly.zip/file).
