### ISSUE TITLE
Iit works on windows 11 home?

### ISSUE THREAD

**Issue by Hectorlascano** [LSPosed/MagiskOnWSA#80]
i did install magisk...l and dont works.

i see several videos and one of then mentions i neede activate HYPER-V.

microsoft documentation indicates hyper-v need windows pro.

will i upgrade to windows 11 pro?

references:
https://docs.microsoft.com/es-es/virtualization/hyper-v-on-windows/about/
![Screenshot_5](https://user-images.githubusercontent.com/94115951/141473064-7604be3c-da3f-4a6c-a249-9de105fd399f.png)
![Screenshot_8](https://user-images.githubusercontent.com/94115951/141473067-d30d34e9-9fd8-4e06-bc12-c29e91a2c513.png)

**Comment by nahid6970** [comment]
You don't need to install magisk. Magisk will be automatically installed. Only canary version of magisk works with WSA right now.

**Comment by Hazmi35** [comment]
Do you mean WSA? Magisk doesn't require Hyper-V. WSA also doesn't require Hyper-V, but it requires "Virtual Machine Platform" to be enabled, which itself is Hyper-V but less feature, so yes WSA can run on Windows 11 Home.

(WSA is based on WSL2, which requires Virtual Machine Platform, not Hyper-V)

**Comment by yujincheng08** [comment]
Answers should be clear.

**Comment by Hectorlascano** [comment]
Ok. Then I don't know why it's no working.
I did all steps..


 I hit developer mode on wsa. Then hit configure developer mode. Nothing happens (just a loading screen... Then it closes and nothing happens) 

Then I hit files button. Nothing happens.... (just a loading screen... Then it closes and nothing happens)  

😢😢😢😢

**Comment by tfragment** [comment]
@Hectorlascano  The same thing is happening to me. :sad:

**Comment by Hectorlascano** [comment]
> @Hectorlascano  The same thing is happening to me. :sad:

I'm giving up...
Actually I wanted wsa to run capcut... And I find capcut for pc... In Chinese... 🤔😜😀🙄😊

I'm translating to use the app... It's the best...

At the moment will not struggling whit wsa... In the future may be....

**Comment by tfragment** [comment]
@Hectorlascano  Yeah, I was thinking of giving up as well. And also, I've already used up a significant portion of my data package downloading it, but sometimes things just don't work out for ya. And I suppose the only thing you could do is keep doing it till it could? lol
