### ISSUE TITLE
Magisk version 23.0

### ISSUE THREAD

**Issue by Denniso2** [LSPosed/MagiskOnWSA#82]
When creating a new workflow with magisk 23 I get the following error
```There is no item named 'lib/x86_64/libmagisk64.so' in the archive```
Magisk canary works just fine.Correct path looks like ```lib/x86/libmagisk64.so```
Same problem with arm64

**Comment by yujincheng08** [comment]
Sorry, only Magisk canary could work since Magisk 23.0 has bugs that cannot run on WSA.
