### ISSUE TITLE
Magisk and Magisk Manager

### ISSUE THREAD

**Issue by Uwid2021** [LSPosed/MagiskOnWSA#83]
![2021-11-13_120040](https://user-images.githubusercontent.com/93023988/141607989-de3b0525-3f01-4093-a99b-1761c30854a3.jpg)
Since I'm new with magisk, my magisk app already installed but I wonder about magisk manager or magisk app is magisk manager too?
What should I do about fix the environment and the purposes of Riru and LSPosed module. Thanks in advance

**Comment by yujincheng08** [comment]
`Magisk manager` renamed to `Magisk` since Magisk 
https://github.com/topjohnwu/Magisk/commit/6951d926f7affde1cd7965be6e5ce6091f90c798
