### ISSUE TITLE
ResourceUnavailable: Program 'WsaClient.exe' failed to run: The system cannot find the path specified.At line:1 char:1

### ISSUE THREAD

**Issue by TylerJaacks** [LSPosed/MagiskOnWSA#84]
I'm getting this after sometime using the application.

ResourceUnavailable: Program 'WsaClient.exe' failed to run: The system cannot find the path specified.At line:1 char:1

**Comment by Howard20181** [comment]
Do not move or delete the folder of the extracted WSA zip package.
