### ISSUE TITLE
Huge time waste

### ISSUE THREAD

**Issue by megapro17** [LSPosed/MagiskOnWSA#86]
Why are suggesting cloning repo and creating package when for the most users it's better just to download prebuild package?? Imagine how much energy is wasted for each user, creating the same build each time. It's pointless and harmful. Not mentioning that you also need to wait before you can get that image.

**Comment by Coxxs** [comment]
Redistributing modified commercial softwares may cause legal problems.

**Comment by yujincheng08** [comment]
And we suggest customization.

**Comment by megapro17** [comment]
> Redistributing modified commercial softwares may cause legal problems.

Who cares



> And we suggest customization.

LMAO customization, everyone is using pico Gapps with magisk
