### ISSUE TITLE
WSA can never pass safetynet ?

### ISSUE THREAD

**Issue by mcitew** [LSPosed/MagiskOnWSA#91]
I have a build of WSA with Magisk 23014, Riru, zygist and usnf 2.2. But safetynet attestation still fails at basic integrity and CTS profile match. So there is no way out to this ?

**Comment by HuskyDG** [comment]
> I have a build of WSA with Magisk 23014, Riru, zygist and usnf 2.2. But safetynet attestation still fails at basic integrity and CTS profile match. So there is no way out to this ?

You should read this https://developer.android.com/training/safetynet/attestation

**Comment by mcitew** [comment]
That is not helping as all that I am trying to determine is whether it is my own configuration problem, or it is the current state of the affairs which is still pending some better solution.

**Comment by HuskyDG** [comment]
> That is not helping as all that I am trying to determine is whether it is my own configuration problem, or it is the current state of the affairs which is still pending some better solution.

You are wrong, baby. Emulator will never pass SafetyNet. And you don't know how SafetyNet works. Stop asking for pass SafetyNet on emulator!!!
