### ISSUE TITLE
How to change physical keyboard layout?

### ISSUE THREAD

**Issue by alex-sandro92** [LSPosed/MagiskOnWSA#98]
I have an Italian keyboard but in WSA it is set as an Us keyboard, so when I need to type a symbol, I have to use Gboard on screen.
I didn't find a way to fix this since there is no Settings app like in an Android smartphone. Any ideas?

**Comment by alex-sandro92** [comment]
Solved: I had to set my language as primary on windows

**Comment by Slion** [comment]
Same issue here with an custom ASERTY NF Z71-300 layout. Windows is in English but I'm using an AZERTY layout. Everything was working fine with the official WSA.
@alex-sandro92 Could you explain what you did exactly to fix it?

**Comment by Slion** [comment]
No such issue when using Pico GApps instead of Super.

**Comment by alex-sandro92** [comment]
Hi @Slion, if you go into Input&Language settings on windows, you have to set the correct language as primary (putting it on the top of the list).
But I found another way: you can change the keyboard settings directly on the Setting app (like the one you find on the smartphones). In order to open it I use [WSA Pacman](https://github.com/alesimula/wsa_pacman)

**Comment by Slion** [comment]
Thanks, luckily I don't need to fidle with that since I'm using the pico gapps instead of the supper gapps I don't have any issue. I'm guessing this is caused by gboard or something.
